import type {CSSProperties} from 'react';
import {dates,dateField,dayAdd,EmptyModule,field,format,groupField,Hint,number,records,title,today,valueField,type ModuleProps,type ModuleRegistry} from './shared';

const palette=['var(--accent)','#bd9066','#8fa3a0','#b97f8b','#8a879f','#aaa063'];
function numeric(p:ModuleProps){const f=valueField(p);return {f,rows:records(p).filter(r=>f&&typeof r.values[f.id]==='number')};}
function DataList({entries}:{entries:[string,string|number][]}){return <details className="module-data"><summary>View data</summary><dl>{entries.map(([k,v],i)=><div key={`${k}-${i}`}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></details>}
function MetricGrid(p:ModuleProps){const {f,rows}=numeric(p);if(!f||!rows.length)return <EmptyModule message="Bind a numeric field and add values to see your metrics."/>;const values=rows.map(r=>number(r.values[f.id])),sum=values.reduce((a,b)=>a+b,0);return <div className="metric-tiles">{[['Total',sum],['Average',sum/values.length],['Lowest',Math.min(...values)],['Highest',Math.max(...values)]].map(([label,n])=><div key={label}><small>{label}</small><strong>{format(p,n as number)}</strong></div>)}<Hint>{values.length} values · {f.label}</Hint></div>}
function LineChart(p:ModuleProps){const d=dateField(p),{f,rows}=numeric(p);if(!d||!f)return <EmptyModule message="Bind a date and a numeric field to see a trend."/>;const sums=new Map<string,number>();for(const r of rows)for(const day of dates(r.values[d.id]))sums.set(day,(sums.get(day)??0)+number(r.values[f.id]));const entries=[...sums].sort(([a],[b])=>a.localeCompare(b));if(!entries.length)return <EmptyModule/>;const min=Math.min(0,...entries.map(([,n])=>n)),max=Math.max(1,...entries.map(([,n])=>n));const pt=(n:number,i:number)=>[35+i*(430/Math.max(1,entries.length-1)),190-(n-min)/(max-min)*155];return <><Hint>{f.label} · daily totals</Hint><svg className="module-chart" viewBox="0 0 500 230" role="img" aria-label={`Daily totals for ${f.label}`}><path d="M35 25V190H465" className="chart-axis"/><polyline points={entries.map(([,n],i)=>pt(n,i).join(',')).join(' ')} className="chart-line"/>{entries.map(([day,n],i)=>{const [x,y]=pt(n,i);return <circle key={day} cx={x} cy={y} r="4" fill="var(--accent)"><title>{day}: {format(p,n)}</title></circle>})}<text x="35" y="216">{entries[0][0]}</text><text x="465" y="216" textAnchor="end">{entries.at(-1)![0]}</text><text x="35" y="16">{format(p,max)}</text></svg><DataList entries={entries.map(([d,n])=>[d,format(p,n)])}/></>}
function DonutChart(p:ModuleProps){const g=groupField(p),v=p.spec.valueField?valueField(p):undefined;if(!g)return <EmptyModule message="Choose a category field to show proportions."/>;const entries=(g.options??[]).map(k=>[k,records(p).filter(r=>r.values[g.id]===k).reduce((s,r)=>s+(v?Math.max(0,number(r.values[v.id])):1),0)] as [string,number]);const total=entries.reduce((s,[,n])=>s+n,0);if(!total)return <EmptyModule/>;let offset=0;const gradient=entries.map(([,n],i)=>{const start=offset;offset+=n/total*100;return `${palette[i%palette.length]} ${start}% ${offset}%`}).join(',');return <div className="donut-layout"><div className="donut-disc" style={{background:`conic-gradient(${gradient})`}} role="img" aria-label={`Category shares: ${entries.map(([k,n])=>`${k} ${format(p,n)}`).join(', ')}`}><div><strong>{format(p,total)}</strong><small>{v?'positive total':'records'}</small></div></div><div className="chart-legend">{entries.map(([k,n],i)=><div key={k}><i style={{background:palette[i%palette.length]}}/><span>{k}</span><strong>{Math.round(n/total*100)}%</strong></div>)}</div></div>}
function Histogram(p:ModuleProps){const {f,rows}=numeric(p);if(!f||!rows.length)return <EmptyModule message="Add numeric values to see their distribution."/>;const ns=rows.map(r=>number(r.values[f.id])),lo=Math.min(...ns),hi=Math.max(...ns),count=p.spec.config?.bins??6,width=(hi-lo||1)/count,bins=Array.from({length:count},(_,i)=>({label:`${format(p,lo+i*width)}–${format(p,lo+(i+1)*width)}`,count:0}));for(const n of ns)bins[Math.min(count-1,Math.floor((n-lo)/width))].count++;const peak=Math.max(1,...bins.map(b=>b.count));return <><Hint>{f.label} · {ns.length} values</Hint><div className="histogram" role="img" aria-label="Value distribution">{bins.map((b,i)=><div key={b.label}><span>{b.count}</span><i style={{height:`${b.count/peak*140+2}px`}}/><small>{i+1}</small></div>)}</div><DataList entries={bins.map(b=>[b.label,b.count])}/></>}
function ScatterPlot(p:ModuleProps){const x=field(p,'number'),y=field(p,'number',1);if(!x||!y)return <EmptyModule message="Bind two numeric fields to compare their relationship."/>;const rs=records(p).filter(r=>typeof r.values[x.id]==='number'&&typeof r.values[y.id]==='number');if(!rs.length)return <EmptyModule/>;const xs=rs.map(r=>number(r.values[x.id])),ys=rs.map(r=>number(r.values[y.id]));const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return <><Hint>{x.label} × {y.label}</Hint><svg className="module-chart" viewBox="0 0 500 245" role="img" aria-label={`${x.label} compared with ${y.label}`}><path d="M40 20V200H470" className="chart-axis"/>{rs.map(r=><circle key={r.id} cx={40+(number(r.values[x.id])-minX)/(maxX-minX||1)*425} cy={200-(number(r.values[y.id])-minY)/(maxY-minY||1)*175} r="6" fill="var(--accent)" opacity=".7"><title>{title(p,r)}: {r.values[x.id]}, {r.values[y.id]}</title></circle>)}<text x="255" y="230" textAnchor="middle">{x.label}</text><text x="42" y="15">{y.label}</text></svg><details className="module-data"><summary>View records</summary>{rs.map(r=><button className="module-row module-button" key={r.id} onClick={()=>p.onSelect(r)}>{title(p,r)}<span>{format(p,number(r.values[x.id]))} / {format(p,number(r.values[y.id]))}</span></button>)}</details></>}
function ActivityHeatmap(p:ModuleProps){const f=dateField(p);if(!f)return <EmptyModule message="Bind a date or check-in history field."/>;const end=today(p),days=Array.from({length:84},(_,i)=>dayAdd(end,i-83)),counts=new Map<string,number>();for(const r of records(p))for(const d of dates(r.values[f.id]))counts.set(d,(counts.get(d)??0)+1);const peak=Math.max(1,...counts.values());return <><Hint>Last 12 weeks · {f.label}</Hint><div className="activity-grid" role="img" aria-label="Activity intensity over the last 84 days">{days.map(d=><span key={d} style={{'--intensity':(counts.get(d)??0)/peak} as CSSProperties} title={`${d}: ${counts.get(d)??0}`}><span className="sr-only">{d}: {counts.get(d)??0}</span></span>)}</div><Hint>Less <span className="heat-key"/> More · today {counts.get(end)??0}</Hint><DataList entries={days.filter(d=>counts.has(d)).map(d=>[d,counts.get(d)!])}/></>}
function Leaderboard(p:ModuleProps){const {f,rows}=numeric({...p,spec:{...p.spec,config:{...p.spec.config,limit:undefined}}});if(!f||!rows.length)return <EmptyModule/>;return <ol className="leaderboard">{rows.sort((a,b)=>number(b.values[f.id])-number(a.values[f.id])).slice(0,p.spec.config?.limit??rows.length).map((r,i)=><li key={r.id}><span className="rank">{String(i+1).padStart(2,'0')}</span><button onClick={()=>p.onSelect(r)}>{title(p,r)}</button><strong>{format(p,number(r.values[f.id]))}</strong></li>)}</ol>}
function Funnel(p:ModuleProps){const f=groupField(p);if(!f)return <EmptyModule message="Choose an ordered category field for this stage view."/>;const rs=records(p),entries=(f.options??[]).map(k=>[k,rs.filter(r=>r.values[f.id]===k).length] as [string,number]),max=Math.max(1,...entries.map(([,n])=>n));return <><Hint>Current stage distribution · not conversion rates</Hint><div className="funnel">{entries.map(([k,n])=><div key={k}><div style={{width:`${35+n/max*65}%`}}><span>{k}</span><strong>{n}</strong></div></div>)}</div></>}
export const analyticsModules:ModuleRegistry={'metric-grid':MetricGrid,'line-chart':LineChart,'donut-chart':DonutChart,histogram:Histogram,'scatter-plot':ScatterPlot,'activity-heatmap':ActivityHeatmap,leaderboard:Leaderboard,funnel:Funnel};
