import {readingDefinition,validateValues,type ComponentSpec,type DataRecord,type Definition,type Mutation,type Snapshot} from '@livingforma/contracts';
import {createModule} from './ModuleLibrary';
import {dayBefore,dayInTimezone} from '../lib/client';

export function sampleDefinition():Definition{return {...readingDefinition(),entitySchema:{schemaVersion:1,name:'Activities',fields:[
  {id:'title',label:'Name',type:'text',public:true,required:true},
  {id:'description',label:'Notes / answer',type:'text',public:true,required:false},
  {id:'quantity',label:'Actual',type:'number',public:true,required:false,min:0,max:100,defaultValue:0},
  {id:'budget',label:'Target',type:'number',public:true,required:false,min:0,max:100,defaultValue:30},
  {id:'rating',label:'Rating',type:'number',public:true,required:false,min:1,max:5,defaultValue:3},
  {id:'category',label:'Category',type:'enum',public:true,required:false,options:['Learn','Create','Restore'],defaultValue:'Learn'},
  {id:'done',label:'Complete',type:'boolean',public:true,required:false,defaultValue:false},
  {id:'date',label:'Date',type:'date',public:true,required:false},
  {id:'dates',label:'Check-ins',type:'dates',public:true,required:false,defaultValue:[]},
  {id:'url',label:'Website',type:'text',public:true,required:false},
]},appSpec:{specVersion:1,title:'Module playground',description:'Local sample data. Changes here are not saved to a real space.',skin:'linen',layout:'dashboard',components:[],actions:[{id:'add',type:'record.create',label:'Add'},{id:'edit',type:'record.update',label:'Edit'},{id:'remove',type:'record.delete',label:'Delete'},{id:'checkin',type:'record.checkin',label:'Check in',fieldId:'dates'}]}}}
export function sampleRecords():DataRecord[]{const day=dayInTimezone('America/Vancouver'),names=['Read one chapter','Sketch a new idea','Take a quiet walk','Practice a language','Write a reflection','Make something useful'];return names.map((name,i)=>({id:`sample-${i}`,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),values:{title:name,description:['A small step, repeated with care.','## Begin with curiosity\n- Notice a detail\n- Try a different angle','Leave a little room to breathe.','Practice makes patterns feel familiar.','What felt meaningful today?','Bring an idea into the world.'][i],quantity:[24,42,18,65,31,54][i],budget:[30,40,25,70,40,60][i],rating:[4,5,3,4,5,4][i],category:['Learn','Create','Restore'][i%3],done:i%2===0,date:dayBefore(day,3-i),dates:[0,1,2,4,6].filter(n=>(i+n)%3!==0).map(n=>dayBefore(day,n)),url:'https://example.com/'}}))}
export function sampleModule(type:ComponentSpec['type'],definition=sampleDefinition()):ComponentSpec{const c=createModule(type,definition);c.id=`demo_${type.replaceAll('-','_')}`;c.size={columns:6};if(type==='rating-input')c.valueField='rating';if(['calendar-grid','streak','habit-matrix','activity-heatmap'].includes(type))c.dateField='dates';if(type==='text-editor')c.fields=['description','title'];if(['text-reader','markdown-viewer','word-counter'].includes(type))c.fields=['title','description'];if(['quiz','flashcards'].includes(type))c.fields=['title','description'];if(type==='link-directory')c.fields=['title','url'];if(type==='goal-meter')c.config={target:300};if(type==='priority-matrix')c.config={target:40};return c}
export function sampleSnapshot(types:ComponentSpec['type'][]):Snapshot{const definition=sampleDefinition();definition.appSpec.components=types.map(t=>sampleModule(t,definition));return {space:{id:'module-showcase',slug:'module-showcase',title:'Module playground',timezone:'America/Vancouver',visibility:'public',participation:'authenticated'},phase:'ready',definition,records:sampleRecords(),stateVersion:1,eventCursor:1,role:'owner',permissions:{canEdit:true,canWrite:true,canUseTools:false,actionIds:['add','edit','remove','checkin']},loginRequiredForWrite:false}}
export function sampleMutation(s:Snapshot,input:Omit<Mutation,'requestId'|'definitionVersion'>):Snapshot{const next=structuredClone(s),a=next.definition!.appSpec.actions.find(a=>a.id===input.actionId);if(!a)throw new Error('Action is not available in this sample.');if(a.type==='record.create'){next.records.push({id:`sample-${crypto.randomUUID()}`,values:validateValues(next.definition!.entitySchema,input.values),version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}else{const r=next.records.find(r=>r.id===input.recordId);if(!r||r.version!==input.recordVersion)throw new Error('This sample record changed. Reopen it to continue.');if(a.type==='record.delete')next.records=next.records.filter(x=>x.id!==r.id);else if(a.type==='record.checkin'){const day=dayInTimezone(next.space.timezone),old=r.values.dates as string[];r.values.dates=old.includes(day)?old.filter(d=>d!==day):[...old,day];r.version++}else{r.values={...r.values,...validateValues(next.definition!.entitySchema,input.values,true)};r.version++}}next.stateVersion++;return next}
