import {useEffect,useState} from 'react';
import type {DataRecord,FieldValue} from '@livingforma/contracts';
import {useDraft} from '../lib/client';
import {FieldInputs} from '../components/Fields';
import {EmptyModule,field,fields,groupField,Hint,number,records,RecordSelect,text,title,useRecord,useWrite,valueField,type ModuleProps,type ModuleRegistry} from './shared';

function ErrorLine({error}:{error:string}){return error?<p role="alert" className="form-error">{error}</p>:null}
function Checklist(p:ModuleProps){const f=field(p,'boolean'),w=useWrite(p),rs=records(p);if(!f)return <EmptyModule message="Bind a completion checkbox field to this checklist."/>;if(!rs.length)return <EmptyModule/>;return <><div className="module-stack">{rs.map(r=><label className="checklist-row" key={r.id}><input type="checkbox" checked={!!r.values[f.id]} disabled={w.busy} onChange={e=>void w.write(r,{[f.id]:e.target.checked})}/><span>{title(p,r)}</span><small>{r.values[f.id]?'Done':'To do'}</small></label>)}</div><ErrorLine error={w.error}/></>}
function RatingInput(p:ModuleProps){const {record,id,setId}=useRecord(p),f=valueField(p),w=useWrite(p);if(!record||!f)return <EmptyModule message="Choose a numeric rating field and add a record."/>;const max=Math.min(10,Math.max(1,Math.floor(f.max??5))),min=f.min??0;return <div className="module-stack"><RecordSelect p={p} id={id} onChange={setId}/><Hint>{f.label} · {number(record.values[f.id])} / {max}</Hint><div className="module-stars" role="group" aria-label={f.label}>{Array.from({length:max},(_,i)=>i+1).map(n=><button key={n} className="module-button" disabled={w.busy||n<min} aria-pressed={number(record.values[f.id])===n} aria-label={`Rate ${n}`} onClick={()=>void w.write(record,{[f.id]:n})}>{number(record.values[f.id])>=n?'★':'☆'}</button>)}</div><ErrorLine error={w.error}/></div>}
function NumberStepper(p:ModuleProps){const {record,id,setId}=useRecord(p),f=valueField(p),w=useWrite(p);if(!record||!f)return <EmptyModule message="Bind a numeric field to adjust quantities."/>;const value=number(record.values[f.id]),step=p.spec.config?.step??1;return <div className="module-stack"><RecordSelect p={p} id={id} onChange={setId}/><div className="stepper-row"><button className="module-button" aria-label={`Decrease ${f.label}`} disabled={w.busy||value-step<(f.min??-Infinity)} onClick={()=>void w.write(record,{[f.id]:Number((value-step).toFixed(6))})}>−</button><output aria-label={f.label}>{value}</output><button className="module-button" aria-label={`Increase ${f.label}`} disabled={w.busy||value+step>(f.max??Infinity)} onClick={()=>void w.write(record,{[f.id]:Number((value+step).toFixed(6))})}>＋</button></div><Hint>{f.label} · step {step}</Hint><ErrorLine error={w.error}/></div>}
// Keep each record's value and editing version together when selection or server data changes.
function useRecordDraft(p:ModuleProps,record:DataRecord,fieldId:string,initial:string){
  const [draft,setDraft]=useDraft(`${p.snapshot.space.id}:${p.spec.id}:${record.id}:${fieldId}`,{value:initial,version:record.version,dirty:false});
  const dirty=draft.dirty===true,version=typeof draft.version==='number'?draft.version:record.version;
  useEffect(()=>{if(!dirty)setDraft({value:initial,version:record.version,dirty:false})},[initial,record.version,dirty]);
  return {value:String(draft.value??initial),dirty,version,conflict:dirty&&version!==record.version,
    change:(value:string)=>setDraft({value,version:dirty?version:record.version,dirty:true}),
    reset:()=>setDraft({value:initial,version:record.version,dirty:false}),
    saved:()=>setDraft(d=>({...d,dirty:false}))};
}
function DraftConflict({conflict,onReload,disabled}:{conflict:boolean;onReload:()=>void;disabled:boolean}){return conflict?<div className="module-stack"><p role="alert" className="form-error">This record changed elsewhere. Your draft is preserved. Copy it before loading the latest value.</p><button type="button" className="module-button" disabled={disabled} onClick={onReload}>Load latest value</button></div>:null}
function RangeEditor({p,record,onBusy}:{p:ModuleProps;record:DataRecord;onBusy:(busy:boolean)=>void}){const f=valueField(p)!,w=useWrite(p),draft=useRecordDraft(p,record,f.id,String(number(record.values[f.id])));useEffect(()=>onBusy(w.busy),[w.busy,onBusy]);const min=f.min??0,max=f.max??100,step=p.spec.config?.step??1;return <form className="module-stack" onSubmit={async e=>{e.preventDefault();if(!draft.dirty||draft.conflict||w.busy)return;if(await w.write({...record,version:draft.version},{[f.id]:Number(draft.value)}))draft.saved()}}><label className="module-field">{f.label}<input type="range" min={min} max={max} step={step} disabled={w.busy} value={draft.value} onChange={e=>draft.change(e.target.value)}/></label><label className="module-field">Value<input required type="number" min={min} max={max} step={step} disabled={w.busy} value={draft.value} onChange={e=>draft.change(e.target.value)}/></label><button className="module-button" disabled={w.busy||!draft.dirty||draft.conflict}>Save value</button><DraftConflict conflict={draft.conflict} onReload={draft.reset} disabled={w.busy}/><ErrorLine error={w.error}/></form>}
function RangeInput(p:ModuleProps){const {record,id,setId}=useRecord(p),[busy,setBusy]=useState(false);if(!record||!valueField(p))return <EmptyModule message="Bind a numeric field with a useful range."/>;return <div className="module-stack"><RecordSelect p={p} id={id} onChange={setId} disabled={busy}/><RangeEditor onBusy={setBusy} key={`${id}:${valueField(p)!.id}`} p={p} record={record}/></div>}
function SegmentedInput(p:ModuleProps){const {record,id,setId}=useRecord(p),f=groupField(p),w=useWrite(p);if(!record||!f)return <EmptyModule message="Bind a category field to choose a status."/>;return <div className="module-stack"><RecordSelect p={p} id={id} onChange={setId}/><div className="module-segments" role="group" aria-label={f.label}>{f.options?.map(o=><button key={o} className="module-button" aria-pressed={record.values[f.id]===o} disabled={w.busy} onClick={()=>void w.write(record,{[f.id]:o})}>{o}</button>)}</div><ErrorLine error={w.error}/></div>}
function TogglePanel(p:ModuleProps){const {record,id,setId}=useRecord(p),fs=fields(p).filter(f=>f.type==='boolean'),w=useWrite(p);if(!record||!fs.length)return <EmptyModule message="Bind one or more checkbox fields for this settings panel."/>;return <div className="module-stack"><RecordSelect p={p} id={id} onChange={setId}/>{fs.map(f=><label className="checklist-row" key={f.id}><span>{f.label}</span><input role="switch" type="checkbox" checked={!!record.values[f.id]} disabled={w.busy} onChange={e=>void w.write(record,{[f.id]:e.target.checked})}/></label>)}<ErrorLine error={w.error}/></div>}
function QuickAdd(p:ModuleProps){const w=useWrite(p),[draft,setDraft]=useState<Record<string,unknown>>({});const all=p.snapshot.definition?.entitySchema.fields??[],primary=field(p,'text'),needed=all.filter(f=>f.id===primary?.id||(f.required&&f.defaultValue===undefined));if(!primary)return <EmptyModule message="Add a text field to collect ideas quickly."/>;return <form className="module-stack" onSubmit={async e=>{e.preventDefault();const vals:Record<string,FieldValue>={};for(const f of needed)if(draft[f.id]!==undefined)vals[f.id]=draft[f.id] as FieldValue;if(await w.write(undefined,vals,'record.create'))setDraft({})}}><FieldInputs fields={needed} values={draft} onChange={(id,v)=>setDraft(d=>({...d,[id]:v}))} prefix={p.spec.id}/><button className="module-button" disabled={w.busy}>Add record</button><ErrorLine error={w.error}/></form>}
function TextDraft({p,record,onBusy}:{p:ModuleProps;record:DataRecord;onBusy:(busy:boolean)=>void}){const f=field(p,'text')!,w=useWrite(p),draft=useRecordDraft(p,record,f.id,String(record.values[f.id]??''));useEffect(()=>onBusy(w.busy),[w.busy,onBusy]);return <form className="module-stack" onSubmit={async e=>{e.preventDefault();if(!draft.dirty||draft.conflict||w.busy)return;if(await w.write({...record,version:draft.version},{[f.id]:draft.value}))draft.saved()}}><label className="module-field">{f.label}<textarea required={f.required} rows={7} maxLength={10000} disabled={w.busy} value={draft.value} onChange={e=>draft.change(e.target.value)}/></label><div className="module-row"><Hint>{draft.value.length} characters {draft.dirty?'· unsaved':''}</Hint><button className="module-button" disabled={w.busy||!draft.dirty||draft.conflict}>Save text</button></div><DraftConflict conflict={draft.conflict} onReload={draft.reset} disabled={w.busy}/><ErrorLine error={w.error}/></form>}
function TextEditor(p:ModuleProps){const {record,id,setId}=useRecord(p),[busy,setBusy]=useState(false);if(!record||!field(p,'text'))return <EmptyModule message="Bind a text field and choose a record to edit."/>;return <div className="module-stack"><RecordSelect p={p} id={id} onChange={setId} disabled={busy}/><TextDraft onBusy={setBusy} key={`${id}:${field(p,'text')!.id}`} p={p} record={record}/></div>}
export const inputModules:ModuleRegistry={checklist:Checklist,'rating-input':RatingInput,'number-stepper':NumberStepper,'range-input':RangeInput,'segmented-input':SegmentedInput,'toggle-panel':TogglePanel,'quick-add':QuickAdd,'text-editor':TextEditor};
