import {useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {motion,useReducedMotion} from 'motion/react';
import {COMPONENT_MANIFESTS,type ComponentSpec,type EntityField} from '@livingforma/contracts';

export function moduleColumns(spec:ComponentSpec){return spec.size?.columns??(spec.span==='side'?4:spec.span==='main'?8:12)}
export function ModuleFrame({spec,children,editing=false,disabled=false,fields=[],onChange,onMove,onRemove}:{spec:ComponentSpec;children:ReactNode;editing?:boolean;disabled?:boolean;fields?:EntityField[];onChange?:(spec:ComponentSpec)=>void;onMove?:(direction:number)=>void;onRemove?:()=>void}){
  const ref=useRef<HTMLElement>(null),drag=useRef<{x:number;y:number;columns:number;height:number;unit:number}|null>(null),reduced=useReducedMotion(),[expanded,setExpanded]=useState(false);
  const m=COMPONENT_MANIFESTS.find(m=>m.id===spec.type)!;
  const update=(patch:Partial<ComponentSpec>)=>{if(!disabled)onChange?.({...spec,...patch})};
  const config=(key:string,value:unknown)=>update({config:{...spec.config,[key]:value}});
  return <motion.section ref={ref} layout={reduced?false:'position'} transition={{duration:.2}} className={`runtime-component module-frame component-${spec.type} variant-${spec.variant} density-${spec.config?.density??'comfortable'} ${editing?'is-editing':''}`} data-component-id={spec.id} data-module-type={spec.type} style={{'--module-cols':moduleColumns(spec),'--module-height':`${spec.size?.minHeight??0}px`} as CSSProperties}>
    {(spec.config?.showHeader!==false||editing)&&<div className="module-heading"><div><small>{m.category??'Essentials'}</small><h2>{spec.title||spec.type.replaceAll('-',' ')}</h2></div>{editing&&<button className="module-button configure-button" disabled={disabled} aria-expanded={expanded} aria-label={`Configure ${spec.title||spec.type}`} onClick={()=>setExpanded(v=>!v)}>Configure</button>}</div>}
    {editing&&expanded&&<fieldset className="module-settings" disabled={disabled}>
      <label className="module-field">Title<input maxLength={120} value={spec.title??''} onChange={e=>update({title:e.target.value})}/></label>
      <div className="settings-grid"><label className="module-field">Desktop width<select aria-label="Module width" value={moduleColumns(spec)} onChange={e=>update({size:{...spec.size,columns:Number(e.target.value)}})}>{[3,4,6,8,9,12].map(n=><option key={n} value={n}>{n===12?'Full':`${n} / 12 columns`}</option>)}{![3,4,6,8,9,12].includes(moduleColumns(spec))&&<option value={moduleColumns(spec)}>{moduleColumns(spec)} / 12 columns</option>}</select></label><label className="module-field">Desktop minimum height<select aria-label="Module minimum height" value={spec.size?.minHeight??0} onChange={e=>{const h=Number(e.target.value);update({size:{columns:moduleColumns(spec),...(h?{minHeight:h}:{})}})}}><option value={0}>Fit content</option>{[160,240,320,480,640,960].map(n=><option key={n} value={n}>{n}px</option>)}{spec.size?.minHeight&&![160,240,320,480,640,960].includes(spec.size.minHeight)&&<option value={spec.size.minHeight}>{spec.size.minHeight}px</option>}</select></label></div>
      <div className="settings-grid"><label className="module-field">Density<select aria-label="Module density" value={spec.config?.density??'comfortable'} onChange={e=>config('density',e.target.value)}>{['compact','comfortable','spacious'].map(v=><option key={v}>{v}</option>)}</select></label><label className="module-field">Appearance<select aria-label="Module appearance" value={spec.variant} onChange={e=>update({variant:e.target.value as ComponentSpec['variant']})}>{m.variants.map(v=><option key={v}>{v}</option>)}</select></label></div>
      <label className="module-check"><input type="checkbox" checked={spec.config?.showHeader!==false} onChange={e=>config('showHeader',e.target.checked)}/>Show heading</label>
      {(['valueField','dateField','groupBy'] as const).filter(key=>m.bindings.includes(key)).map(key=><label className="module-field" key={key}>{key==='valueField'?'Numeric value':key==='dateField'?'Date / history':'Category'}<select value={spec[key]??''} onChange={e=>{const next={...spec};if(e.target.value)next[key]=e.target.value;else delete next[key];onChange?.(next)}}><option value="">Automatic</option>{fields.filter(f=>key==='valueField'?f.type==='number':key==='dateField'?['date','dates'].includes(f.type):f.type==='enum').map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label>)}
      {m.bindings.includes('fields')&&<fieldset><legend>Fields · selection order</legend><div className="settings-fields">{fields.map(f=><label className="module-check" key={f.id}><input type="checkbox" checked={spec.fields.includes(f.id)} onChange={e=>update({fields:e.target.checked?[...spec.fields,f.id]:spec.fields.filter(id=>id!==f.id)})}/>{f.label}{spec.fields.includes(f.id)&&<small>{spec.fields.indexOf(f.id)+1}</small>}</label>)}</div></fieldset>}
      {(m.configKeys??[]).filter(k=>!['showHeader','density'].includes(k)).map(k=>{const val=spec.config?.[k as keyof NonNullable<ComponentSpec['config']>];return <label className="module-field" key={k}>{k.replace(/([A-Z])/g,' $1')}<input type={['prefix','suffix','text'].includes(k)?'text':'number'} value={String(val??'')} step={['target','step','scale'].includes(k)?'any':1} maxLength={k==='text'?5000:16} onChange={e=>{const next={...spec.config};if(!e.target.value)delete next[k as keyof typeof next];else Object.assign(next,{[k]:['prefix','suffix','text'].includes(k)?e.target.value:Number(e.target.value)});update({config:next})}}/></label>})}
      <div className="module-row"><button className="module-button" onClick={()=>onMove?.(-1)}>Move earlier</button><button className="module-button" onClick={()=>onMove?.(1)}>Move later</button><button className="module-button danger" onClick={onRemove}>Remove module</button></div><p className="module-hint">Phones use full width and fit their content. Content stays visible at every height. Save layout to share these changes.</p>
    </fieldset>}
    <div className="module-content">{children}</div>
    {editing&&<button className="module-resize" disabled={disabled} aria-label={`Resize ${spec.title||spec.type}; use Configure for keyboard controls`} onPointerDown={e=>{if(disabled||!ref.current||e.pointerType==='touch')return;e.currentTarget.setPointerCapture(e.pointerId);const rect=ref.current.getBoundingClientRect(),grid=ref.current.parentElement!.getBoundingClientRect();drag.current={x:e.clientX,y:e.clientY,columns:moduleColumns(spec),height:rect.height,unit:grid.width/12};}} onPointerMove={e=>{const d=drag.current;if(!d||!ref.current)return;const cols=Math.max(3,Math.min(12,Math.round(d.columns+(e.clientX-d.x)/d.unit)));ref.current.style.setProperty('--module-cols',String(cols));ref.current.style.setProperty('--module-height',`${Math.max(120,Math.min(960,Math.round(d.height+e.clientY-d.y)))}px`);}} onPointerUp={e=>{const d=drag.current;if(!d)return;drag.current=null;update({size:{columns:Math.max(3,Math.min(12,Math.round(d.columns+(e.clientX-d.x)/d.unit))),minHeight:Math.max(120,Math.min(960,Math.round(d.height+e.clientY-d.y)))}});}} onPointerCancel={()=>{drag.current=null;ref.current?.style.setProperty('--module-cols',String(moduleColumns(spec)));ref.current?.style.setProperty('--module-height',`${spec.size?.minHeight??0}px`);}} onClick={()=>setExpanded(true)}>↘</button>}
  </motion.section>
}
