import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {COMPONENT_MANIFESTS,type ComponentSpec,type Snapshot} from '@livingforma/contracts';
import {Renderer} from '../components/Renderer';
import {sampleMutation,sampleSnapshot} from './fixtures';

export function Showcase(){const params=new URLSearchParams(location.search),initial=params.get('type')??'';
  const [reset,setReset]=useState(0);
  const [query,setQuery]=useState(initial),[category,setCategory]=useState('All'),[page,setPage]=useState(0),[width,setWidth]=useState('Desktop'),[skin,setSkin]=useState('linen'),[snapshot,setSnapshot]=useState<Snapshot>(()=>sampleSnapshot([]));const current=useRef(snapshot);current.current=snapshot;
  const filtered=useMemo(()=>COMPONENT_MANIFESTS.filter(m=>m.id!=='generated-site'&&(category==='All'||(m.category??'Essentials')===category)&&(m.id===query||`${m.id} ${m.description}`.toLowerCase().includes(query.toLowerCase()))),[query,category]);const exact=COMPONENT_MANIFESTS.find(m=>m.id!=='generated-site'&&m.id===query);const visible=exact?[exact]:filtered.slice(page*12,page*12+12);const key=visible.map(m=>m.id).join(',');
  useEffect(()=>{const next=sampleSnapshot(visible.map(m=>m.id));const cols=Number(params.get('columns'));if(Number.isInteger(cols)&&cols>=3&&cols<=12)next.definition!.appSpec.components.forEach(c=>c.size={columns:cols});setSnapshot(next)},[key]);
  useEffect(()=>{document.documentElement.dataset.skin=skin;document.title='60 adaptable modules — LivingForma'},[skin]);
  return <div className="showcase-shell"><header className="showcase-header"><a href="/">LivingForma<span className="wordmark-dot">.</span></a><span className="showcase-badge">INTERACTIVE MODULE LIBRARY · 60 MODULES</span></header><div className="showcase-intro"><small>A vocabulary for your ideas</small><h1>Small pieces.<br/>Endless possibilities.</h1><p>Shape a study space, a calmer dashboard, or an idea that is entirely yours. Explore each module, try its controls, and adjust its proportions.</p><span className="showcase-badge">Sample data · changes stay in this playground</span></div><div className="showcase-controls"><label className="module-field">Find a module<input type="search" value={query} placeholder="Search all 60 modules…" onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><label className="module-field">Category<select value={category} onChange={e=>{setCategory(e.target.value);setQuery('');setPage(0)}}>{['All',...new Set(COMPONENT_MANIFESTS.filter(m=>m.id!=='generated-site').map(m=>m.category??'Essentials'))].map(c=><option key={c}>{c}</option>)}</select></label><label className="module-field">Preview width<select value={width} onChange={e=>setWidth(e.target.value)}>{['Desktop','Tablet','Phone'].map(c=><option key={c}>{c}</option>)}</select></label><label className="module-field">Palette<select value={skin} onChange={e=>setSkin(e.target.value)}>{['linen','sage','ink','clay','sand','rose'].map(c=><option key={c}>{c}</option>)}</select></label><button className="module-button" onClick={()=>{for(const storageKey of Object.keys(sessionStorage))if(storageKey.startsWith('lf-draft:module-showcase:'))sessionStorage.removeItem(storageKey);setSnapshot(sampleSnapshot(visible.map(m=>m.id)));setReset(n=>n+1)}}>Reset sample</button></div>
    <div className="module-row"><p className="module-hint">{exact?1:filtered.length} matching modules · mobile and desktop ready</p>{!exact&&filtered.length>12&&<div className="module-row"><button className="module-button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="module-hint">{page+1} / {Math.ceil(filtered.length/12)}</span><button className="module-button" disabled={(page+1)*12>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</div>
    <div className={`showcase-preview ${width==='Phone'?'preview-phone':''}`} style={{width:width==='Phone'?390:width==='Tablet'?768:'100%'} as CSSProperties}>{snapshot.definition?.appSpec.components.length?<Renderer key={`${key}:${reset}`} snapshot={snapshot} csrf={null} onLogin={()=>{}} mutate={async input=>{const next=sampleMutation(current.current,input);current.current=next;setSnapshot(next);return next}} onPresentation={async(components:ComponentSpec[],base,layout)=>{const next=structuredClone(current.current);if(next.definition!.definitionVersion!==base)throw new Error('This sample has changed. Reopen the editor.');next.definition!.appSpec.components=components;next.definition!.definitionVersion++;if(layout)next.definition!.appSpec.layout=layout;current.current=next;setSnapshot(next);return next}}/>:<p>No modules match your search.</p>}</div><p className="showcase-footer">Playground controls use local sample records. Camera, voice and external tools require an authorized real space. Layout changes in a real space are saved and shared with its viewers.</p></div>
}
