/** Independent LF-146 regression: real local HTTP, PGlite, local-rules planner and Chrome.
 * No cloud credentials/providers are read. Adversarial database states are explicitly fixtures.
 * Run: pnpm exec tsx tests/e2e/foundation.ts
 */
import {chromium, expect, type BrowserContext} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {buildApp} from '../../apps/api/src/app';
import {createDatabase, type SpaceState} from '../../packages/db/src/index';
import {readingDefinition, validateDefinition, type Snapshot} from '../../packages/contracts/src/index';
import {planProposal} from '../../packages/agent/src/planner';
import {toolAdapter} from '../../packages/agent/src/tools';

process.env.ENABLE_LOCAL_DEMO='true';process.env.NODE_ENV='test';
const origin='http://localhost:4317';
const context=await buildApp({db:await createDatabase(),origin,localDemo:true,planner:planProposal,plannerMode:'local',tools:toolAdapter,staticDir:resolve('apps/web/dist')});
await context.app.listen({host:'127.0.0.1',port:4317});
const browser=await chromium.launch({headless:true,channel:'chrome'});
const owner=await browser.newContext({viewport:{width:1440,height:1000}}),anon=await browser.newContext({viewport:{width:1440,height:1000}}),participant=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
const page=await owner.newPage(),viewer=await anon.newPage(),member=await participant.newPage();
for(const p of [page,viewer,member])p.setDefaultTimeout(12000);
const pageErrors:string[]=[];for(const p of [page,viewer,member])p.on('pageerror',e=>pageErrors.push(e.message));
const checks:{name:string;status:'pass'|'fail';detail?:string}[]=[];
async function check(name:string,fn:()=>Promise<void>){try{await fn();checks.push({name,status:'pass'});console.log('PASS',name)}catch(e){checks.push({name,status:'fail',detail:(e as Error).message});console.log('FAIL',name,(e as Error).message)}}
async function session(client:BrowserContext){return (await client.request.get(`${origin}/api/session`)).json()}
async function post(client:BrowserContext,path:string,data:unknown,headers:Record<string,string>={}){const s=await session(client);return client.request.post(`${origin}${path}`,{data,headers:{origin,'x-csrf-token':s.csrfToken??'',...headers}})}
async function snap(client:BrowserContext,slug:string){return (await client.request.get(`${origin}/api/spaces/${slug}/snapshot`)).json() as Promise<Snapshot>}
try{
 await check('Anonymous English reading UI hides Owner orb and prevents write',async()=>{await page.goto(`${origin}/s/reading`);await expect(page.getByRole('heading',{name:'Between the lines.',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Open the space designer'})).toHaveCount(0);expect(/[\p{Script=Han}]/u.test(await page.locator('body').innerText())).toBe(false);const res=await post(anon,'/api/spaces/reading/actions',{requestId:randomUUID(),definitionVersion:1,actionId:'add',values:{title:'Unauthorized'}});expect(res.status()).toBe(401);});
 await check('Explicit local test login exposes Owner orb and preserves typed draft',async()=>{await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText(/test identity/i)).toBeVisible();await page.getByRole('button',{name:'Enter local test space'}).click();await page.getByRole('button',{name:'Open the space designer'}).click();const field=page.getByRole('textbox',{name:'Describe how to change your space'});await expect(field).toBeFocused();await field.fill('Show books as a list, add rating and sort by rating with rose skin');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Open the space designer'}).click();await expect(field).toHaveValue('Show books as a list, add rating and sort by rating with rose skin');await page.keyboard.press('Escape');});
 const title='QA independent retained book';
 await viewer.goto(`${origin}/s/reading`);await expect(viewer.getByRole('heading',{level:1})).toBeVisible();
 await check('Create through actual form persists on reload and reaches second anonymous client by SSE',async()=>{const form=page.locator('[data-component-id="add-book"]');await form.getByLabel(/^Title/).fill(title);await form.getByLabel('Author',{exact:true}).fill('QA regression');await form.locator('button[type=submit]').click();await expect(viewer.getByRole('button',{name:`View ${title}`,exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:`View ${title}`,exact:true})).toBeVisible();});
 await check('Local participant has CRUD permission but server rejects definition/tool writes',async()=>{const login=await participant.request.post(`${origin}/auth/local`,{data:{persona:'participant'},headers:{origin}});expect(login.status()).toBe(200);await member.goto(`${origin}/s/reading`);await expect(member.getByRole('heading',{level:1})).toBeVisible();await expect(member.getByRole('button',{name:'Open the space designer'})).toHaveCount(0);expect((await snap(participant,'reading')).role).toBe('participant');expect((await post(participant,'/api/spaces/reading/proposals',{prompt:'Add rating',baseDefinitionVersion:1,requestId:randomUUID()})).status()).toBe(403);expect((await post(participant,'/api/spaces/reading/tool-proposals',{prompt:'Search books'})).status()).toBe(403);expect((await post(participant,'/api/spaces/reading/tools',{spec:{},enable:true})).status()).toBe(403);const action=await post(participant,'/api/spaces/reading/actions',{actionId:'add',definitionVersion:1,requestId:randomUUID(),values:{title:'Participant contribution'}});expect(action.status()).toBe(200);await expect(page.getByRole('button',{name:'View Participant contribution',exact:true})).toBeVisible();});
 await check('Cross-origin and incorrect CSRF writes fail without modifying records',async()=>{const before=await snap(owner,'reading');const payload={actionId:'add',definitionVersion:1,requestId:randomUUID(),values:{title:'Forbidden'}};expect((await post(owner,'/api/spaces/reading/actions',payload,{origin:'https://attacker.invalid'})).status()).toBe(403);expect((await post(owner,'/api/spaces/reading/actions',payload,{'x-csrf-token':'wrong'})).status()).toBe(403);expect((await snap(owner,'reading')).records).toEqual(before.records);});
 await check('Actual local-rules morph retains record IDs, values, URL and unsaved form while SSE viewers update',async()=>{const before=await snap(owner,'reading');const unsaved=page.locator('[data-component-id="add-book"]').getByLabel(/^Title/);await unsaved.fill('Unsaved text survives real morph');await page.getByRole('button',{name:'Open the space designer'}).click();await page.getByRole('textbox',{name:'Describe how to change your space'}).fill('Show books as a list, add rating and sort by rating with rose skin');await page.getByRole('button',{name:'Apply changes'}).click();await expect(page.locator('.record-list')).toBeVisible();await expect(viewer.locator('.record-list')).toBeVisible();await expect(member.locator('.record-list')).toBeVisible();await expect(unsaved).toHaveValue('Unsaved text survives real morph');const after=await snap(owner,'reading');expect(after.records.map(r=>r.id)).toEqual(before.records.map(r=>r.id));for(const record of before.records)expect(after.records.find(r=>r.id===record.id)?.values).toMatchObject(record.values);expect(after.definition?.entitySchema.fields.some(f=>f.id==='rating')).toBe(true);expect(after.definition?.appSpec.skin).toBe('rose');expect(page.url()).toBe(`${origin}/s/reading`);await page.screenshot({path:'docs/qa/reading-real-local-morph.png',fullPage:true});});
 const mobileDimensions:unknown[]=[];
 for(const width of [320,390,430])await check(`Reduced-motion rating layout fits a ${width}px viewport`,async()=>{await member.setViewportSize({width,height:844});expect(await member.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches)).toBe(true);await expect(member.getByRole('group',{name:'Rating',exact:true})).toBeVisible();await member.screenshot({path:`docs/qa/mobile-rating-${width}.png`,fullPage:true});const dimensions=await member.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,rating:[...document.querySelectorAll<HTMLInputElement>('.rating-input .sr-only')].map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,padding:getComputedStyle(e).padding,left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right})),overflow:[...document.querySelectorAll('*')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right,text:e.textContent?.slice(0,80)})).slice(0,12)}));mobileDimensions.push(dimensions);await writeFile('docs/qa/mobile-dimensions.json',JSON.stringify(mobileDimensions,null,2));expect(dimensions.scroll,JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.width);for(const hidden of dimensions.rating){expect(hidden.width).toBe(1);expect(hidden.height).toBe(1);expect(hidden.padding).toBe('0px');}});
 await check('Update/delete actions persist and propagate to a second client',async()=>{const record=(await snap(owner,'reading')).records.find(r=>r.values.title===title)!;const target=page.locator(`[data-record-id="${record.id}"] .record-info`);await target.click();await page.getByLabel('Progress',{exact:true}).fill('81');await page.getByRole('button',{name:'Save changes'}).click();await page.reload();await target.click();await expect(page.getByLabel('Progress',{exact:true})).toHaveValue('81');await page.getByRole('button',{name:'Delete record',exact:true}).click();await page.getByRole('button',{name:'Yes, delete'}).click();await expect(viewer.locator(`[data-record-id="${record.id}"]`)).toHaveCount(0);});
 await check('Unsupported capability retains last definition, records and URL',async()=>{const before=await snap(owner,'reading');const response=await post(owner,'/api/spaces/reading/proposals',{prompt:'Send an email',baseDefinitionVersion:before.definition!.definitionVersion,requestId:randomUUID()});expect(response.status()).toBe(422);expect((await response.json()).error.code).toBe('CAPABILITY_UNAVAILABLE');expect(await snap(owner,'reading')).toEqual(before);expect(page.url()).toBe(`${origin}/s/reading`);});
 await check('Offline viewer preserves prior view and resumes actual snapshot/SSE after reconnect',async()=>{await anon.setOffline(true);await expect(viewer.getByText('Offline · your last view is safe')).toBeVisible();await expect(viewer.getByRole('heading',{level:1})).toBeVisible();await anon.setOffline(false);await expect(viewer.getByText('Live and in sync')).toBeVisible({timeout:15000});});
 await check('Habit check-in changes real dates, preserves route and restores original state',async()=>{await page.goto(`${origin}/s/habits`);await expect(page.getByRole('group',{name:/completion calendar/})).toBeVisible();const before=await snap(owner,'habits'),button=page.locator('.checkin-button').first(),pressed=await button.getAttribute('aria-pressed');await button.click();await expect(button).toHaveAttribute('aria-pressed',pressed==='true'?'false':'true');await page.reload();await expect(button).toHaveAttribute('aria-pressed',pressed==='true'?'false':'true');await button.click();await expect(button).toHaveAttribute('aria-pressed',pressed!);expect((await snap(owner,'habits')).records.map(r=>r.values)).toEqual(before.records.map(r=>r.values));expect(page.url()).toBe(`${origin}/s/habits`);});
 await check('Participant creates a new habit space through UI and becomes its Owner',async()=>{await member.getByRole('button',{name:'Create a new space'}).click();await member.getByRole('button',{name:'A daily practice',exact:true}).click();await member.getByRole('button',{name:'Create my space'}).click();await expect(member.getByRole('button',{name:'Open the space designer'})).toBeVisible();await expect(member.getByRole('group',{name:/completion calendar/})).toBeVisible();const slug=member.url().split('/s/')[1]!;expect(slug).not.toBe('habits');const created=await snap(participant,slug);expect(created.role).toBe('owner');expect(created.definition?.entitySchema.fields.some(f=>f.type==='dates')).toBe(true);expect(created.records).toEqual([]);});
 await check('External-tool prompt on new space is safely rejected with explicit approval guidance and no partial space',async()=>{const before=(await (await participant.request.get(`${origin}/api/spaces`)).json()).spaces;const response=await post(participant,'/api/spaces',{title:'Pending book search',prompt:'Create a book search with Open Library'});expect(response.status()).toBe(422);expect((await response.json()).error.code).toBe('TOOL_APPROVAL_REQUIRED');expect((await (await participant.request.get(`${origin}/api/spaces`)).json()).spaces).toEqual(before);});
 await check('Logout removes orb; prior cookie and CSRF cannot mutate',async()=>{const oldSession=await session(owner),cookies=await owner.cookies();await page.getByRole('button',{name:'Sign out'}).click();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Open the space designer'})).toHaveCount(0);const response=await context.app.inject({method:'POST',url:'/api/spaces/habits/actions',headers:{origin,cookie:cookies.map(c=>`${c.name}=${c.value}`).join('; '),'x-csrf-token':oldSession.csrfToken},payload:{requestId:randomUUID(),definitionVersion:1,actionId:'add',values:{title:'Old cookie'}}});expect(response.statusCode).toBe(401);});
 await check('Public projection of all-private field definition remains renderable without private values',async()=>{const definition=readingDefinition();for(const field of definition.entitySchema.fields)field.public=false;validateDefinition(definition);const now=new Date().toISOString();const state:SpaceState={space:{id:'qa-private-projection',slug:'qa-private-projection',title:'Private data public shell',timezone:'America/Vancouver',visibility:'public',participation:'authenticated'},ownerId:'user-local-owner',members:[],definition,records:[{id:'private-record',values:{title:'PRIVATE_SENTINEL',author:'SECRET_AUTHOR',status:'Reading',progress:30},version:1,createdAt:now,updatedAt:now}],stateVersion:1,eventCursor:0};await context.store.insertSpace(state);const publicView=await snap(anon,state.space.slug);expect(JSON.stringify(publicView)).not.toContain('PRIVATE_SENTINEL');expect(JSON.stringify(publicView)).not.toContain('SECRET_AUTHOR');await viewer.goto(`${origin}/s/${state.space.slug}`);await viewer.getByRole('heading',{level:1}).waitFor();await viewer.screenshot({path:'docs/qa/all-private-public-projection.png',fullPage:true});await writeFile('docs/qa/all-private-projection.json',JSON.stringify({fieldCount:publicView.definition?.entitySchema.fields.length,componentCount:publicView.definition?.appSpec.components.length,body:await viewer.locator('body').innerText()},null,2));expect(publicView.definition).toBeNull();expect(publicView.records).toEqual([]);expect(publicView.permissions.canWrite).toBe(false);await expect(viewer.getByRole('heading',{name:'A little pause.'})).toHaveCount(0);await expect(viewer.getByText('The space owner is preparing something for this space.')).toBeVisible();expect((await snap(participant,state.space.slug)).definition).toBeNull();const login=await owner.request.post(`${origin}/auth/local`,{data:{persona:'owner'},headers:{origin}});expect(login.status()).toBe(200);expect((await snap(owner,state.space.slug)).definition).toEqual(definition);
 const onlyPrivateComponent=structuredClone(state);onlyPrivateComponent.space={...state.space,id:'qa-private-component',slug:'qa-private-component'};onlyPrivateComponent.definition!.entitySchema.fields.find(f=>f.id==='author')!.public=true;onlyPrivateComponent.definition!.appSpec.components=onlyPrivateComponent.definition!.appSpec.components.filter(c=>c.type==='cards').map(c=>({...c,fields:['title']}));validateDefinition(onlyPrivateComponent.definition);await context.store.insertSpace(onlyPrivateComponent);const componentView=await snap(anon,onlyPrivateComponent.space.slug);expect(componentView.definition).toBeNull();expect(componentView.records).toEqual([]);});
 await check('No browser JavaScript errors in above rendered flows',async()=>{expect(pageErrors).toEqual([])});
}finally{
 await writeFile('docs/qa/foundation-results.json',JSON.stringify({date:new Date().toISOString(),scope:'Independent actual local HTTP/Chrome/PGlite/local-rules. No real Google, Gemini, external tool, media, or production claim. All-private projection state is an explicit adversarial fixture.',checks,pageErrors},null,2));await browser.close();await context.app.close();
}
if(checks.some(c=>c.status==='fail'))process.exitCode=1;
