/** Independent ordinary acceptance: offline authored source, real host/Chrome/QuickJS. */
import {chromium,expect,type Page,type FrameLocator} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {buildApp} from '../../apps/api/src/app';
import {createDatabase} from '../../packages/db/src/index';
import {componentSchema,readingDefinition,type GeneratedToolSpec,type GenerationJob,type Proposal,type SiteGenerator,type GenerationOutline} from '../../packages/contracts/src/index';

process.env.NODE_ENV='test';process.env.ENABLE_LOCAL_DEMO='true';
const origin='http://localhost:4349',reportDir='docs/qa/generated-sites';
const checks:{name:string;status:'passed';details?:unknown}[]=[];
const calls:{prompt:string;repair:boolean}[]=[];let outlineRelease:(()=>void)|undefined,sourceRelease:(()=>void)|undefined;
const tool:GeneratedToolSpec={kind:'code-js-v1',toolId:'readingTime',toolVersion:1,name:'Reading time',description:'Estimate remaining reading time from public saved progress.',source:'async function run(input, api) { const rows = await api.readRecords({fields:["progress"],limit:100}); const remaining = rows.reduce((sum,row)=>sum + Math.max(0,100 - Number(row.values.progress || 0)),0); return {remainingMinutes:Math.round(remaining * input.minutesPerPercent),books:rows.length}; }',inputSchema:{type:'object',properties:{minutesPerPercent:{type:'number',minimum:0,maximum:10}},required:['minutesPerPercent'],additionalProperties:false},outputSchema:{type:'object',properties:{remainingMinutes:{type:'number',minimum:0},books:{type:'number',minimum:0}},required:['remainingMinutes','books'],additionalProperties:false},sideEffects:'none',capabilities:{publicRecordFields:['progress'],connectors:[]},tests:[{name:'Empty shelf',input:{minutesPerPercent:2},expected:{remainingMinutes:0,books:0},records:[]},{name:'Different progress',input:{minutesPerPercent:3},expected:{remainingMinutes:375,books:2},records:[{id:'a',version:1,values:{progress:25}},{id:'b',version:1,values:{progress:50}}]}]};
const css='body{margin:0;background:#ede9df;color:#293d39;font:16px system-ui}main{max-width:650px;margin:auto;padding:32px 20px;box-sizing:border-box}h1{font:42px Georgia;line-height:1.08;margin:12px 0}p{line-height:1.5}button,input{font:inherit;max-width:100%;box-sizing:border-box;padding:12px;border:1px solid #83978c;border-radius:12px;background:#faf8f2;margin:6px 0}button{cursor:pointer}label{display:grid;gap:5px}#card{background:#d0ddcf;border-radius:22px;padding:20px;touch-action:none;user-select:none;min-height:220px}img{width:100%;height:150px;object-fit:cover;image-rendering:pixelated;border-radius:14px;background:#9fb9ab}#controls{display:flex;gap:12px}#result{min-height:2.5em}li{padding:9px 0}ul{padding-left:20px}input{min-width:0;width:100%}small{letter-spacing:2px;font-size:10px}';
const startJs='(async()=>{let state=await lf.ready;window.qaState=state;const output=document.getElementById("result");';
const photoJs=startJs+'let index=0,liked=0,startX=null;const card=document.getElementById("card");function draw(next){state=next;window.qaState=next;const record=state.records[index%Math.max(1,state.records.length)];document.getElementById("card-title").textContent=record?.values.title||"No records";document.getElementById("saved").textContent=state.records.length+" saved records";if(record?.values.photo)lf.image(record.values.photo).then(asset=>document.getElementById("photo").src=asset.dataUrl).catch(error=>output.textContent=error.message)}function choose(like){liked+=like?1:0;index++;card.style.transform="none";draw(state);output.textContent=(like?"Liked":"Skipped")+" · "+liked+" favorites"}card.onpointerdown=e=>{startX=e.clientX;card.setPointerCapture(e.pointerId)};card.onpointermove=e=>{if(startX!==null)card.style.transform="translateX("+(e.clientX-startX)+"px)"};card.onpointerup=e=>{if(startX!==null&&Math.abs(e.clientX-startX)>50)choose(e.clientX>startX);else card.style.transform="none";startX=null};document.getElementById("skip").onclick=()=>choose(false);document.getElementById("like").onclick=()=>choose(true);lf.subscribe(draw);draw(state);lf.reportReady();})();';
const searchJs=startJs+'function draw(next){state=next;window.qaState=next;const query=document.getElementById("search").value.toLowerCase();const list=document.getElementById("records");list.replaceChildren();const found=state.records.filter(record=>String(record.values.title).toLowerCase().includes(query));for(const record of found){const li=document.createElement("li");li.textContent=record.values.title+" · "+(record.values.progress||0)+"%";list.appendChild(li)}document.getElementById("count").textContent=found.length+" matches"}document.getElementById("search").oninput=()=>draw(state);document.getElementById("save").onclick=async()=>{try{draw(await lf.create({title:document.getElementById("title").value,author:"QA fixture author"}));output.textContent="Saved through the host"}catch(error){output.textContent=error.message}};document.getElementById("progress").onclick=async()=>{try{draw(await lf.update(state.records[0].id,{progress:45}));output.textContent="Progress saved"}catch(error){output.textContent=error.message}};lf.subscribe(draw);draw(state);lf.reportReady();})();';
const toolJs=startJs+'document.getElementById("saved").textContent=state.records.length+" saved records";const run=document.getElementById("run");run.disabled=state.preview;run.textContent=state.preview?"Publish to run tool":"Estimate reading time";run.onclick=async()=>{output.textContent="Calculating…";try{const response=await lf.runTool("readingTime",1,{minutesPerPercent:Number(document.getElementById("minutes").value)});output.textContent=response.result.remainingMinutes+" minutes across "+response.result.books+" books"}catch(error){output.textContent=error.message}};lf.reportReady();})();';
const generator:SiteGenerator=async input=>{
 calls.push({prompt:input.prompt,repair:!!input.repair});expect(JSON.stringify(input)).not.toMatch(/PRIVATE_QA_RECORD|PRIVATE_QA_DEFAULT/);
 const current=input.current??readingDefinition(),kind=input.prompt.includes('photos')?'photos':input.prompt.includes('search')?'search':'tool',reuse=input.prompt.includes('reuse');
 const intro:GenerationOutline={version:1,title:kind==='photos'?'Photo discoveries':'Reading desk',layout:'flow',skin:'sage',sections:[{id:'intro',kind:'hero',label:'A new experience',columns:12}]};
 input.onProgress?.({stage:'planning',message:'Offline authored layout checkpoint.',ui:intro});
 if(kind==='photos')await new Promise<void>(resolve=>outlineRelease=resolve);
 const outlined:GenerationOutline={...intro,layout:'split',sections:[{id:'intro',kind:'hero',label:'Your saved collection',columns:8},{id:'summary',kind:'metrics',label:'Your perspective',columns:4,items:2},{id:'content',kind:kind==='photos'?'media':kind==='search'?'collection':'form',label:'The interactive surface',columns:12,items:3}]};
 const html=kind==='photos'?'<main><small>PHOTO DISCOVERIES</small><h1>Swipe your perspective.</h1><p id="saved"></p><article id="card"><img id="photo" alt="Saved photograph"><h2 id="card-title"></h2></article><div id="controls"><button id="skip">Skip photo</button><button id="like">Like photo</button></div><p id="result" role="status"></p></main>':kind==='search'?'<main><small>A DIFFERENT EXPERIENCE</small><h1>A searchable reading desk.</h1><label>Search saved records<input id="search"></label><p id="count"></p><ul id="records"></ul><label>New title<input id="title"></label><button id="save">Save record</button><button id="progress">Set first progress to 45%</button><p id="result" role="status"></p></main>':`<main><small>SERVER COMPUTATION</small><h1>${reuse?'Reading time, revisited.':'How much time remains?'}</h1><p id="saved"></p><label>Minutes per percent<input id="minutes" type="number" value="3" min="0" max="10"></label><button id="run">Estimate reading time</button><p id="result" role="status"></p></main>`;
 const actions=current.appSpec.actions.filter(action=>action.type!=='tool.invoke');if(kind==='tool')actions.push({id:'estimate',type:'tool.invoke',label:'Estimate reading time'});
 const assetIds=current.appSpec.generated?.assetIds??[];
 const proposal:Proposal={entitySchema:current.entitySchema,appSpec:{...current.appSpec,title:kind==='photos'?'Photo discoveries':kind==='search'?'Reading desk':'Reading time',description:'An explicitly offline authored QA candidate.',layout:'flow',actions,components:[componentSchema.parse({id:'qa-custom-site',type:'generated-site',version:1,fields:current.entitySchema.fields.filter(f=>f.public).map(f=>f.id),actionIds:actions.map(a=>a.id),...(kind==='tool'?{toolBindings:[{actionId:'estimate',toolId:tool.toolId,toolVersion:1,kind:'generated'}]}:{})})],generated:{format:'html-v1',bridgeVersion:1,html,css,js:kind==='photos'?photoJs:kind==='search'?searchJs:toolJs,assetIds}},summary:'Offline authored custom page through the real host pipeline.',source:'gemini',capabilityGaps:[],...(kind==='tool'&&!reuse?{codeToolProposals:[tool]}:{})};
 if(reuse){expect(input.registeredTools?.find(t=>t.toolId==='readingTime'&&t.toolVersion===1)).toBeDefined();expect(JSON.stringify(input.registeredTools)).not.toContain('async function run');}
 if(input.prompt.includes('invalid'))proposal.appSpec.generated!.js='const = invalid syntax;';
 input.onProgress?.({stage:'writing',message:'Offline actual source checkpoint.',ui:outlined,source:proposal.appSpec.generated,...(kind==='tool'&&!reuse?{tool:{toolId:tool.toolId,name:tool.name,phase:'writing'}}:{})});
 if(kind==='photos')await new Promise<void>(resolve=>sourceRelease=resolve);
 return proposal;
};
const api=await buildApp({db:await createDatabase(),origin,localDemo:true,siteGenerator:generator,staticDir:resolve('apps/web/dist')});
const seeded=(await api.store.getSpace('reading'))!;seeded.definition!.entitySchema.fields.push({id:'photo',label:'Photo reference',type:'text',public:true,required:false},{id:'private_note',label:'Private note',type:'text',public:false,required:false,defaultValue:'PRIVATE_QA_DEFAULT'});seeded.records[0].values.private_note='PRIVATE_QA_RECORD';await api.store.db.transaction(tx=>api.store.event(seeded,'definition.published',tx));
await api.app.listen({host:'127.0.0.1',port:4349});
const browser=await chromium.launch({headless:true,channel:'chrome'}),owner=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'no-preference'}),visitor=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
await owner.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});const page=await owner.newPage(),publicPage=await visitor.newPage();page.setDefaultTimeout(20000);publicPage.setDefaultTimeout(20000);
const errors:string[]=[],posts:string[]=[];for(const tab of [page,publicPage]){tab.on('pageerror',error=>errors.push(error.message));tab.on('request',request=>{if(request.method()==='POST')posts.push(new URL(request.url()).pathname)});}
const preview=()=>page.frameLocator('iframe[title="Generated website preview"]'),live=(tab=page)=>tab.frameLocator('iframe[title="Generated website"]');
async function enter(frame:FrameLocator,name:string){await frame.getByRole('button',{name,exact:true}).focus();await page.keyboard.press('Enter');}
async function check(name:string,run:()=>Promise<unknown>){const details=await run();checks.push({name,status:'passed',...(details?{details}:{})});console.log('PASS',name);}
async function begin(prompt:string){await page.getByRole('button',{name:'Open the space designer'}).click();await page.getByRole('textbox',{name:'Describe your website'}).fill(prompt);await page.locator('form').filter({has:page.getByRole('textbox',{name:'Describe your website'})}).getByRole('button').click();}
async function publish(){await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Publish website',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');}
async function noOverflow(tab:Page,frame:FrameLocator){expect(await tab.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(await frame.locator('body').evaluate(element=>element.scrollWidth<=document.documentElement.clientWidth+1)).toBe(true);}
try{
 await mkdir(reportDir,{recursive:true});await page.goto(`${origin}/s/reading`);await publicPage.goto(`${origin}/s/reading`);await publicPage.evaluate(()=>{(window as any).qaNavigation='kept'});
 const session=await(await owner.request.get(`${origin}/api/session`)).json();const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXuoAAAAASUVORK5CYII=';
 const uploaded=await owner.request.post(`${origin}/api/spaces/reading/assets`,{headers:{origin,'x-csrf-token':session.csrfToken},data:{mimeType:'image/png',dataBase64:png}});expect(uploaded.status()).toBe(201);const asset=await uploaded.json();
 await api.store.db.transaction(async tx=>{const state=(await api.store.getSpace('reading',tx,true))!;for(const record of state.records)record.values.photo=asset.assetId;await api.store.event(state,'records.changed',tx)});
 const retainedIds=seeded.records.map(record=>record.id),retainedUrl=page.url();
 await check('Actual host SSE checkpoints reshape stable safe UI; source is escaped and incomplete code never runs',async()=>{
  await begin('photos: an offline custom swipe discovery interaction');await expect(page.locator('[data-outline-id=intro]')).toBeVisible();await expect.poll(()=>!!outlineRelease).toBe(true);await page.locator('[data-outline-id=intro]').evaluate(element=>(element as any).qaIdentity='same');expect(await page.locator('iframe[title="Generated website preview"]').count()).toBe(0);
  outlineRelease!();outlineRelease=undefined;await expect(page.locator('[data-outline-id]')).toHaveCount(3);expect(await page.locator('[data-outline-id=intro]').evaluate(element=>(element as any).qaIdentity)).toBe('same');await expect(page.locator('[data-outline-id=intro]')).toHaveCSS('--outline-columns','8');await page.screenshot({path:`${reportDir}/formation-desktop.png`});
  await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Phone',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${reportDir}/formation-mobile.png`});await page.setViewportSize({width:1440,height:1080});await page.getByRole('button',{name:'Desktop',exact:true}).click();
  await page.getByRole('tab',{name:'HTML',exact:true}).click();await expect(page.locator('.studio-source code')).toContainText('<main>');expect(await page.locator('.studio-source main').count()).toBe(0);expect(await page.locator('iframe[title="Generated website preview"]').count()).toBe(0);await expect.poll(()=>!!sourceRelease).toBe(true);sourceRelease!();sourceRelease=undefined;await page.getByRole('tab',{name:'Preview',exact:true}).click();await expect(preview().getByRole('heading',{name:'Swipe your perspective.'})).toBeVisible();
 });
 await check('Custom photo drag/button interaction works in preview and publish preserves records, image references and URL',async()=>{
  await preview().getByRole('button',{name:'Like photo',exact:true}).click();await expect(preview().getByRole('status')).toHaveText('Liked · 1 favorites');expect((await api.store.getSpace('reading'))!.definition!.definitionVersion).toBe(1);await publish();await expect(live(publicPage).getByRole('heading',{name:'Swipe your perspective.'})).toBeVisible();
  await live().locator('#card').hover();const box=(await live().locator('#card').boundingBox())!;const dragY=box.y+box.height-24;await page.mouse.move(box.x+box.width/2,dragY);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,dragY,{steps:8});await page.mouse.up();await expect(live().getByRole('status')).toHaveText('Liked · 1 favorites');await expect(live().locator('#photo')).toHaveAttribute('src',/^data:image\/png;base64,/);
  await expect(publicPage.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');await live(publicPage).getByRole('button',{name:'Skip photo',exact:true}).focus();await publicPage.keyboard.press('Enter');await expect(live(publicPage).getByRole('status')).toHaveText('Skipped · 0 favorites');await noOverflow(page,live());await noOverflow(publicPage,live(publicPage));await page.screenshot({path:`${reportDir}/photo-desktop.png`});await publicPage.screenshot({path:`${reportDir}/photo-mobile.png`});
  expect(page.url()).toBe(retainedUrl);const state=(await api.store.getSpace('reading'))!;expect(state.records.map(r=>r.id)).toEqual(retainedIds);expect(state.records.every(r=>r.values.photo===asset.assetId)).toBe(true);expect(state.records[0].values.private_note).toBe('PRIVATE_QA_RECORD');expect(await publicPage.evaluate(()=>(window as any).qaNavigation)).toBe('kept');
 });
 await check('A substantially different search/save page evolves the same space; preview stays read-only',async()=>{
  await begin('search: an offline interactive searchable reading desk');await expect(preview().getByRole('heading',{name:'A searchable reading desk.'})).toBeVisible();await preview().getByLabel('New title').fill('Do not save preview');await enter(preview(),'Save record');await expect(preview().getByRole('status')).toContainText('read-only');expect((await api.store.getSpace('reading'))!.records).toHaveLength(retainedIds.length);await publish();await expect(live(publicPage).getByRole('heading',{name:'A searchable reading desk.'})).toBeVisible();
  const firstTitle=String((await api.store.getSpace('reading'))!.records[0].values.title);await live().getByLabel('Search saved records').fill(firstTitle);await expect(live().locator('#count')).toHaveText('1 matches');await live().getByLabel('Search saved records').fill('no matching synthetic title');await expect(live().locator('#count')).toHaveText('0 matches');await live().getByLabel('Search saved records').fill('');await live(publicPage).getByLabel('Search saved records').fill(firstTitle);await expect(live(publicPage).locator('#count')).toHaveText('1 matches');await live(publicPage).getByLabel('Search saved records').fill('');
  await owner.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});const writesBefore=posts.filter(path=>path.endsWith('/actions')).length;await live().getByLabel('New title').fill('QA saved from generated page');await enter(live(),'Save record');await expect(live().locator('#records')).toContainText('QA saved from generated page');expect(posts.filter(path=>path.endsWith('/actions')).length-writesBefore).toBe(1);await expect(live(publicPage).locator('#count')).toHaveText(`${retainedIds.length+1} matches`);await enter(live(),'Set first progress to 45%');await expect(live().getByRole('status')).toHaveText('Progress saved');await expect(live(publicPage).locator('#records')).toContainText('45%');
  await noOverflow(page,live());await noOverflow(publicPage,live(publicPage));expect(page.url()).toBe(retainedUrl);expect(await publicPage.evaluate(()=>(window as any).qaNavigation)).toBe('kept');await page.screenshot({path:`${reportDir}/search-desktop.png`});await publicPage.screenshot({path:`${reportDir}/search-mobile.png`});
  const frame=page.frames().find(f=>f.url().includes('/api/generated-frame'))!;expect(await frame.evaluate(()=>JSON.stringify((window as any).qaState))).not.toMatch(/PRIVATE_QA|csrfToken|sourceDigest|cookie/);
 });
 await check('Third custom page is bound to original host-tested backend source; actual QuickJS reads scoped records',async()=>{
  await begin('tool: an offline original reading-time calculator');await expect(preview().getByRole('heading',{name:'How much time remains?'})).toBeVisible();await expect(preview().getByRole('button',{name:'Publish to run tool',exact:true})).toBeDisabled();expect(await api.store.getCodeTools(seeded.space.id)).toEqual([]);
  await page.getByRole('tab',{name:'Tools',exact:true}).click();await expect(page.locator('.tool-evidence-card code').first()).toContainText('async function run');await expect(page.getByText('Host tests passed',{exact:true})).toBeVisible();await expect(page.getByText('Pass · Different progress',{exact:true})).toBeVisible();await page.screenshot({path:`${reportDir}/tested-tool.png`});await page.getByRole('tab',{name:'Preview',exact:true}).click();await publish();await expect(live(publicPage).getByRole('heading',{name:'How much time remains?'})).toBeVisible();
  await enter(live(),'Estimate reading time');const records=(await api.store.getSpace('reading'))!.records,expected=Math.round(records.reduce((sum,r)=>sum+Math.max(0,100-Number(r.values.progress||0)),0)*3);await expect(live().getByRole('status')).toHaveText(`${expected} minutes across ${records.length} books`);expect((await api.store.getCodeTools(seeded.space.id))[0].invocationCount).toBe(1);
  await noOverflow(page,live());await noOverflow(publicPage,live(publicPage));await page.screenshot({path:`${reportDir}/calculator-desktop.png`});await publicPage.screenshot({path:`${reportDir}/calculator-mobile.png`});await page.setViewportSize({width:390,height:844});await enter(live(),'Estimate reading time');await expect(live().getByRole('status')).toHaveText(`${expected} minutes across ${records.length} books`);expect((await api.store.getCodeTools(seeded.space.id))[0].invocationCount).toBe(2);await noOverflow(page,live());await page.screenshot({path:`${reportDir}/calculator-owner-mobile.png`});await page.setViewportSize({width:1440,height:1080});return {actualQuickJsResult:{remainingMinutes:expected,books:records.length},interactiveWidths:[390,1440]};
 });
 await check('Anonymous tool use opens login, sends zero invokes and has no Owner orb or backend source',async()=>{
  const before=posts.filter(path=>path.endsWith('/readingTime/invoke')).length;await live(publicPage).getByRole('button',{name:'Estimate reading time',exact:true}).focus();await publicPage.keyboard.press('Enter');await expect(publicPage.getByRole('heading',{name:'Make this moment yours.'})).toBeVisible();expect(posts.filter(path=>path.endsWith('/readingTime/invoke')).length).toBe(before);expect(await publicPage.getByRole('button',{name:'Open the space designer'}).count()).toBe(0);const frame=publicPage.frames().find(f=>f.url().includes('/api/generated-frame'))!;const state=await frame.evaluate(()=>(window as any).qaState);expect(state.toolBindings).toEqual([]);expect(state.permissions.canUseTools).toBe(false);expect(JSON.stringify(state)).not.toMatch(/PRIVATE_QA|async function run|sourceDigest|csrfToken/);await publicPage.keyboard.press('Escape');
 });
 await check('Exact registered tool is reused in a new page revision without regenerating or replacing source',async()=>{
  const old=(await api.store.getCodeTools(seeded.space.id))[0];await begin('tool reuse: keep the records and reuse readingTime in a fresh layout');await expect(preview().getByRole('heading',{name:'Reading time, revisited.'})).toBeVisible();await page.getByRole('tab',{name:'Tools',exact:true}).click();await expect(page.locator('.tool-evidence-card code').first()).toContainText(old.spec.source);await expect(page.getByText('Host tests passed',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Preview',exact:true}).click();await publish();await enter(live(),'Estimate reading time');await expect(live().getByRole('status')).toContainText('minutes across');const after=(await api.store.getCodeTools(seeded.space.id))[0];expect(after.sourceDigest).toBe(old.sourceDigest);expect(after.spec).toEqual(old.spec);expect(after.invocationCount).toBe(old.invocationCount+1);expect(page.url()).toBe(retainedUrl);
  await page.reload();await expect(live().getByRole('heading',{name:'Reading time, revisited.'})).toBeVisible();expect((await api.store.getSpace('reading'))!.records[0].values.photo).toBe(asset.assetId);expect((await api.store.getSpace('reading'))!.definition!.entitySchema.fields.find(f=>f.id==='private_note')!.defaultValue).toBe('PRIVATE_QA_DEFAULT');
 });
 await check('Invalid source receives one concrete repair and cannot replace the published definition, records or tools',async()=>{
  const old=(await api.store.getSpace('reading'))!,oldTools=await api.store.getCodeTools(seeded.space.id),before=calls.length;await begin('invalid tool reuse: ordinary invalid syntax regression');await expect.poll(async()=>{const rows=await api.store.db.query<{data:{job:GenerationJob}}>("SELECT data FROM lf_generations WHERE space_id=$1 ORDER BY data->'job'->>'createdAt' DESC",[seeded.space.id]);return rows.rows[0].data.job.stage;}).toBe('failed');await expect(page.locator('.studio-brief [role=alert]')).toContainText('JavaScript syntax');
  expect(calls.length-before).toBe(2);expect(calls.slice(before).map(call=>call.repair)).toEqual([false,true]);expect((await api.store.getSpace('reading'))!.definition).toEqual(old.definition);expect((await api.store.getSpace('reading'))!.records).toEqual(old.records);expect(await api.store.getCodeTools(seeded.space.id)).toEqual(oldTools);expect(await page.getByRole('button',{name:'Publish website',exact:true}).isEnabled()).toBe(false);await page.keyboard.press('Escape');await expect(live(publicPage).getByRole('heading',{name:'Reading time, revisited.'})).toBeVisible();
 });
 await check('Changed account discards a completed tool response delayed in transport; Participant sends no new invocation',async()=>{
  let received=false,release!:(()=>void);const before=posts.filter(path=>path.endsWith('/readingTime/invoke')).length,invokedBefore=(await api.store.getCodeTools(seeded.space.id))[0].invocationCount;
  await owner.route('**/api/spaces/reading/code-tools/readingTime/invoke',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);received=true;await new Promise<void>(resolve=>release=resolve);await route.fulfill({response}).catch(()=>{});});
  try{await enter(live(),'Estimate reading time');await expect.poll(()=>received).toBe(true);expect((await api.store.getCodeTools(seeded.space.id))[0].invocationCount).toBe(invokedBefore+1);await expect(page.getByText('Running the connected tool…',{exact:true})).toBeVisible();
   await owner.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'participant'}});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Open the space designer'})).toHaveCount(0);release();await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');await enter(live(),'Estimate reading time');await expect(live().getByRole('status')).toContainText('cannot use this tool');expect(posts.filter(path=>path.endsWith('/readingTime/invoke')).length-before).toBe(1);expect(await page.getByText('Tool completed.',{exact:false}).count()).toBe(0);
  }finally{release?.();await owner.unroute('**/api/spaces/reading/code-tools/readingTime/invoke');}
  return {serverCall:'Completed before identity change',delayedDelivery:'Explicit local transport fixture',lateResult:'Discarded'};
 });
 expect(errors).toEqual([]);await writeFile(`${reportDir}/results.json`,JSON.stringify({at:new Date().toISOString(),scope:'Independent real Chrome, host generation/SSE/storage/assets/frame/MessageChannel and actual QuickJS. HTML/CSS/JS/tools/outline come from an explicitly offline injected SiteGenerator. No provider, real OAuth/cloud or production claim.',checks,generatorCalls:calls,protectedPosts:posts,errors},null,2));
}catch(error){await mkdir(reportDir,{recursive:true});await page.screenshot({path:`${reportDir}/failed.png`,fullPage:true}).catch(()=>{});await writeFile(`${reportDir}/failed.json`,JSON.stringify({at:new Date().toISOString(),error:String(error),checks,body:await page.locator('body').innerText().catch(()=>''),frames:await Promise.all(page.frames().filter(f=>f.parentFrame()).map(async f=>({url:f.url(),body:await f.locator('body').innerText().catch(()=>'(detached)')}))),calls,errors},null,2));throw error}finally{outlineRelease?.();sourceRelease?.();await owner.close();await visitor.close();await browser.close();await api.app.close();}
