/** LF204 regressions for coordinator review findings. Local gallery + real PGlite.
 * One presentation request is paused by Playwright to model transport delay, then
 * continued to the real local backend; no response is mocked.
 */
import {chromium,expect,type BrowserContext} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {componentSchema,type Snapshot} from '../../packages/contracts/src/index';
const origin='http://localhost:5173',out='docs/qa/module-expansion';await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await ctx.newPage();page.setDefaultTimeout(12000);
const errors:string[]=[],checks:{name:string;status:string;detail?:string}[]=[];page.on('pageerror',e=>errors.push(e.message));
async function check(name:string,fn:()=>Promise<void>){try{await fn();checks.push({name,status:'pass'});console.log('PASS',name)}catch(e){checks.push({name,status:'fail',detail:(e as Error).message});console.log('FAIL',name,(e as Error).message);await page.screenshot({path:`${out}/regression-failure-${checks.length}.png`,fullPage:true}).catch(()=>{});}}
async function gallery(type:string){await page.goto(`${origin}/modules?type=${type}`,{waitUntil:'networkidle'});const f=page.locator(`[data-module-type="${type}"]`);await expect(f).toBeVisible();return f;}
async function settings(type:string){const f=await gallery(type);await page.getByRole('button',{name:'Customize layout',exact:true}).click();await f.getByRole('button',{name:/^Configure/}).click();return f;}
async function post(client:BrowserContext,path:string,data:unknown){const s=await (await client.request.get(`${origin}/api/session`)).json();return client.request.post(`${origin}${path}`,{data,headers:{origin,'x-csrf-token':s.csrfToken??''}});}
async function snapshot(slug:string){return (await ctx.request.get(`${origin}/api/spaces/${slug}/snapshot`)).json() as Promise<Snapshot>;}
let slug='';
try{
  await check('invalid histogram bins retain the app tree and disable Save until corrected',async()=>{const f=await settings('histogram');await f.getByLabel('bins',{exact:true}).fill('0');await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page.getByRole('button',{name:'Save layout',exact:true})).toBeDisabled();await f.getByLabel('bins',{exact:true}).fill('6');await expect(page.getByRole('button',{name:'Save layout',exact:true})).toBeEnabled();});
  await check('invalid calculator precision retains the app tree and disables Save',async()=>{const f=await settings('calculator');await f.getByLabel('precision',{exact:true}).fill('-1');await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page.getByRole('button',{name:'Save layout',exact:true})).toBeDisabled();await f.getByLabel('precision',{exact:true}).fill('2');await expect(page.getByRole('button',{name:'Save layout',exact:true})).toBeEnabled();});
  await check('leaderboard limit applies after ranking, selecting the real top two',async()=>{const f=await settings('leaderboard');await f.getByLabel('limit',{exact:true}).fill('2');await expect(f.locator('.leaderboard li')).toHaveCount(2);expect(await f.locator('.leaderboard strong').allTextContents()).toEqual(['65','54']);});
  await check('unsaved text survives switching between records',async()=>{const f=await gallery('text-editor');await f.getByRole('textbox',{name:'Notes / answer',exact:true}).fill('QA retained unsaved text');await f.getByLabel('Choose record').selectOption('sample-1');await f.getByLabel('Choose record').selectOption('sample-0');await expect(f.getByRole('textbox',{name:'Notes / answer',exact:true})).toHaveValue('QA retained unsaved text');await expect(f.getByRole('button',{name:'Save text'})).toBeEnabled();});
  await check('unsaved range value survives switching between records',async()=>{const f=await gallery('range-input');await f.getByLabel('Value',{exact:true}).fill('77');await f.getByLabel('Choose record').selectOption('sample-1');await f.getByLabel('Choose record').selectOption('sample-0');await expect(f.getByLabel('Value',{exact:true})).toHaveValue('77');await expect(f.getByRole('button',{name:'Save value'})).toBeEnabled();});
  await check('card compact and hero variants materially change the rendered presentation',async()=>{const f=await settings('cards');await f.getByRole('combobox',{name:'Module appearance',exact:true}).selectOption('compact');await expect(f.locator('.record-cards')).toHaveClass(/variant-compact/);const compact=await f.locator('.record-item').first().boundingBox();await f.getByRole('combobox',{name:'Module appearance',exact:true}).selectOption('hero');await expect(f.locator('.record-cards')).toHaveClass(/variant-hero/);const hero=await f.locator('.record-item').first().boundingBox();expect(Math.abs(hero!.height-compact!.height)+Math.abs(hero!.width-compact!.width)).toBeGreaterThan(30);for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);}await page.setViewportSize({width:1440,height:1000});});
  await check('create isolated local two-record regression fixture',async()=>{
    const health=await (await ctx.request.get(`${origin}/api/health`)).json();expect(health.database).toBe('pglite');expect(health.planner).toBe('local');expect((await ctx.request.post(`${origin}/auth/local`,{data:{persona:'owner'},headers:{origin}})).status()).toBe(200);
    slug=`qa-drafts-${randomUUID().slice(0,8)}`;const created=await post(ctx,'/api/spaces',{title:'QA draft regression',slug,prompt:'Create a reading collection for books'});expect(created.status(),await created.text()).toBe(201);
    for(const title of ['QA draft A','QA draft B']){const s=await snapshot(slug);const added=await post(ctx,`/api/spaces/${slug}/actions`,{requestId:randomUUID(),definitionVersion:s.definition!.definitionVersion,actionId:s.definition!.appSpec.actions.find(a=>a.type==='record.create')!.id,values:{title,author:'Original note',progress:12}});expect(added.status(),await added.text()).toBe(200);}
    const s=await snapshot(slug);const actionIds=[s.definition!.appSpec.actions.find(a=>a.type==='record.update')!.id];const components=[componentSchema.parse({id:'qa-text',type:'text-editor',version:1,fields:['author','title'],actionIds,size:{columns:6}}),componentSchema.parse({id:'qa-range',type:'range-input',version:1,fields:['title','progress'],valueField:'progress',actionIds,size:{columns:6}})];const configured=await post(ctx,`/api/spaces/${slug}/presentation`,{requestId:randomUUID(),baseDefinitionVersion:s.definition!.definitionVersion,components});expect(configured.status(),await configured.text()).toBe(200);await page.goto(`${origin}/s/${slug}`);await expect(page.locator('[data-module-type="text-editor"]')).toBeVisible();
  });
  await check('concurrent record update preserves text draft and blocks stale overwrite',async()=>{
    const f=page.locator('[data-module-type="text-editor"]'),s=await snapshot(slug),r=s.records[0]!;await f.getByRole('textbox',{name:'Author',exact:true}).fill('Local unsaved text');const changed=await post(ctx,`/api/spaces/${slug}/actions`,{requestId:randomUUID(),definitionVersion:s.definition!.definitionVersion,actionId:s.definition!.appSpec.actions.find(a=>a.type==='record.update')!.id,recordId:r.id,recordVersion:r.version,values:{author:'Remote saved text'}});expect(changed.status(),await changed.text()).toBe(200);
    await expect(f.getByRole('button',{name:'Save text',exact:true})).toBeDisabled();await expect(f.getByRole('textbox',{name:'Author',exact:true})).toHaveValue('Local unsaved text');expect((await snapshot(slug)).records[0]!.values.author).toBe('Remote saved text');
  });
  await check('concurrent numeric update preserves range draft and blocks stale overwrite',async()=>{
    const f=page.locator('[data-module-type="range-input"]'),s=await snapshot(slug),r=s.records[0]!;await f.getByLabel('Value',{exact:true}).fill('77');const changed=await post(ctx,`/api/spaces/${slug}/actions`,{requestId:randomUUID(),definitionVersion:s.definition!.definitionVersion,actionId:s.definition!.appSpec.actions.find(a=>a.type==='record.update')!.id,recordId:r.id,recordVersion:r.version,values:{progress:55}});expect(changed.status(),await changed.text()).toBe(200);
    await expect(f.getByRole('button',{name:'Save value',exact:true})).toBeDisabled();await expect(f.getByLabel('Value',{exact:true})).toHaveValue('77');expect((await snapshot(slug)).records[0]!.values.progress).toBe(55);
  });
  await check('layout controls lock throughout a delayed real presentation request',async()=>{
    await page.reload();await page.getByRole('button',{name:'Customize layout',exact:true}).click();const f=page.locator('[data-module-type="text-editor"]');await f.getByRole('button',{name:/^Configure/}).click();await f.getByLabel('Title',{exact:true}).fill('QA locked save');
    let release!:()=>void,started!:()=>void;const pending=new Promise<void>(r=>release=r),began=new Promise<void>(r=>started=r);await page.route('**/presentation',async route=>{started();await pending;await route.continue();});
    try{const response=page.waitForResponse(r=>r.url().endsWith('/presentation'));await page.getByRole('button',{name:'Save layout',exact:true}).click();await began;
      await expect(page.getByRole('button',{name:'Saving…',exact:true})).toBeDisabled();await expect(page.getByLabel('Layout preset',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Add module ＋',exact:true})).toBeDisabled();await expect(f.getByLabel('Title',{exact:true})).toBeDisabled();await expect(f.getByRole('button',{name:/^Configure/})).toBeDisabled();await expect(f.getByRole('button',{name:/^Resize/})).toBeDisabled();
      release();expect((await response).status()).toBe(200);await expect(page.getByRole('button',{name:'Customize layout',exact:true})).toBeVisible();
    }finally{release();await page.unroute('**/presentation');}
  });
  await check('review regression flows produce no browser exception',async()=>{expect(errors).toEqual([]);});
}finally{await writeFile(`${out}/regressions.json`,JSON.stringify({at:new Date().toISOString(),scope:'Coordinator review findings; sample gallery plus local PGlite and transport-delay fixture',checks,errors,slug},null,2));await browser.close();}
console.log('TOTAL',checks.filter(c=>c.status==='pass').length,'/',checks.length);if(checks.some(c=>c.status==='fail')||errors.length)process.exitCode=1;
