/** LF204 gallery behavior + real isolated local PGlite presentation workflow.
 * No request interception, external model, Google or cloud database calls.
 */
import {chromium,expect,type Page,type BrowserContext} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import type {Snapshot} from '../../packages/contracts/src/index';

const origin='http://localhost:5173',out='docs/qa/module-expansion';await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const owner=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),anon=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
const page=await owner.newPage(),viewer=await anon.newPage();page.setDefaultTimeout(12000);viewer.setDefaultTimeout(12000);
const errors:string[]=[],checks:{name:string;status:string;detail?:string}[]=[];for(const p of [page,viewer])p.on('pageerror',e=>errors.push(e.message));
async function check(name:string,fn:()=>Promise<void>){try{await fn();checks.push({name,status:'pass'});console.log('PASS',name)}catch(e){checks.push({name,status:'fail',detail:(e as Error).message});console.log('FAIL',name,(e as Error).message);await page.screenshot({path:`${out}/interaction-failure-${checks.length}.png`,fullPage:true}).catch(()=>{});}}
async function gallery(type:string){await page.goto(`${origin}/modules?type=${type}`,{waitUntil:'networkidle'});const frame=page.locator(`[data-module-type="${type}"]`);await expect(frame).toBeVisible();return frame;}
async function addModule(p:Page,type:string){await p.getByRole('button',{name:'Add module ＋',exact:true}).click();const dialog=p.getByRole('dialog');await dialog.getByLabel('Find a module',{exact:true}).fill(type);const article=dialog.locator('article').filter({has:p.getByRole('heading',{name:type.replaceAll('-',' '),exact:true})});await article.getByRole('button',{name:'Add module ＋',exact:true}).click();}
async function session(client:BrowserContext){return (await client.request.get(`${origin}/api/session`)).json();}
async function post(client:BrowserContext,path:string,data:unknown){const s=await session(client);return client.request.post(`${origin}${path}`,{data,headers:{origin,'x-csrf-token':s.csrfToken??''}});}
async function snap(slug:string,client=owner){return (await client.request.get(`${origin}/api/spaces/${slug}/snapshot`)).json() as Promise<Snapshot>;}
let slug='';
try{
  await check('metric-grid computes sum, average, minimum and maximum',async()=>{const f=await gallery('metric-grid');expect(await f.locator('.metric-tiles strong').allTextContents()).toEqual(['234','39','18','65']);});
  await check('line-chart exposes six daily totals with the correct total',async()=>{const f=await gallery('line-chart');await f.getByText('View data',{exact:true}).click();expect(await f.locator('dl>div').count()).toBe(6);expect((await f.locator('dd').allTextContents()).reduce((n,v)=>n+Number(v),0)).toBe(234);});
  await check('donut-chart aggregates category shares',async()=>{const f=await gallery('donut-chart');expect(await f.locator('.chart-legend strong').allTextContents()).toEqual(['38%','31%','31%']);await expect(f.locator('.donut-disc strong')).toHaveText('234');});
  await check('histogram accounts for all six numeric records',async()=>{const f=await gallery('histogram');await f.getByText('View data',{exact:true}).click();expect((await f.locator('dd').allTextContents()).reduce((n,v)=>n+Number(v),0)).toBe(6);});
  await check('scatter-plot renders six points and opens a selected source record',async()=>{const f=await gallery('scatter-plot');await expect(f.locator('circle')).toHaveCount(6);await f.getByText('View records',{exact:true}).click();await f.locator('details button').first().click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').getByRole('heading')).toContainText('Read one chapter');await page.keyboard.press('Escape');});
  await check('activity-heatmap renders 84 days and exposes 20 check-ins',async()=>{const f=await gallery('activity-heatmap');await expect(f.locator('.activity-grid>span')).toHaveCount(84);await f.getByText('View data',{exact:true}).click();expect((await f.locator('dd').allTextContents()).reduce((n,v)=>n+Number(v),0)).toBe(20);});
  await check('leaderboard ranks the largest quantity first and opens the record',async()=>{const f=await gallery('leaderboard');await expect(f.locator('li').first()).toContainText('Practice a language');await expect(f.locator('li').first().locator('strong')).toHaveText('65');await f.locator('li').first().getByRole('button').click();await expect(page.getByRole('dialog').getByRole('heading')).toContainText('Practice a language');await page.keyboard.press('Escape');});
  await check('funnel presents current stage counts without claiming conversion rates',async()=>{const f=await gallery('funnel');expect(await f.locator('.funnel strong').allTextContents()).toEqual(['2','2','2']);await expect(f).toContainText('not conversion rates');});
  await check('checklist toggles a stored local sample boolean',async()=>{const f=await gallery('checklist');const c=f.getByRole('checkbox').first();await expect(c).toBeChecked();await c.uncheck();await expect(c).not.toBeChecked();await expect(f.locator('.checklist-row').first()).toContainText('To do');});
  await check('rating-input edits a selected record and keeps other records separate',async()=>{const f=await gallery('rating-input');await f.getByRole('button',{name:'Rate 2',exact:true}).click();await expect(f.getByRole('button',{name:'Rate 2',exact:true})).toHaveAttribute('aria-pressed','true');await f.getByLabel('Choose record').selectOption('sample-1');await expect(f.getByRole('button',{name:'Rate 5',exact:true})).toHaveAttribute('aria-pressed','true');await f.getByLabel('Choose record').selectOption('sample-0');await expect(f.getByRole('button',{name:'Rate 2',exact:true})).toHaveAttribute('aria-pressed','true');});
  await check('number-stepper increments/decrements the actual numeric field',async()=>{const f=await gallery('number-stepper');await f.getByRole('button',{name:'Increase Actual'}).click();await expect(f.locator('output')).toHaveText('25');await f.getByRole('button',{name:'Decrease Actual'}).click();await expect(f.locator('output')).toHaveText('24');});
  await check('range-input saves a changed value and restores it after record selection',async()=>{const f=await gallery('range-input');await f.getByLabel('Value',{exact:true}).fill('77');await f.getByRole('button',{name:'Save value'}).click();await expect(f.getByRole('button',{name:'Save value'})).toBeDisabled();await f.getByLabel('Choose record').selectOption('sample-1');await f.getByLabel('Choose record').selectOption('sample-0');await expect(f.getByLabel('Value',{exact:true})).toHaveValue('77');});
  await check('segmented-input switches the selected category',async()=>{const f=await gallery('segmented-input');await f.getByRole('button',{name:'Restore',exact:true}).click();await expect(f.getByRole('button',{name:'Restore',exact:true})).toHaveAttribute('aria-pressed','true');});
  await check('toggle-panel changes the selected boolean',async()=>{const f=await gallery('toggle-panel');await f.getByRole('switch').uncheck();await expect(f.getByRole('switch')).not.toBeChecked();await f.getByLabel('Choose record').selectOption('sample-2');await expect(f.getByRole('switch')).toBeChecked();await f.getByLabel('Choose record').selectOption('sample-0');await expect(f.getByRole('switch')).not.toBeChecked();});
  await check('quick-add creates a new record visible in another added module',async()=>{const f=await gallery('quick-add');await f.getByLabel(/^Name/).fill('QA quick note');await f.getByRole('button',{name:'Add record'}).click();await expect(f.getByLabel(/^Name/)).toHaveValue('');await addModule(page,'data-table');await page.getByRole('button',{name:'Save layout',exact:true}).click();await expect(page.locator('[data-module-type="data-table"]')).toContainText('QA quick note');});
  await check('text-editor saves long text and restores it after changing records',async()=>{const f=await gallery('text-editor');await f.getByRole('textbox',{name:'Notes / answer',exact:true}).fill('QA text saved locally');await f.getByRole('button',{name:'Save text'}).click();await expect(f.getByRole('button',{name:'Save text'})).toBeDisabled();await f.getByLabel('Choose record').selectOption('sample-1');await f.getByLabel('Choose record').selectOption('sample-0');await expect(f.getByRole('textbox',{name:'Notes / answer',exact:true})).toHaveValue('QA text saved locally');});

  await check('explicit local test sign-in and isolated real reading-space creation',async()=>{
    await page.goto(`${origin}/s/reading`);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText('Local development · test identity')).toBeVisible();await page.getByRole('button',{name:'Enter local test space'}).click();await expect(page.getByRole('button',{name:'Open the space designer'})).toBeVisible();
    const health=await (await owner.request.get(`${origin}/api/health`)).json();expect(health.database).toBe('pglite');expect(health.planner).toBe('local');
    slug=`qa-modules-${randomUUID().slice(0,8)}`;const created=await post(owner,'/api/spaces',{title:'QA module persistence',slug,prompt:'Create a reading collection for books'});expect(created.status(),await created.text()).toBe(201);
    const state=await snap(slug);const add=state.definition!.appSpec.actions.find(a=>a.type==='record.create')!;const inserted=await post(owner,`/api/spaces/${slug}/actions`,{requestId:randomUUID(),definitionVersion:state.definition!.definitionVersion,actionId:add.id,values:{title:'QA retained book',author:'Local fixture',progress:12}});expect(inserted.status(),await inserted.text()).toBe(200);
    await page.goto(`${origin}/s/${slug}`);await viewer.goto(`${origin}/s/${slug}`);await expect(viewer.getByText('Live and in sync')).toBeVisible();
  });
  await check('Owner adds, configures and drags a module; save persists and anonymous SSE updates',async()=>{
    if(!slug)throw new Error('Space creation failed');const before=await snap(slug);
    await addModule(page,'number-stepper');const f=page.locator('[data-module-type="number-stepper"]');await f.getByRole('button',{name:/^Configure/}).click();await f.getByLabel('Title',{exact:true}).fill('QA adjustable quantity');await f.getByLabel('Module width',{exact:true}).selectOption('4');await f.getByRole('combobox',{name:'Module minimum height',exact:true}).selectOption('320');await f.getByRole('combobox',{name:'Module density',exact:true}).selectOption('compact');await f.getByRole('button',{name:/^Configure/}).click();
    const handle=f.getByRole('button',{name:/Resize/});await handle.scrollIntoViewIfNeeded();const rect=(await handle.boundingBox())!;await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+rect.width/2+110,rect.y+rect.height/2+50,{steps:5});await page.mouse.up();
    const saving=page.waitForResponse(r=>r.url().endsWith('/presentation')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save layout',exact:true}).click();const response=await saving;expect(response.status(),await response.text()).toBe(200);
    const after=await snap(slug);const added=after.definition!.appSpec.components.find(c=>c.type==='number-stepper')!;expect(added.title).toBe('QA adjustable quantity');expect(added.size!.columns).toBeGreaterThan(4);expect(added.size!.minHeight).toBeGreaterThan(320);expect(added.config!.density).toBe('compact');expect(after.records).toEqual(before.records);expect(after.definition!.entitySchema).toEqual(before.definition!.entitySchema);expect(after.definition!.appSpec.actions).toEqual(before.definition!.appSpec.actions);expect(after.stateVersion).toBe(before.stateVersion);
    await expect(viewer.locator('[data-module-type="number-stepper"]')).toContainText('QA adjustable quantity');await expect(viewer.getByRole('button',{name:'Customize layout'})).toHaveCount(0);await expect(viewer.getByRole('button',{name:'Add module ＋',exact:true})).toHaveCount(0);
    await page.reload();await expect(f).toContainText('QA adjustable quantity');expect((await snap(slug)).definition!.appSpec.components.find(c=>c.type==='number-stepper')).toEqual(added);
    await page.screenshot({path:`${out}/owner-persisted-desktop.png`,fullPage:true});await viewer.screenshot({path:`${out}/anonymous-persisted-mobile.png`,fullPage:true});
    await writeFile(`${out}/persistence.json`,JSON.stringify({slug,beforeVersion:before.definition!.definitionVersion,afterVersion:after.definition!.definitionVersion,component:added,recordIds:after.records.map(r=>r.id),recordsPreserved:true,source:'Local test identity + real HTTP/PGlite, no Google/provider'},null,2));
  });
  await check('saved numeric module writes real records and reaches the anonymous client',async()=>{if(!slug)throw new Error('Space creation failed');const f=page.locator('[data-module-type="number-stepper"]');const before=await snap(slug);const c=before.definition!.appSpec.components.find(c=>c.type==='number-stepper')!;const value=Number(before.records[0]!.values[c.valueField!]);await f.getByRole('button',{name:/Increase/}).click();await expect(f.locator('output')).toHaveText(String(value+1));await expect(viewer.locator('[data-module-type="number-stepper"] output')).toHaveText(String(value+1));await page.reload();await expect(f.locator('output')).toHaveText(String(value+1));});
  await check('anonymous numeric write asks for sign-in and leaves real records unchanged',async()=>{const before=await snap(slug);await viewer.locator('[data-module-type="number-stepper"]').getByRole('button',{name:/Increase/}).click();await expect(viewer.getByRole('dialog',{name:'Make this moment yours.'})).toBeVisible();await viewer.keyboard.press('Escape');expect((await snap(slug)).records).toEqual(before.records);});
  await check('concurrent remote layout publication preserves local draft and prevents stale Save',async()=>{
    if(!slug)throw new Error('Space creation failed');await page.getByRole('button',{name:'Customize layout',exact:true}).click();const before=await snap(slug);const components=structuredClone(before.definition!.appSpec.components);components[0]!.title='QA remote layout';const response=await post(owner,`/api/spaces/${slug}/presentation`,{requestId:randomUUID(),baseDefinitionVersion:before.definition!.definitionVersion,components});expect(response.status(),await response.text()).toBe(200);
    await expect(page.getByText('This space changed elsewhere. Your draft is preserved. Cancel and reopen the editor to use the latest layout.')).toBeVisible();await expect(page.getByRole('button',{name:'Save layout',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('heading',{name:'QA remote layout',exact:true})).toBeVisible();await expect(viewer.getByRole('heading',{name:'QA remote layout',exact:true})).toBeVisible();
  });
  await check('saved space fits mobile 320/390 and no browser exceptions occurred',async()=>{for(const width of [320,390]){await viewer.setViewportSize({width,height:844});expect(await viewer.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);}expect(errors).toEqual([]);});
}finally{await writeFile(`${out}/interactions.json`,JSON.stringify({at:new Date().toISOString(),scope:'16 local gallery interactions + real isolated local HTTP/PGlite presentation/record/SSE flows; no cloud/provider calls',checks,errors},null,2));await browser.close();}
console.log('TOTAL',checks.filter(c=>c.status==='pass').length,'/',checks.length);
if(checks.some(c=>c.status==='fail')||errors.length)process.exitCode=1;
