import {chromium} from '@playwright/test';
import {readingDefinition,exampleRecords,COMPONENT_MANIFESTS,type Snapshot,type ComponentSpec,type ToolSpec} from '../../../packages/contracts/src/index';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(8000);
const errors:string[]=[],checks:string[]=[];page.on('pageerror',e=>errors.push(e.message));
const tool:ToolSpec={toolId:'fixture_lookup',toolVersion:1,name:'Find a book',description:'Fixture lookup. No real external request.',endpointId:'fixture',method:'GET',sideEffects:'none',parameters:[{name:'query',type:'string',required:true},{name:'limit',type:'number',required:false}],responseMap:{title:'title'},timeoutMs:1000};
let definition=readingDefinition();definition.entitySchema.fields.push({id:'dates',label:'Completion dates',type:'dates',required:false,public:true,defaultValue:[]});
const extra:ComponentSpec[]=[{id:'list-fixture',type:'list',version:1,title:'List fixture',variant:'dense',fields:['title','author'],actionIds:['edit'],span:'main'},{id:'calendar-fixture',type:'calendar-grid',version:1,title:'Calendar fixture',variant:'default',fields:[],dateField:'dates',actionIds:[],span:'main'},{id:'streak-fixture',type:'streak',version:1,title:'Streak fixture',variant:'default',fields:[],dateField:'dates',actionIds:[],span:'side'},{id:'chart-fixture',type:'chart',version:1,title:'Chart fixture',variant:'default',fields:[],groupBy:'status',actionIds:[],span:'main'},{id:'kanban-fixture',type:'kanban',version:1,title:'Kanban fixture',variant:'default',fields:['title'],groupBy:'status',actionIds:['edit'],span:'main'},{id:'detail-fixture',type:'detail',version:1,title:'Detail fixture',variant:'default',fields:['title','author'],actionIds:['edit'],span:'main'},{id:'tool-fixture',type:'tool-result',version:1,title:'Tool fixture',variant:'default',fields:[],actionIds:['lookup'],toolRef:{toolId:tool.toolId,toolVersion:1},span:'main'}];
if(COMPONENT_MANIFESTS.some(m=>m.id==='camera'&&m.status==='available'))extra.push({id:'camera-fixture',type:'camera',version:1,title:'Camera fixture',variant:'default',fields:[],actionIds:[],span:'main'});
definition.appSpec.actions.push({id:'lookup',type:'tool.invoke',label:'Look up'});definition.appSpec.components.push(...extra);
let snapshot:Snapshot={space:{id:'sp_fixture',slug:'fixture',title:'Fixture coverage',timezone:'America/Vancouver',visibility:'public',participation:'authenticated'},phase:'ready',definition,records:exampleRecords('reading'),stateVersion:1,eventCursor:1,role:'owner',permissions:{canEdit:true,canWrite:true,canUseTools:true,actionIds:['add','edit','remove','lookup']},loginRequiredForWrite:false};let fail=false,empty=false,pendingApproval=false,enabled=false;
await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/session')return route.fulfill({json:{user:{id:'fixture',name:'Fixture'},csrfToken:'fixture',auth:{googleConfigured:false,localDemoAvailable:false},mode:'local'}});if(path==='/api/spaces')return route.fulfill({json:{spaces:[{id:'sp_fixture',slug:'fixture',title:'Fixture coverage',role:'owner'}]}});if(path.endsWith('/snapshot'))return route.fulfill(fail?{status:503,json:{error:{message:'Fixture service unavailable'}}}:{json:{...snapshot,records:empty?[]:snapshot.records}});if(path.endsWith('/events'))return route.fulfill({status:200,contentType:'text/event-stream',body:': fixture only\n\n'});if(path.endsWith('/tools')){if(route.request().method()==='POST'){enabled=true;return route.fulfill({json:{tool:{spec:tool,enabled:true}}})}return route.fulfill({json:{tools:[{spec:tool,enabled:true,verifiedAt:new Date().toISOString(),invocationCount:0}]}})}if(path.endsWith('/invoke'))return route.fulfill({json:{result:{books:[{title:'<script>not executable</script>',author:'Fixture author',year:2026},{title:'Another result',author:'Another author'}]},reused:true}});if(path.endsWith('/proposals'))return route.fulfill({json:{snapshot,proposal:{...definition,source:'local-rules',summary:'Fixture tool approval',capabilityGaps:[],toolProposals:enabled?[]:[tool]},requiresToolApproval:!enabled}});return route.fulfill({status:404,json:{error:{message:'Fixture route not defined'}}})});
try{
 await page.goto('http://localhost:5173/s/fixture');await page.locator('[data-component-id="tool-fixture"]').waitFor();
 for(const manifest of COMPONENT_MANIFESTS.filter(m=>m.status==='available'))if(!await page.locator(`.component-${manifest.id}`).count())throw Error(`Missing component ${manifest.id}`);checks.push(`All ${COMPONENT_MANIFESTS.filter(m=>m.status==='available').length} available manifests rendered from one composed fixture`);
 await page.getByLabel('query *',{exact:true}).fill('systems');await page.getByLabel('limit',{exact:true}).fill('2');await page.getByRole('button',{name:'Find a book',exact:true}).click();await page.getByText('<script>not executable</script>',{exact:true}).waitFor();if(await page.locator('.tool-output script').count())throw Error('Unsafe result HTML');checks.push('Registered tool parameters are independent typed inputs; structured results escape markup');
 await page.getByRole('button',{name:'Open the space designer'}).click();await page.getByRole('textbox',{name:'Describe how to change your space'}).fill('Find a book using a tool');await page.getByRole('button',{name:'Apply changes'}).click();await page.getByRole('button',{name:'Enable tool',exact:true}).waitFor();if(enabled)throw Error('Tool auto-enabled');await page.getByRole('button',{name:'Enable tool',exact:true}).click();await page.getByRole('button',{name:'Enable tool',exact:true}).waitFor({state:'detached'});if(!enabled)throw Error('Tool was not explicitly enabled');checks.push('Tool proposals await explicit Enable tool and re-propose after registration');
 const colors=new Set<string>();for(const skin of ['linen','sage','ink','clay','sand','rose'] as const){snapshot.definition!.appSpec.skin=skin;await page.reload();await page.locator('[data-component-id="books"]').waitFor();colors.add(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--bg')))}if(colors.size!==6)throw Error('Missing skin tokens');checks.push('All six skin palettes have distinct active tokens');
 empty=true;await page.reload();await page.getByRole('heading',{name:'Every story has a first entry.'}).first().waitFor();checks.push('Collection empty state renders');
 fail=true;await page.reload();await page.getByRole('heading',{name:'A little pause.'}).waitFor();await page.getByText('Fixture service unavailable').waitFor();checks.push('Initial API error shows actionable recovery');
 if(errors.length)throw Error(errors.join('\n'));await writeFile('docs/frontend/browser-evidence/components-results.json',JSON.stringify({date:new Date().toISOString(),scope:'Explicitly mocked contracts and network; not real external tool integration evidence',checks,errors},null,2));console.log(JSON.stringify(checks,null,2));
}finally{await browser.close()}
