import {chromium} from '@playwright/test';
import {readingDefinition,habitDefinition,exampleRecords,type Snapshot} from '../../../packages/contracts/src/index';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:'chrome'});
const owner=await browser.newContext({viewport:{width:1440,height:1050}}),guest=await browser.newContext({viewport:{width:1440,height:1050}});
const page=await owner.newPage(),viewer=await guest.newPage();page.setDefaultTimeout(10000);viewer.setDefaultTimeout(10000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));viewer.on('pageerror',e=>errors.push(e.message));const checks:string[]=[];
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.log('PASS',name)}
try{
 await check('Anonymous reading loads from real API; owner orb absent',async()=>{await page.goto('http://localhost:5173/s/reading');await page.getByRole('heading',{name:/Between the lines/i,level:1}).waitFor();if(await page.getByRole('button',{name:'Open the space designer'}).count())throw Error('Visitor orb visible');await page.screenshot({path:'docs/frontend/browser-evidence/reading-desktop.png',fullPage:true})});
 await check('Local test identity explicitly labeled; owner orb becomes visible',async()=>{await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Enter local test space'}).click();await page.getByRole('button',{name:'Open the space designer'}).waitFor()});
 await check('Owner orb opens centrally, receives focus, and preserves draft across close',async()=>{await page.getByRole('button',{name:'Open the space designer'}).click();const command=page.getByRole('textbox',{name:'Describe how to change your space'});await command.fill('Add a rating field and sort by rating');if(!await command.evaluate(e=>e===document.activeElement))throw Error('Text field not focused');await page.screenshot({path:'docs/frontend/browser-evidence/owner-orb.png'});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Open the space designer'}).click();if(await command.inputValue()!=='Add a rating field and sort by rating')throw Error('Draft lost');await page.keyboard.press('Escape')});
 const newTitle=`Browser verification ${Date.now()}`;
 await viewer.goto('http://localhost:5173/s/reading');await viewer.getByRole('heading',{name:/Between the lines/i,level:1}).waitFor();
 await check('Create record persists and second anonymous browser receives real SSE update',async()=>{await page.locator('[data-component-id="add-book"]').getByLabel(/^Title/).fill(newTitle);await page.locator('[data-component-id="add-book"]').getByLabel('Author',{exact:true}).fill('Frontend verification');await page.locator('[data-component-id="add-book"] button[type=submit]').click();await page.getByRole('button',{name:`View ${newTitle}`,exact:true}).waitFor();await viewer.getByRole('button',{name:`View ${newTitle}`,exact:true}).waitFor({timeout:15000});await page.reload();await page.getByRole('button',{name:`View ${newTitle}`,exact:true}).waitFor()});
 await check('Update progress and delete only the browser-created record',async()=>{await page.getByRole('button',{name:`View ${newTitle}`,exact:true}).click();await page.getByLabel('Progress',{exact:true}).fill('73');await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('button',{name:`View ${newTitle}`,exact:true}).click();if(await page.getByLabel('Progress',{exact:true}).inputValue()!=='73')throw Error('Progress not persisted');await page.getByRole('button',{name:'Delete record',exact:true}).click();await page.getByRole('button',{name:'Yes, delete'}).click();await page.getByRole('button',{name:`View ${newTitle}`,exact:true}).waitFor({state:'detached'})});
 await check('Habit tracker renders calendar and real check-in toggles without changing the URL',async()=>{await page.goto('http://localhost:5173/s/habits');await page.getByRole('heading',{name:/Little by little/i,level:1}).waitFor();await page.getByRole('group',{name:/completion calendar/}).waitFor();const btn=page.locator('.checkin-button').first();const before=await btn.getAttribute('aria-pressed');await btn.click();await page.waitForFunction(v=>document.querySelector('.checkin-button')?.getAttribute('aria-pressed')!==v,before);await page.screenshot({path:'docs/frontend/browser-evidence/habits-desktop.png',fullPage:true});await btn.click();await page.waitForFunction(v=>document.querySelector('.checkin-button')?.getAttribute('aria-pressed')===v,before);if(!page.url().endsWith('/s/habits'))throw Error('Check-in changed route')});
 await check('Mobile layout stays within viewport',async()=>{await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/frontend/browser-evidence/habits-mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow')});
 // Explicit fixture-only branch for presentation changes; no model/network integration claim.
 const fixtureContext=await browser.newContext({viewport:{width:1280,height:1000},reducedMotion:'reduce'});const fixture=await fixtureContext.newPage();let definition=readingDefinition();let snapshot:Snapshot={space:{id:'sp_fixture',slug:'fixture',title:'Fixture verification',timezone:'America/Vancouver',visibility:'public',participation:'authenticated'},phase:'ready',definition,records:exampleRecords('reading'),stateVersion:1,eventCursor:1,role:'owner',permissions:{canEdit:true,canWrite:true,canUseTools:true,actionIds:['add','edit','remove']},loginRequiredForWrite:false};
 await fixture.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/session')return route.fulfill({json:{user:{id:'fixture',name:'Fixture'},csrfToken:'fixture',auth:{googleConfigured:false,localDemoAvailable:false},mode:'local'}});if(path==='/api/spaces')return route.fulfill({json:{spaces:[{id:'sp_fixture',slug:'fixture',title:'Fixture verification',role:'owner'}]}});if(path.endsWith('/snapshot'))return route.fulfill({json:snapshot});if(path.endsWith('/events'))return route.fulfill({status:200,contentType:'text/event-stream',body:': fixture\n\n'});if(path.endsWith('/proposals')){definition={...definition,definitionVersion:2,appSpec:{...definition.appSpec,skin:'rose',layout:'flow',components:definition.appSpec.components.map(c=>c.id==='books'?{...c,type:'list',variant:'comfortable'}:c)}};snapshot={...snapshot,definition,eventCursor:2};return route.fulfill({json:{snapshot,proposal:{...definition,source:'local-rules',summary:'Fixture morph verification',capabilityGaps:[]}}})}return route.fulfill({status:404,json:{error:{message:'Fixture route not defined'}}})});
 await check('Fixture-only morph preserves existing record IDs, add-form draft and URL with reduced motion',async()=>{await fixture.goto('http://localhost:5173/s/fixture');await fixture.getByRole('heading',{level:1}).waitFor();const input=fixture.locator('[data-component-id="add-book"]').getByLabel(/^Title/);await input.fill('Unsaved draft survives morph');const ids=await fixture.locator('[data-record-id]').evaluateAll(es=>es.map(e=>e.getAttribute('data-record-id')).sort());await fixture.getByRole('button',{name:'Open the space designer'}).click();await fixture.getByRole('textbox',{name:'Describe how to change your space'}).fill('Show my records as a list');await fixture.getByRole('button',{name:'Apply changes'}).click();await fixture.locator('.record-list').waitFor();if(await input.inputValue()!=='Unsaved draft survives morph')throw Error('Add draft lost');if(JSON.stringify(ids)!==JSON.stringify(await fixture.locator('[data-record-id]').evaluateAll(es=>es.map(e=>e.getAttribute('data-record-id')).sort())))throw Error('Record identity changed');if(!fixture.url().endsWith('/s/fixture'))throw Error('URL changed');await fixture.screenshot({path:'docs/frontend/browser-evidence/fixture-morph-reduced.png',fullPage:true})});
 await fixtureContext.close();
 if(errors.length)throw Error(errors.join('\n'));checks.push('No browser page errors');
 await writeFile('docs/frontend/browser-evidence/results.json',JSON.stringify({date:new Date().toISOString(),checks,scope:'Real local API for auth/CRUD/SSE/habits; explicitly mocked fixture for morph/reduced-motion only',errors},null,2));
}finally{await browser.close()}
