import {useEffect,useState} from 'react';
import {AnimatePresence,MotionConfig,motion} from 'motion/react';
import {ArrowRightIcon,ArrowTopRightIcon,CheckIcon,CopyIcon,ExitIcon,PlusIcon,ReloadIcon,StackIcon} from '@radix-ui/react-icons';
import {COMPONENT_MANIFESTS} from '@livingforma/contracts';
import {useWorkspace} from './lib/client';
import {Renderer} from './components/Renderer';
import {OwnerOrb} from './components/OwnerOrb';
import {AuthDialog} from './components/auth/AuthDialog';
import {Empty,Loading,Modal,Submit} from './components/ui';
import '@fontsource/geist/latin-400.css';
import '@fontsource/geist/latin-500.css';
import '@fontsource/geist/latin-600.css';
import './styles.css';
export default function App(){const w=useWorkspace();const [authOpen,setAuthOpen]=useState(false),[newOpen,setNewOpen]=useState(false),[catalogOpen,setCatalogOpen]=useState(false),[title,setTitle]=useState(''),[prompt,setPrompt]=useState(''),[creating,setCreating]=useState(false),[createError,setCreateError]=useState(''),[copied,setCopied]=useState(false);const skin=w.snapshot?.definition?.appSpec.skin||'linen';useEffect(()=>{document.documentElement.dataset.skin=skin;document.title=w.snapshot?.definition?`${w.snapshot.definition.appSpec.title} — LivingForma`:'LivingForma — A space that grows with you'},[skin,w.snapshot?.definition?.appSpec.title]);const openNew=()=>{if(!w.session?.user){setAuthOpen(true);return}setNewOpen(true)};const hasDate=w.snapshot?.definition?.entitySchema.fields.some(f=>f.type==='dates');
return <MotionConfig reducedMotion="user"><a href="#workspace" className="skip-link">Skip to your space</a><div className="app-shell"><header className="site-header"><a className={`wordmark ${w.snapshot?.permissions.canEdit?'has-orb':''}`} href="/" onClick={e=>{e.preventDefault();if(w.spaces[0])w.navigate(w.spaces[0].slug)}}><span className="brand-symbol" aria-hidden="true">lf</span><span>LivingForma<span className="wordmark-dot">.</span></span></a><nav className="space-nav" aria-label="Your spaces">{w.spaces.slice(0,5).map(space=><a key={space.id} href={`/s/${space.slug}`} className={w.slug===space.slug?'active':''} onClick={e=>{e.preventDefault();w.navigate(space.slug)}}>{w.slug===space.slug&&<motion.span layoutId="space-tab" className="nav-active"/>}<span>{space.title}</span></a>)}</nav><div className="header-actions"><button className="icon-button new-space-button" onClick={openNew} aria-label="Create a new space" title="Create a space"><PlusIcon/></button>{w.session?.user?<><span className="user-avatar" title={w.session.user.name}>{w.session.user.name.slice(0,1).toUpperCase()}</span><button className="icon-button" aria-label="Sign out" title="Sign out" onClick={()=>void w.logout().catch(e=>w.setNotice(e.message))}><ExitIcon/></button></>:<button className="sign-in" onClick={()=>setAuthOpen(true)}>Sign in<ArrowTopRightIcon/></button>}</div></header>
{w.snapshot?.permissions.canEdit&&<OwnerOrb key={w.snapshot.space.id} snapshot={w.snapshot} onPropose={w.propose} onNotice={w.setNotice} csrf={w.session?.csrfToken||null}/>}
<main id="workspace" className="workspace">{w.loading?<Loading/>:w.error&&!w.snapshot?<div className="connection-error"><span className="eyebrow">LET’S TRY THAT AGAIN</span><h1>A little pause.</h1><p>{w.error}</p><button className="button primary" onClick={()=>{void w.refreshIdentity().then(()=>w.refresh()).catch(e=>w.setNotice(e.message))}}>Reconnect<ReloadIcon/></button></div>:w.snapshot?<><motion.div layout className="workspace-heading"><div className="heading-copy"><div className="eyebrow"><span className="small-diamond"/>{hasDate?'SMALL STEPS, MEANINGFUL DAYS':'A LITTLE ROOM FOR WHAT MATTERS'}</div><h1>{w.snapshot.definition?.appSpec.title||w.snapshot.space.title}<span className="title-dot">.</span></h1><p>{w.snapshot.definition?.appSpec.description||'A blank canvas, waiting for your first idea.'}</p><div className="workspace-meta"><span className={`live-status ${w.connection}`}><i/>{w.connection==='live'?'Live and in sync':w.connection==='offline'?'Offline · your last view is safe':'Connecting'}</span><span className="meta-divider"/><span>{w.snapshot.space.visibility==='public'?'An open space':'A private space'}</span><span className="meta-divider"/><span>{w.snapshot.records.length} {w.snapshot.records.length===1?'record':'records'}</span></div></div><div className={`heading-art ${hasDate?'habit-art':'reading-art'}`} aria-hidden="true">{hasDate?<><span className="art-ring one"/><span className="art-ring two"/><span className="art-ring three"/><span className="art-leaf"/><span className="art-caption">GROW AT YOUR OWN PACE</span></>:<><span className="art-book one"/><span className="art-book two"/><span className="art-book three"/><span className="art-caption">MAKE ROOM FOR DISCOVERY</span></>}</div></motion.div><div className="workspace-toolbar"><div><span className="workspace-index">01 /</span><span>{hasDate?'A practice of showing up':'Collected, not forgotten'}</span></div><div><button className="text-button share-button" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{w.setNotice('Copy the address from your browser to share this space.')}}}>{copied?<CheckIcon/>:<CopyIcon/>}{copied?'Link copied':'Share space'}</button>{w.snapshot.permissions.canEdit&&<button className="text-button" onClick={()=>setCatalogOpen(true)}><StackIcon/><span>Building blocks</span></button>}</div></div><Renderer key={w.snapshot.space.id} snapshot={w.snapshot} mutate={w.mutate} onLogin={()=>{if(w.session?.user)w.setNotice('Your account does not have permission to write in this space.');else setAuthOpen(true)}} csrf={w.session?.csrfToken||null}/></>:<Empty title="Make a little space for your life." description="A reading journal, a daily practice, or an idea that’s entirely your own." action={<button className="button primary" onClick={openNew}>Create your first space<ArrowRightIcon/></button>}/>}
</main><footer className="site-footer"><span>Made to change. Built to keep.</span><div>{w.session?.mode==='local'&&<span className="local-badge">Local development</span>}<span>LivingForma</span><span className="footer-mark" aria-hidden="true">✳</span></div></footer></div><AnimatePresence>{w.notice&&<motion.div role="status" aria-live="polite" className="toast" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}}><span className="toast-dot"/>{w.notice}<button className="text-button" onClick={()=>w.setNotice('')} aria-label="Dismiss notification">×</button></motion.div>}</AnimatePresence><AuthDialog open={authOpen} onOpenChange={setAuthOpen} session={w.session} onLocal={w.localLogin}/><Modal open={newOpen} onOpenChange={setNewOpen} title="A new space, a new possibility." description="Start with a blank canvas, or describe an idea to give it a first shape."><form className="record-form" onSubmit={async e=>{e.preventDefault();setCreating(true);setCreateError('');try{await w.createSpace(title,prompt);setNewOpen(false);setTitle('');setPrompt('')}catch(e){setCreateError((e as Error).message)}finally{setCreating(false)}}}><label className="field">Give it a name<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={120}/></label><label className="field">What would you like to keep here? (optional)<textarea rows={4} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="A reading journal with books, authors, and progress…" maxLength={4000}/></label><div className="prompt-presets"><button type="button" onClick={()=>{setTitle('Between the Lines');setPrompt('Create a reading journal with books and reading progress')}}>A reading journal</button><button type="button" onClick={()=>{setTitle('Small Rituals');setPrompt('Create a habit tracker with daily check-ins and a calendar')}}>A daily practice</button></div>{createError&&<p className="form-error" role="alert">{createError}</p>}<Submit busy={creating}>Create my space</Submit></form></Modal><Modal open={catalogOpen} onOpenChange={setCatalogOpen} title="A vocabulary of possibilities." description="Reusable components, composed around your life. Ask the orb to reshape this space." className="catalog-dialog"><div className="catalog-grid">{COMPONENT_MANIFESTS.filter(m=>m.status==='available').map((m,i)=><div className="catalog-item" key={m.id}><span>{String(i+1).padStart(2,'0')}</span><strong>{m.id.replaceAll('-',' ')}</strong><p>{m.description}</p><small>{m.variants.join(' · ')}</small></div>)}</div><div className="palette-list">{['linen','sage','ink','clay','sand','rose'].map(s=><span key={s}><i className={`swatch-${s}`}/>{s}</span>)}</div></Modal></MotionConfig>}
