import {useState,type FormEvent} from 'react';
import type {EntityField,FieldValue} from '@livingforma/contracts';
import {StarFilledIcon,StarIcon} from '@radix-ui/react-icons';
import {Submit} from './ui';
import {useDraft} from '../lib/client';

export function FieldInputs({fields,values,onChange,prefix}:{fields:EntityField[];values:Record<string,unknown>;onChange:(id:string,value:unknown)=>void;prefix:string}){return <>{fields.filter(f=>f.type!=='dates').map(f=>{const value=values[f.id]??f.defaultValue??'';const id=`${prefix}-${f.id}`;return <div className="field" key={f.id}><label htmlFor={id}>{f.label}{f.required&&<span className="required-dot"> *</span>}</label>{f.type==='enum'?<select id={id} data-field-id={f.id} value={String(value)} required={f.required} onChange={e=>onChange(f.id,e.target.value)}><option value="">Choose an option</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:f.type==='boolean'?<label className="checkbox-label"><input id={id} data-field-id={f.id} type="checkbox" checked={!!value} onChange={e=>onChange(f.id,e.target.checked)}/>Complete</label>:f.type==='number'&&f.max===5?<div className="rating-input" role="group" aria-label={f.label}>{[1,2,3,4,5].map(n=><button key={n} type="button" aria-label={`${f.label} ${n} ${n===1?'star':'stars'}`} aria-pressed={Number(value)===n} onClick={()=>onChange(f.id,n)}>{Number(value)>=n?<StarFilledIcon/>:<StarIcon/>}</button>)}<span>{value?String(value):'Unrated'}</span><input className="sr-only" id={id} type="number" tabIndex={-1} value={String(value)} min={f.min} max={f.max} onChange={e=>onChange(f.id,Number(e.target.value))}/></div>:f.type==='text'&&(f.id==='notes'||f.label.toLowerCase().includes('note')||f.label.toLowerCase().includes('description'))?<textarea id={id} data-field-id={f.id} value={String(value)} rows={4} required={f.required} maxLength={10000} onChange={e=>onChange(f.id,e.target.value)}/>:<input id={id} data-field-id={f.id} value={String(value)} required={f.required} min={f.min} max={f.max} type={f.type==='number'?'number':f.type==='date'?'date':'text'} maxLength={f.type==='text'?10000:undefined} onChange={e=>onChange(f.id,f.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/>}</div>})}</>}
export function RecordForm({fields,draftKey,initial,submit,label,onSuccess,disabled=false}:{fields:EntityField[];draftKey:string;initial?:Record<string,FieldValue>;submit:(values:Record<string,FieldValue>)=>Promise<unknown>;label:string;onSuccess?:()=>void;disabled?:boolean}){
 const [values,setValues]=useDraft(draftKey,initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const output:Record<string,FieldValue>={};for(const f of fields){const v=values[f.id]??f.defaultValue;if(v!==undefined)output[f.id]=v as FieldValue}await submit(output);setValues({});onSuccess?.()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={save} className="record-form"><FieldInputs fields={fields} values={values} onChange={(id,value)=>setValues(v=>({...v,[id]:value}))} prefix={draftKey}/>{error&&<p className="form-error" role="alert">{error}</p>}<Submit busy={busy} disabled={disabled}>{label}</Submit></form>
}
