import {useEffect,useState,type CSSProperties,type ComponentType} from 'react';
import {AnimatePresence,LayoutGroup,motion,useReducedMotion} from 'motion/react';
import {ArrowTopRightIcon,CheckIcon,ChevronLeftIcon,ChevronRightIcon,PlusIcon,StarFilledIcon,TrashIcon} from '@radix-ui/react-icons';
import {COMPONENT_MANIFESTS,type ComponentSpec,type DataRecord,type EntityField,type FieldValue,type Mutation,type Snapshot,type RegisteredTool} from '@livingforma/contracts';
import {dayBefore,dayInTimezone,request} from '../lib/client';
import {Empty,Modal,spring} from './ui';
import {RecordForm} from './Fields';
import {CameraScene} from './media/CameraScene';
import {BookResults} from './ToolResults';
export type RuntimeProps={snapshot:Snapshot;mutate:(input:Omit<Mutation,'requestId'|'definitionVersion'>)=>Promise<unknown>;onLogin:()=>void;csrf:string|null};
type ComponentProps=RuntimeProps&{spec:ComponentSpec;onSelect:(record:DataRecord)=>void};
const text=(v:unknown)=>Array.isArray(v)?`${v.length} ${v.length===1?'day':'days'}`:v===undefined||v===null||v===''?'—':String(v);
const hues=['ochre','sage','coal','clay','mist','olive'];
const hash=(s:string)=>[...s].reduce((n,c)=>n+c.charCodeAt(0),0);
function titleField(s:Snapshot){return s.definition!.entitySchema.fields.find(f=>f.type==='text')?.id||s.definition!.entitySchema.fields[0]?.id||'title'}
function action(s:Snapshot,type:string,ids?:string[]){return s.definition?.appSpec.actions.find(a=>a.type===type&&s.permissions.actionIds.includes(a.id)&&(!ids||ids.includes(a.id)))}
function recordsFor({spec,snapshot}:ComponentProps){const records=[...snapshot.records];if(spec.sort)records.sort((a,b)=>{const av=a.values[spec.sort!.field],bv=b.values[spec.sort!.field];const compared=typeof av==='number'&&typeof bv==='number'?av-bv:String(av??'').localeCompare(String(bv??''),'en');return compared*(spec.sort!.direction==='asc'?1:-1)});if(spec.emphasis?.style==='pin')records.sort((a,b)=>Number(b.values[spec.emphasis!.field]===spec.emphasis!.equals)-Number(a.values[spec.emphasis!.field]===spec.emphasis!.equals));return records}
function boundFields(p:ComponentProps){return p.snapshot.definition!.entitySchema.fields.filter(f=>p.spec.fields.includes(f.id))}
function Value({field,value}:{field:EntityField;value:unknown}){if(field.type==='number'&&field.max===5&&value)return <span className="rating-value"><StarFilledIcon/>{String(value)}<span>/ 5</span></span>;return <>{text(value)}</>}

function Collection(p:ComponentProps){const {spec,snapshot,onSelect}=p;const records=recordsFor(p),fields=boundFields(p),heading=titleField(snapshot);const isList=spec.type==='list',check=action(snapshot,'record.checkin',spec.actionIds),today=dayInTimezone(snapshot.space.timezone);const [busy,setBusy]=useState(''),[error,setError]=useState('');return <><div className={`collection ${isList?'record-list':`record-cards variant-${spec.variant}`} ${spec.variant==='dense'?'dense':''}`}><AnimatePresence initial={false} mode="popLayout">{records.map((record,index)=>{const completed=check?.fieldId&&Array.isArray(record.values[check.fieldId])&&(record.values[check.fieldId] as string[]).includes(today);const dateField=snapshot.definition!.entitySchema.fields.find(f=>f.type==='dates');const publicCompleted=dateField&&Array.isArray(record.values[dateField.id])&&(record.values[dateField.id] as string[]).includes(today);const emphasis=spec.emphasis&&record.values[spec.emphasis.field]===spec.emphasis.equals?spec.emphasis.style:'';return <motion.article layout="position" transition={spring} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0,scale:.97}} className={`record-item ${emphasis||''} ${publicCompleted?'completed':''}`} key={record.id} data-record-id={record.id}>
{!isList&&<button className={`book-cover cover-${hues[hash(record.id)%hues.length]}`} onClick={()=>onSelect(record)} aria-label={`View ${text(record.values[heading])}`}><span className="cover-edition">LIVING LIBRARY · {String(index+1).padStart(2,'0')}</span><strong>{text(record.values[heading])}</strong><span className="cover-line"/><span className="cover-author">{text(record.values[fields.find(f=>f.id!==heading&&f.type==='text')?.id||'author'])}</span><span className="cover-mark" aria-hidden="true">LF</span><span className="cover-open"><ArrowTopRightIcon/></span></button>}
{isList&&dateField&&<button className={`checkin-button ${publicCompleted?'checked':''}`} disabled={busy===record.id} aria-label={`${publicCompleted?'Undo today’s check-in':'Complete today'}: ${text(record.values[heading])}`} aria-pressed={!!publicCompleted} onClick={async()=>{if(!snapshot.permissions.canWrite){p.onLogin();return}if(!check)return;setBusy(record.id);setError('');try{await p.mutate({actionId:check.id,recordId:record.id,recordVersion:record.version,values:{}})}catch(e){setError((e as Error).message)}finally{setBusy('')}}}>{publicCompleted?<CheckIcon/>:<span/>}</button>}
<button className="record-info" onClick={()=>onSelect(record)}><span className="record-title">{text(record.values[heading])}</span><span className="record-meta">{fields.filter(f=>f.id!==heading&&!['dates','boolean'].includes(f.type)&&f.id!=='notes'&&f.id!=='progress').slice(0,3).map(f=><span key={f.id} className={f.type==='enum'?'status-chip':''}><Value field={f} value={record.values[f.id]}/></span>)}</span>{!isList&&typeof record.values.progress==='number'&&<span className="card-progress"><span className="progress-track"><span style={{transform:`scaleX(${Math.max(0,Math.min(100,record.values.progress))/100})`}}/></span><span>{record.values.progress}%</span></span>}</button>
{isList&&<span className="list-end">{publicCompleted?'Done for today':dateField?'A little counts, too':<ArrowTopRightIcon/>}</span>}
</motion.article>})}</AnimatePresence></div>{!records.length&&<Empty title="Every story has a first entry." description="Add something, and let this space grow with you."/>}{error&&<p role="alert" className="form-error">{error}</p>}</>}
function FormComponent(p:ComponentProps){const a=action(p.snapshot,'record.create',p.spec.actionIds);return !p.snapshot.permissions.canWrite?<div className="join-in"><p>Every small beginning<br/>deserves a place to live.</p><button className="button secondary" onClick={p.onLogin}>Sign in to add<PlusIcon/></button></div>:a?<RecordForm draftKey={`${p.snapshot.space.id}:${p.spec.id}`} fields={boundFields(p)} label={a.label} submit={values=>p.mutate({actionId:a.id,values})}/>:<p className="inline-note">Your account cannot add records in this space.</p>}
function Counter(p:ComponentProps){const value=p.spec.valueField?p.snapshot.records.reduce((n,r)=>n+(Number(r.values[p.spec.valueField!])||0),0):p.snapshot.records.length;return <div className="metric"><strong>{String(value).padStart(2,'0')}</strong><span>{p.spec.valueField?'in total':'things worth keeping'}</span><div className="metric-glyph" aria-hidden="true"><i/><i/><i/></div></div>}
function Progress(p:ComponentProps){const field=p.spec.valueField,records=p.snapshot.records;const value=records.length&&field?Math.round(records.reduce((n,r)=>n+(Number(r.values[field])||0),0)/records.length):0;return <div className="progress-summary"><div className="progress-orbit" style={{'--progress':`${Math.max(0,Math.min(100,value))*3.6}deg`} as CSSProperties}><strong>{value}<small>%</small></strong></div><div><b>A little further along</b><p>{records.length?'Every page opens up a little more of the world.':'Add a record to begin your progress.'}</p></div></div>}
function Calendar(p:ComponentProps){const today=dayInTimezone(p.snapshot.space.timezone);const [month,setMonth]=useState(today.slice(0,7)),[selected,setSelected]=useState(today);const first=new Date(`${month}-01T12:00:00Z`),days=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate(),offset=(first.getUTCDay()+6)%7;const completed=p.snapshot.records.reduce<Record<string,number>>((all,r)=>{const dates=r.values[p.spec.dateField||''];for(const d of Array.isArray(dates)?dates:typeof dates==='string'?[dates]:[])all[d]=(all[d]||0)+1;return all},{});const change=(n:number)=>{const date=new Date(first);date.setUTCMonth(date.getUTCMonth()+n);setMonth(date.toISOString().slice(0,7))};return <div className="calendar"><div className="calendar-heading"><span>{first.toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'})}</span><div><button className="icon-button" aria-label="Previous month" onClick={()=>change(-1)}><ChevronLeftIcon/></button><button className="text-button" onClick={()=>{setMonth(today.slice(0,7));setSelected(today)}}>Today</button><button className="icon-button" aria-label="Next month" onClick={()=>change(1)}><ChevronRightIcon/></button></div></div><div className="calendar-grid" role="group" aria-label={`${month} completion calendar`}>{['M','T','W','T','F','S','S'].map((d,i)=><span key={i} className="weekday">{d}</span>)}{Array.from({length:offset},(_,i)=><span key={`blank${i}`} aria-hidden="true"/>)}{Array.from({length:days},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`,count=completed[day]||0;return <button key={day} onClick={()=>setSelected(day)} className={`calendar-day ${day===today?'today':''} ${selected===day?'selected':''} ${count?'has-completions':''}`} aria-label={`${day}, ${count} completed ${count===1?'record':'records'}`} aria-pressed={selected===day}><span>{i+1}</span><span className="completion-dots">{Array.from({length:Math.min(count,4)},(_,j)=><i key={j}/>)}</span></button>})}</div><div className="calendar-caption"><span><i/>Small steps, collected</span><span>{selected.slice(5).replace('-',' / ')} · {completed[selected]||0} completed</span></div></div>}
function Streak(p:ComponentProps){const dates=new Set(p.snapshot.records.flatMap(r=>{const d=r.values[p.spec.dateField||''];return Array.isArray(d)?d:typeof d==='string'?[d]:[]}));const today=dayInTimezone(p.snapshot.space.timezone);let cursor=dates.has(today)?today:dayBefore(today),count=0;while(dates.has(cursor)&&count<366){count++;cursor=dayBefore(cursor)}return <div className="streak"><div className="streak-number">{count}<span>{count===1?'day':'days'}</span></div><p>{count?'Small actions, becoming a rhythm of your own.':'Today can be a new first day.'}</p><div className="week-streak">{Array.from({length:7},(_,i)=>dayBefore(today,6-i)).map(d=><div key={d}><span>{['S','M','T','W','T','F','S'][new Date(`${d}T12:00:00Z`).getUTCDay()]}</span><i className={dates.has(d)?'done':''}>{dates.has(d)?<CheckIcon/>:<span/>}</i></div>)}</div></div>}
function Chart(p:ComponentProps){const field=p.snapshot.definition!.entitySchema.fields.find(f=>f.id===p.spec.groupBy);const groups=field?.options||[];return groups.length?<div className="chart">{groups.map(g=>{const rows=p.snapshot.records.filter(r=>r.values[field!.id]===g),value=p.spec.valueField?rows.reduce((sum,r)=>sum+Number(r.values[p.spec.valueField!]||0),0):rows.length;const max=p.spec.valueField?Math.max(...groups.map(v=>p.snapshot.records.filter(r=>r.values[field!.id]===v).reduce((sum,r)=>sum+Number(r.values[p.spec.valueField!]||0),0)),1):Math.max(p.snapshot.records.length,1);return <div className="chart-row" key={g}><span>{g}</span><span className="chart-track"><span style={{transform:`scaleX(${value/max})`}}/></span><b>{value}</b></div>})}</div>:<Empty title="Give your records a category." description="Add a category field to see the shape of your collection."/>}
function Kanban(p:ComponentProps){const field=p.snapshot.definition!.entitySchema.fields.find(f=>f.id===p.spec.groupBy);return <div className="kanban">{field?.options?.map(group=><div className="kanban-column" key={group}><h3>{group}<span>{p.snapshot.records.filter(r=>r.values[field.id]===group).length}</span></h3>{p.snapshot.records.filter(r=>r.values[field.id]===group).map(record=><motion.button layout className="kanban-record" key={record.id} onClick={()=>p.onSelect(record)}>{text(record.values[titleField(p.snapshot)])}<ArrowTopRightIcon/></motion.button>)}</div>)}</div>}
function Detail(p:ComponentProps){const record=recordsFor(p)[0];return record?<div className="detail-summary"><span className="eyebrow">TAKE A CLOSER LOOK</span><h3>{text(record.values[titleField(p.snapshot)])}</h3><dl>{boundFields(p).filter(f=>f.id!==titleField(p.snapshot)).map(f=><div key={f.id}><dt>{f.label}</dt><dd><Value field={f} value={record.values[f.id]}/></dd></div>)}</dl><button className="button secondary" onClick={()=>p.onSelect(record)}>Open this record<ArrowTopRightIcon/></button></div>:<Empty/>}
function ResultValue({value,depth=0}:{value:unknown;depth?:number}){if(value&&typeof value==='object'&&!Array.isArray(value)&&Array.isArray((value as Record<string,unknown>).books))return <BookResults value={value as {books:unknown[]}}/>;if(value===null||value===undefined)return <span className="result-null">Not provided</span>;if(typeof value!=='object')return <span>{typeof value==='boolean'?(value?'Yes':'No'):String(value)}</span>;if(depth>3)return <span className="result-null">Additional nested details</span>;if(Array.isArray(value))return <div className="result-list">{value.slice(0,30).map((item,i)=><div className="result-list-item" key={i}><span className="result-index">{String(i+1).padStart(2,'0')}</span><ResultValue value={item} depth={depth+1}/></div>)}{value.length>30&&<p className="inline-note">Showing the first 30 of {value.length} results.</p>}{!value.length&&<p className="inline-note">No matching results. Try another search.</p>}</div>;return <dl className="result-fields">{Object.entries(value).slice(0,20).map(([key,item])=><div key={key}><dt>{key.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ')}</dt><dd><ResultValue value={item} depth={depth+1}/></dd></div>)}</dl>}
function ToolResult(p:ComponentProps){const [tool,setTool]=useState<RegisteredTool|null>(null),[result,setResult]=useState<unknown>(null),[inputs,setInputs]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');const ref=p.spec.toolRef;
useEffect(()=>{if(!ref||!p.snapshot.permissions.canUseTools)return;let active=true;setLoading(true);request<{tools:RegisteredTool[]}>(`/api/spaces/${p.snapshot.space.slug}/tools`).then(list=>{if(active){setTool(list.tools.find(t=>t.spec.toolId===ref.toolId&&t.spec.toolVersion===ref.toolVersion)||null);setError('')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[ref?.toolId,ref?.toolVersion,p.snapshot.space.slug,p.snapshot.permissions.canUseTools]);
return <div className="tool-result"><p className="inline-note">Look something up with a registered read-only tool. Your records stay intact.</p>{!p.snapshot.permissions.canUseTools?<button className="button secondary" onClick={p.onLogin}>{p.snapshot.role==='visitor'?'Sign in to use this tool':'Tool access is restricted'}</button>:loading?<p role="status" className="inline-note">Loading this tool…</p>:ref&&tool?<form onSubmit={async e=>{e.preventDefault();if(!tool.enabled)return;setBusy(true);setError('');try{const query=Object.fromEntries(tool.spec.parameters.filter(param=>inputs[param.name]!==undefined&&inputs[param.name]!=='').map(param=>[param.name,param.type==='number'?Number(inputs[param.name]):inputs[param.name]]));const data=await request<{result:unknown}>(`/api/spaces/${p.snapshot.space.slug}/tools/${ref.toolId}/invoke`,{method:'POST',body:JSON.stringify({toolVersion:ref.toolVersion,input:query,requestId:crypto.randomUUID()})},p.csrf);setResult(data.result)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}} className="record-form">{tool.spec.parameters.map(param=><label className="field" key={param.name}>{param.name==='q'?'Book title or author':param.name.replaceAll('_',' ')}{param.required?' *':''}<input type={param.type==='number'?'number':'text'} required={param.required} value={inputs[param.name]||''} onChange={e=>setInputs(previous=>({...previous,[param.name]:e.target.value}))}/></label>)}<button type="submit" className="button secondary" disabled={busy||!tool.enabled}>{busy?'Looking it up…':tool.enabled?tool.spec.name:'Waiting for the owner to enable this tool'}<ArrowTopRightIcon/></button></form>:<p className="inline-note">No registered tool is connected yet.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{result!==null&&<div className="tool-output" aria-live="polite"><ResultValue value={result}/></div>}</div>}

function Camera(p:ComponentProps){return <CameraScene slug={p.snapshot.space.slug} csrf={p.csrf} isOwner={p.snapshot.permissions.canEdit}/>};
const registry:Partial<Record<ComponentSpec['type'],ComponentType<ComponentProps>>>={form:FormComponent,cards:Collection,list:Collection,counter:Counter,progress:Progress,'calendar-grid':Calendar,streak:Streak,chart:Chart,kanban:Kanban,detail:Detail,'tool-result':ToolResult,camera:Camera};
export function Renderer(props:RuntimeProps){const {snapshot}=props;const [selected,setSelected]=useState<DataRecord|null>(null),[selectedActions,setSelectedActions]=useState<string[]>([]),[deleting,setDeleting]=useState(false),[deleteConfirm,setDeleteConfirm]=useState(false),[error,setError]=useState('');const reduced=useReducedMotion();if(!snapshot.definition)return <Empty title="A blank canvas, for now." description={snapshot.permissions.canEdit?'Open the orb in the top left, and tell me what you would like to keep here.':'The space owner is preparing something for this space.'}/>;const definition=snapshot.definition,fields=definition.entitySchema.fields,edit=action(snapshot,'record.update',selectedActions),remove=action(snapshot,'record.delete',selectedActions);const current=selected&&snapshot.records.find(r=>r.id===selected.id);const onSelect=(record:DataRecord,ids:string[])=>{setSelectedActions(ids);setSelected(record);setDeleteConfirm(false);setError('')};function render(spec:ComponentSpec){const manifest=COMPONENT_MANIFESTS.find(m=>m.id===spec.type&&m.version===spec.version),Component=registry[spec.type as keyof typeof registry];return <motion.section layout={reduced?false:'position'} transition={spring} className={`runtime-component component-${spec.type}`} key={spec.id} data-component-id={spec.id}><div className="section-heading"><h2>{spec.title||manifest?.description}</h2>{['cards','list'].includes(spec.type)&&<span>{snapshot.records.length} {snapshot.records.length===1?'record':'records'}</span>}</div>{Component&&manifest?.status==='available'&&manifest.variants.includes(spec.variant)?<Component {...props} spec={spec} onSelect={record=>onSelect(record,spec.actionIds)}/>:<Empty title="This building block is on its way." description="This component is not supported yet. The rest of your space is ready to use."/>}</motion.section>}
return <LayoutGroup id={snapshot.space.id}><div className={`runtime-grid layout-${definition.appSpec.layout}`}><div className="runtime-main">{definition.appSpec.components.filter(c=>c.span!=='side').map(render)}</div><aside className="runtime-side">{definition.appSpec.components.filter(c=>c.span==='side').map(render)}</aside></div><Modal open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}} title={selected?text(selected.values[titleField(snapshot)]):'Record'} description="Keep this moment of progress. Leave a little room for the next." className="record-dialog">{selected&&(snapshot.permissions.canWrite&&edit?<RecordForm key={`${snapshot.space.id}:${selected.id}`} draftKey={`${snapshot.space.id}:edit:${selected.id}`} fields={fields} initial={selected.values} label="Save changes" submit={values=>props.mutate({actionId:edit.id,recordId:selected.id,recordVersion:selected.version,values})} onSuccess={()=>setSelected(null)}/>:<><dl className="record-details">{fields.map(f=><div key={f.id}><dt>{f.label}</dt><dd><Value field={f} value={selected.values[f.id]}/></dd></div>)}</dl>{snapshot.role==='visitor'?<button className="button primary" onClick={props.onLogin}>Sign in to update<ArrowTopRightIcon/></button>:<p className="inline-note">You do not have permission to edit this record.</p>}</>)}{selected&&current&&current.version!==selected.version&&<p className="inline-note">This record changed since you opened it. Your draft is safe. Close and reopen to review the latest version before saving.</p>}{remove&&selected&&<div className="delete-area">{deleteConfirm?<><span>Delete this record?</span><button className="text-button danger" disabled={deleting} onClick={async()=>{setDeleting(true);setError('');try{await props.mutate({actionId:remove.id,recordId:selected.id,recordVersion:selected.version,values:{}});setSelected(null)}catch(e){setError((e as Error).message)}finally{setDeleting(false)}}}>{deleting?'Deleting…':'Yes, delete'}</button><button className="text-button" onClick={()=>setDeleteConfirm(false)}>Keep it</button></>:<button className="text-button danger" onClick={()=>setDeleteConfirm(true)}><TrashIcon/>Delete record</button>}</div>}{error&&<p className="form-error" role="alert">{error}</p>}</Modal></LayoutGroup>}
