import * as Dialog from '@radix-ui/react-dialog';
import {Cross2Icon,ArrowRightIcon} from '@radix-ui/react-icons';
import {motion} from 'motion/react';
import type {ReactNode} from 'react';
export const spring={type:'spring',stiffness:270,damping:30} as const;
export function Modal({open,onOpenChange,title,description,children,className='',onCloseAutoFocus}:{open:boolean;onOpenChange:(open:boolean)=>void;title:string;description?:string;children:ReactNode;className?:string;onCloseAutoFocus?:(event:Event)=>void}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={`modal-content ${className}`} onCloseAutoFocus={onCloseAutoFocus}><Dialog.Title className="modal-title">{title}</Dialog.Title><Dialog.Description className="modal-description">{description||'A little space for things worth keeping.'}</Dialog.Description><Dialog.Close className="icon-button modal-close" aria-label="Close"><Cross2Icon/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export function Empty({title='Nothing here, just yet.',description='Leave a little room for what comes next.',action}:{title?:string;description?:string;action?:ReactNode}){return <div className="empty-state"><span className="empty-mark" aria-hidden="true">＋</span><h3>{title}</h3><p>{description}</p>{action}</div>}
export function Loading(){return <div className="workspace-skeleton" role="status" aria-label="Opening your space"><div className="skeleton line small"/><div className="skeleton line large"/><div className="skeleton line medium"/><div className="skeleton-grid">{[1,2,3,4].map(n=><div className="skeleton skeleton-book" key={n}/>)}</div><span className="sr-only">Loading your space</span></div>}
export function Submit({children,busy=false,disabled=false}:{children:ReactNode;busy?:boolean;disabled?:boolean}){return <motion.button type="submit" className="button primary" disabled={busy||disabled} whileTap={{scale:.98}}>{busy?'Saving…':children}<ArrowRightIcon/></motion.button>}
