import {describe,it,expect} from 'vitest';
import {readingDefinition,habitDefinition,validateDefinition,validateEvolution,validateValues} from './index';
describe('accepted contracts',()=>{
  it('validates structurally distinct compositions',()=>{expect(readingDefinition().appSpec.components[0].type).toBe('cards');expect(habitDefinition().appSpec.components.some(c=>c.type==='calendar-grid')).toBe(true);});
  it('rejects unknown properties and bindings',()=>{const d=readingDefinition();d.appSpec.components[0].fields.push('unknown');expect(()=>validateDefinition(d)).toThrow();expect(()=>validateDefinition({...readingDefinition(),script:'alert(1)'})).toThrow();});
  it('allows additive evolution but not field destruction',()=>{const previous=readingDefinition();const next=structuredClone(previous);next.definitionVersion++;next.entitySchema.fields.push({id:'rating',label:'Rating',type:'number',required:false,public:true,min:0,max:5,defaultValue:0});expect(validateEvolution(previous,next)).toEqual(next);next.entitySchema.fields.shift();expect(()=>validateEvolution(previous,next)).toThrow();});
  it('rejects nonnumeric summaries and misplaced tool authority',()=>{const d=readingDefinition();d.appSpec.components.find(c=>c.type==='progress')!.valueField='title';expect(()=>validateDefinition(d)).toThrow(/number field/);const t=readingDefinition();t.appSpec.components[0].toolRef={toolId:'lookup',toolVersion:1};expect(()=>validateDefinition(t)).toThrow(/Only tool results/);const missing=readingDefinition();missing.appSpec.components.push({id:'lookup',type:'tool-result',version:1,variant:'default',fields:[],actionIds:[],span:'full'});expect(()=>validateDefinition(missing)).toThrow(/registered tool reference/);});
  it('rejects invalid calendar and record input',()=>{expect(()=>validateValues(habitDefinition().entitySchema,{title:'Run',dates:['2026-02-30']})).toThrow();expect(()=>validateValues(readingDefinition().entitySchema,{title:'Book',progress:110})).toThrow();});
  it('cannot empty a required field in a partial update',()=>{expect(()=>validateValues(readingDefinition().entitySchema,{title:''},true)).toThrow();expect(validateValues(readingDefinition().entitySchema,{progress:20},true)).toEqual({progress:20});});
  it('rejects incompatible action wiring and unsafe additive requirements',()=>{const d=readingDefinition();d.appSpec.components[1].actionIds=['remove'];expect(()=>validateDefinition(d)).toThrow();const next=readingDefinition();next.definitionVersion=2;next.entitySchema.fields.push({id:'new',label:'Required',type:'text',required:true,public:true});expect(()=>validateEvolution(readingDefinition(),next)).toThrow();});
});
