/** LF-202: actual Chrome + local sample playground. No model or production calls. */
import {chromium,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const origin=process.env.MODULE_TEST_ORIGIN??'http://localhost:5173';
const evidence='docs/memory/handoffs/agent/LF-202-a903b374';
const types=['flashcards','quiz','random-picker','pomodoro','stopwatch','breathing-guide','calculator','unit-converter','search-panel','filter-panel','tag-cloud','text-reader','word-counter','markdown-viewer','link-directory','recipe-scaler'];
const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1440,height:1000}});
page.setDefaultTimeout(6000);
const errors:string[]=[],checks:{name:string;status:'pass'|'fail';detail?:string}[]=[];
page.on('pageerror',e=>errors.push(e.message));
const module=(type:string)=>page.locator(`[data-module-type="${type}"]`);
async function open(type:string){await page.goto(`${origin}/modules?type=${type}&columns=3`);await module(type).waitFor();return module(type);}
async function check(name:string,run:()=>Promise<void>){try{await run();checks.push({name,status:'pass'});console.log('PASS',name);}catch(e){checks.push({name,status:'fail',detail:(e as Error).message});console.log('FAIL',name,(e as Error).message);}}
try{
  for(const width of [320,1440])for(const type of types)await check(`${type}: ${width}px viewport / 3-column container`,async()=>{
    await page.setViewportSize({width,height:950});const tile=await open(type);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
    expect(await tile.locator('.module-content').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
    expect(await tile.locator('button').evaluateAll(nodes=>nodes.every(node=>node.getBoundingClientRect().height>=39))).toBe(true);
  });
  await page.setViewportSize({width:390,height:900});
  await check('Flashcards: keyboard flip and next card',async()=>{const tile=await open('flashcards'),card=tile.getByRole('button',{name:'Question; flip to answer',exact:true});await expect(card).toContainText('Read one chapter');await card.focus();await page.keyboard.press('Enter');await expect(tile.getByRole('button',{name:'Answer; flip to question'})).toContainText('A small step, repeated with care.');await tile.getByRole('button',{name:'Next card'}).click();await expect(tile.getByRole('button',{name:'Question; flip to answer',exact:true})).toContainText('Sketch a new idea');});
  await check('Quiz: correct answer, score, next and restart',async()=>{const tile=await open('quiz');await tile.getByLabel('Your answer').fill('a SMALL step, repeated with care.');await tile.getByRole('button',{name:'Check answer'}).click();await expect(tile).toContainText('Correct.');await expect(tile).toContainText('1 correct / 1 answered');await tile.getByRole('button',{name:'Next question'}).click();await expect(tile.getByLabel('Your answer')).toHaveValue('');await tile.getByRole('button',{name:'Restart'}).click();await expect(tile).toContainText('0 correct / 0 answered');});
  await check('Random picker: no-repeat pool exhausts and resets',async()=>{const tile=await open('random-picker');await tile.getByLabel('Avoid repeats').check();const selected=new Set<string>();for(let i=0;i<6;i++){await tile.getByRole('button',{name:'Pick a record'}).click();selected.add(await tile.locator('.tool-pick').innerText());}expect(selected.size).toBe(6);await expect(tile.getByRole('button',{name:'Pick a record'})).toBeDisabled();await tile.getByRole('button',{name:'Reset pool'}).click();await expect(tile).toContainText('6 choices available');});
  await check('Calculator: arithmetic, divide-zero and clear',async()=>{const tile=await open('calculator');await tile.getByLabel('First number').fill('12');await tile.getByLabel('Second number').fill('5');await tile.getByRole('button',{name:'Calculate',exact:true}).click();await expect(tile.locator('output')).toContainText('17');await tile.getByLabel('Operation').selectOption('÷');await tile.getByLabel('Second number').fill('0');await tile.getByRole('button',{name:'Calculate',exact:true}).click();await expect(tile.locator('output')).toHaveText('Cannot divide by zero.');await tile.getByRole('button',{name:'Clear',exact:true}).click();await expect(tile.getByLabel('First number')).toHaveValue('');});
  await check('Unit converter: real length and temperature conversion',async()=>{const tile=await open('unit-converter');await expect(tile.locator('output')).toHaveText('3.2808 Feet');await tile.getByLabel('Measurement').selectOption('Temperature');await tile.getByLabel('Amount').fill('0');await expect(tile.locator('output')).toHaveText('32 Fahrenheit');await tile.getByRole('button',{name:'Swap units'}).click();await expect(tile.locator('output')).toHaveText('-17.7778 Celsius');});
  await check('Search and enum filters change the shared tag-cloud view',async()=>{await page.goto(`${origin}/modules`);await page.locator('.showcase-controls').getByRole('combobox',{name:/^Category/}).selectOption('Discovery');await module('tag-cloud').waitFor();await expect(module('tag-cloud').locator('.tool-records li')).toHaveCount(6);await module('search-panel').getByLabel('Search this collection').fill('quiet');await expect(module('tag-cloud').locator('.tool-records li')).toHaveCount(1);await expect(module('search-panel')).toContainText('1 / 6 records shown');await module('filter-panel').getByRole('combobox',{name:/^Category/}).selectOption('Learn');await expect(module('tag-cloud').locator('.tool-records li')).toHaveCount(0);await module('filter-panel').getByRole('button',{name:'Clear all filters'}).click();await expect(module('tag-cloud').locator('.tool-records li')).toHaveCount(6);});
  await check('Tag cloud selects and clears a category',async()=>{const tile=await open('tag-cloud');await tile.getByRole('button',{name:/^Learn\s*2$/}).click();await expect(tile.locator('.tool-records li')).toHaveCount(2);await tile.getByRole('button',{name:/^Learn\s*2$/}).click();await expect(tile.locator('.tool-records li')).toHaveCount(6);});
  await check('Reader size is adjustable and source record can change',async()=>{const tile=await open('text-reader');await tile.getByRole('slider').fill('26');await expect(tile.locator('article')).toHaveCSS('font-size','26px');await tile.getByRole('combobox',{name:'Choose record'}).selectOption('sample-2');await expect(tile.locator('article')).toHaveText('Leave a little room to breathe.');await page.screenshot({path:`${evidence}-reader-mobile.png`,fullPage:true});});
  await check('Word counter handles Unicode and remains a local draft',async()=>{const tile=await open('word-counter');await tile.getByLabel('Text to measure').fill('Hello world\n\nSecond paragraph');await expect(tile.locator('.tool-stat-grid').locator('div').filter({hasText:'Words'})).toContainText('4');await expect(tile.locator('.tool-stat-grid').locator('div').filter({hasText:'Paragraphs'})).toContainText('2');await page.reload();await expect(module('word-counter').getByLabel('Text to measure')).not.toHaveValue('Hello world\n\nSecond paragraph');});
  await check('Markdown renders headings and escapes HTML/unsafe links',async()=>{const tile=await open('markdown-viewer');await tile.getByRole('combobox',{name:'Choose record'}).selectOption('sample-1');await expect(tile.locator('article h3')).toHaveText('Begin with curiosity');await page.getByRole('button',{name:'Customize layout'}).click();await tile.getByRole('button',{name:'Configure markdown viewer',exact:true}).click();await tile.getByLabel('text',{exact:true}).fill('# Safe\n<script>window.LF_UNSAFE=true</script>\n[bad](javascript:alert)\n[good](https://example.com/)');await page.getByRole('button',{name:'Save layout'}).click();await expect(tile.locator('article')).toContainText('<script>window.LF_UNSAFE=true</script>');await expect(tile.locator('article a')).toHaveCount(1);await expect(tile.locator('article a')).toHaveAttribute('href','https://example.com/');expect(await page.evaluate(()=>('LF_UNSAFE' in window))).toBe(false);});
  await check('Link directory filters and only exposes safe web links',async()=>{const tile=await open('link-directory');await expect(tile.locator('.tool-links a')).toHaveCount(6);await tile.getByLabel('Find a link').fill('quiet');await expect(tile.locator('.tool-links a')).toHaveCount(1);await expect(tile.locator('.tool-links a')).toHaveAttribute('rel','noopener noreferrer');await expect(tile.locator('.tool-links a')).toHaveAttribute('href','https://example.com/');});
  await check('Recipe scaler changes numeric preview, not stored quantities',async()=>{const tile=await open('recipe-scaler');await expect(tile.locator('.tool-ingredients li').first()).toContainText('24');await tile.getByRole('button',{name:'2×',exact:true}).click();await expect(tile.locator('.tool-ingredients li').first()).toContainText('48');await tile.getByLabel('Recipe multiplier').fill('0');await expect(tile.getByRole('alert')).toHaveText('Choose a multiplier between 0.01 and 100.');await page.reload();await expect(module('recipe-scaler').locator('.tool-ingredients li').first()).toContainText('24');});
  await check('Stopwatch timestamp, pause, laps and reset with controlled browser clock',async()=>{const tile=await open('stopwatch');await page.clock.install();await tile.getByRole('button',{name:'Start',exact:true}).click();await page.clock.fastForward(3200);await expect(tile.locator('output')).toContainText('00:03');await tile.getByRole('button',{name:'Record lap'}).click();await expect(tile.locator('.tool-laps li')).toHaveCount(1);await tile.getByRole('button',{name:'Pause',exact:true}).click();const stopped=await tile.locator('output').innerText();await page.clock.fastForward(4000);expect(await tile.locator('output').innerText()).toBe(stopped);await tile.getByRole('button',{name:'Reset',exact:true}).click();await expect(tile.locator('output')).toContainText('00:00');});
  await check('Pomodoro completes, pauses and resets explicitly',async()=>{const tile=await open('pomodoro');await page.getByRole('button',{name:'Customize layout'}).click();await tile.getByRole('button',{name:'Configure pomodoro',exact:true}).click();await tile.getByLabel('duration Seconds',{exact:true}).fill('4');await page.getByRole('button',{name:'Save layout'}).click();await tile.getByRole('button',{name:'Start',exact:true}).click();await page.clock.fastForward(4500);await expect(tile.locator('p[role=status]')).toHaveText('Session complete. Take a moment.');await expect(tile.getByRole('button',{name:'Start',exact:true})).toBeDisabled();await tile.getByRole('button',{name:'Reset',exact:true}).click();await expect(tile.locator('output')).toHaveText('00:04');});
  await check('Breathing phase starts only on click and reduced-motion disables transitions',async()=>{const tile=await open('breathing-guide');await page.emulateMedia({reducedMotion:'reduce'});await expect(tile.getByRole('status')).toHaveText('Find your rhythm');await tile.getByRole('button',{name:'Start breathing'}).click();await expect(tile.getByRole('status')).toHaveText('Breathe in');await page.clock.fastForward(4500);await expect(tile.getByRole('status')).toHaveText('Hold gently');await expect(tile.locator('.tool-breath-orbit')).toHaveCSS('transition-property','none');await tile.getByRole('button',{name:'Stop & reset'}).click();await expect(tile.getByRole('status')).toHaveText('Find your rhythm');});
  await check('All three timers clear intervals on pause and module unmount',async()=>{
    const cleanup=await browser.newPage({viewport:{width:1440,height:1000}});
    await cleanup.addInitScript(()=>{const state=window as unknown as {__lfTimers:Set<number>};state.__lfTimers=new Set();const set=window.setInterval.bind(window),clear=window.clearInterval.bind(window);window.setInterval=((handler:TimerHandler,timeout?:number,...args:unknown[])=>{const id=set(handler,timeout,...args);state.__lfTimers.add(id);return id;}) as typeof window.setInterval;window.clearInterval=((id?:number)=>{if(id!==undefined)state.__lfTimers.delete(id);clear(id);}) as typeof window.clearInterval;});
    const count=()=>cleanup.evaluate(()=>(window as unknown as {__lfTimers:Set<number>}).__lfTimers.size);
    try{for(const type of ['pomodoro','stopwatch','breathing-guide']){
      await cleanup.goto(`${origin}/modules?type=${type}`);const tile=cleanup.locator(`[data-module-type="${type}"]`);await tile.waitFor();const baseline=await count();
      await tile.getByRole('button',{name:type==='breathing-guide'?'Start breathing':'Start',exact:true}).click();await expect.poll(count).toBe(baseline+1);
      await tile.getByRole('button',{name:'Pause',exact:true}).click();await expect.poll(count).toBe(baseline);
      await tile.getByRole('button',{name:type==='breathing-guide'?'Start breathing':'Start',exact:true}).click();await expect.poll(count).toBe(baseline+1);
      await cleanup.getByLabel('Find a module').fill('calculator');await cleanup.locator('[data-module-type="calculator"]').waitFor();await expect.poll(count).toBe(baseline);
    }}finally{await cleanup.close();}
  });
  await check('No browser runtime errors',async()=>{expect(errors).toEqual([]);});
}finally{await writeFile(`${evidence}-browser.json`,JSON.stringify({date:new Date().toISOString(),scope:'Real Chrome, local sample playground; clock-controlled timer checks. No live providers, paid services, production state or real user data.',checks,errors},null,2));await browser.close();}
if(checks.some(c=>c.status==='fail'))process.exitCode=1;
