import {afterAll,beforeAll,expect,it,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {componentSchema,readingDefinition,toolSpecSchema,validateDefinition,validateGeneratedTool,type GeneratedToolSpec,type GenerationJob,type Proposal,type SiteGenerator} from '@livingforma/contracts';
import {createDatabase,type SpaceState} from '@livingforma/db';
import {buildApp,type AppOptions} from './app';
import {createGeneratedToolAdapter} from './generated-tool-runtime';
const origin='http://localhost:5173',runtime=createGeneratedToolAdapter();
const spec=():GeneratedToolSpec=>validateGeneratedTool({kind:'code-js-v1',toolId:'score',toolVersion:1,name:'Custom score',description:'Multiply any number by seven.',source:'function run(input, api) { return {answer: input.value * 7}; }',inputSchema:{type:'object',properties:{value:{type:'number'}},required:['value'],additionalProperties:false},outputSchema:{type:'object',properties:{answer:{type:'number'}},required:['answer'],additionalProperties:false},sideEffects:'none',capabilities:{publicRecordFields:[],connectors:[]},tests:[{name:'Positive',input:{value:3},expected:{answer:21}},{name:'Negative',input:{value:-2},expected:{answer:-14}}]});
type Context=Awaited<ReturnType<typeof buildApp>>;let ctx:Context,owner:Record<string,string>,participant:Record<string,string>,ip=10;
let generator:SiteGenerator=async()=>{throw new Error('Fixture not configured.');};let toolGenerator:NonNullable<AppOptions['toolCodeGenerator']>=async()=>({spec:spec(),reuse:null,source:'gemini',summary:'Fixture proposal'});
async function login(context=ctx,persona='owner'){const r=await context.app.inject({method:'POST',url:'/auth/local',headers:{origin},payload:{persona}});expect(r.statusCode,r.body).toBe(200);return {origin,cookie:String(r.headers['set-cookie']).split(';')[0]!,'x-csrf-token':r.json().csrfToken};}
function generated(current=readingDefinition(),tool=spec()):Proposal{return {entitySchema:current.entitySchema,appSpec:{...current.appSpec,actions:[...current.appSpec.actions,{id:'run_score',type:'tool.invoke',label:'Calculate'}],components:[componentSchema.parse({id:'custom',type:'generated-site',version:1,fields:['title'],actionIds:['run_score'],toolBindings:[{actionId:'run_score',toolId:tool.toolId,toolVersion:tool.toolVersion,kind:'generated'}]})],generated:{format:'html-v1',bridgeVersion:1,html:'<main>Custom calculator</main>',css:'body{font-family:system-ui}',js:'lf.reportReady();',assetIds:[]}},codeToolProposals:[tool],summary:'A custom calculator',source:'gemini',capabilityGaps:[]};}
async function space(context=ctx,bind=true){const definition=readingDefinition();if(bind){const p=generated(definition);definition.appSpec=p.appSpec;}definition.entitySchema.fields.push({id:'secret',type:'text',label:'Private',required:false,public:false,defaultValue:'PRIVATE_DEFAULT'});const now=new Date().toISOString(),state:SpaceState={space:{id:randomUUID(),slug:`tools-${randomUUID().slice(0,8)}`,title:'Tool fixture',timezone:'UTC',visibility:'public',participation:'authenticated'},ownerId:'user-local-owner',members:[],definition,records:[{id:'record_kept',version:1,values:{title:'Public book',secret:'PRIVATE_RECORD',progress:0,status:'To read'},createdAt:now,updatedAt:now}],stateVersion:1,eventCursor:0};await context.store.insertSpace(state);return state;}
const url=(state:SpaceState,suffix='')=>`/api/spaces/${state.space.slug}/code-tools${suffix}`;
async function register(state:SpaceState,tool=spec(),enable=true,context=ctx,headers=owner){return context.app.inject({method:'POST',url:url(state),remoteAddress:`127.0.0.${++ip}`,headers,payload:{spec:tool,enable}});}
const invocation=(requestId=randomUUID())=>({requestId,definitionVersion:1,componentId:'custom',actionId:'run_score',toolVersion:1,input:{value:8}});
async function invoke(state:SpaceState,body=invocation(),context=ctx,headers=owner){return context.app.inject({method:'POST',url:url(state,'/score/invoke'),remoteAddress:`127.0.0.${++ip}`,headers,payload:body});}
beforeAll(async()=>{process.env.ENABLE_LOCAL_DEMO='true';process.env.NODE_ENV='test';ctx=await buildApp({db:await createDatabase(),origin,localDemo:true,siteGenerator:input=>generator(input),toolCodeGenerator:input=>toolGenerator(input)});owner=await login();participant=await login(ctx,'participant');},30000);
afterAll(async()=>{await ctx?.app.close();});
it('requires Owner and Origin/CSRF, checks fixtures, preserves immutable versions and replays bounded results',async()=>{
 const state=await space();for(const [headers,status] of [[{},401],[participant,403],[{...owner,origin:'https://other.example'},403],[{...owner,'x-csrf-token':'wrong'},403]] as const)expect((await register(state,spec(),true,ctx,headers)).statusCode).toBe(status);
 const bad=spec();bad.tests[1]!.expected={answer:0};expect((await register(state,bad)).statusCode).toBe(422);expect(await ctx.store.getCodeTools(state.space.id)).toEqual([]);
 const r=await register(state);expect(r.statusCode,r.body).toBe(200);expect(r.json().tool.testReport.ok).toBe(true);expect(r.json().tool.sourceDigest).toMatch(/^[a-f0-9]{64}$/);
 const changed=spec();changed.source='function run(input, api){return {answer:0}}';expect((await register(state,changed)).statusCode).toBe(409);
 const body=invocation(),first=await invoke(state,body);expect(first.statusCode,first.body).toBe(200);expect(first.json()).toMatchObject({result:{answer:56},reused:false});expect((await invoke(state,body)).json()).toEqual(first.json());expect((await ctx.store.getCodeTools(state.space.id))[0]!.invocationCount).toBe(1);
 expect((await invoke(state,{...body,input:{value:9}})).statusCode).toBe(409);expect((await invoke(state)).json().reused).toBe(true);expect((await invoke(state,{...invocation(),definitionVersion:9})).statusCode).toBe(409);expect((await invoke(state,{...invocation(),actionId:'unbound'})).statusCode).toBe(403);expect((await invoke(state,invocation(),ctx,participant)).statusCode).toBe(403);
 expect((await ctx.app.inject({url:url(state)})).statusCode).toBe(401);expect((await ctx.app.inject({url:url(state),headers:owner})).json().tools[0].spec.source).toBe(spec().source);
 const snapshot=(await ctx.app.inject({url:`/api/spaces/${state.space.slug}/snapshot`})).json();expect(()=>validateDefinition(snapshot.definition)).not.toThrow();expect(JSON.stringify(snapshot)).not.toContain('PRIVATE_');expect(snapshot.definition.appSpec.components[0].toolBindings).toBeUndefined();
 expect((await register(state,spec(),false)).statusCode).toBe(200);expect((await invoke(state)).statusCode).toBe(403);
},20000);
it('brokers only declared public fields from the current space',async()=>{
 const state=await space(),tool=spec();tool.capabilities.publicRecordFields=['title'];tool.source='async function run(input,api){const rows=await api.readRecords({fields:["title"],limit:10});return {answer:rows.length+rows[0].values.title.length};}';for(const f of tool.tests){f.records=[{id:'a',version:1,values:{title:'Test'}}];f.expected={answer:5};}expect((await register(state,tool)).statusCode).toBe(200);expect((await invoke(state)).json().result).toEqual({answer:12});const denied=spec();denied.toolVersion=2;denied.capabilities.publicRecordFields=['secret'];expect((await register(state,denied)).statusCode).toBe(422);
},10000);
it('proposes and tests new tools without enabling them and reuses enabled exact versions',async()=>{
 const state=await space();toolGenerator=async input=>{expect(JSON.stringify(input)).not.toContain('PRIVATE_');return {spec:spec(),reuse:null,source:'gemini',summary:'A new tool'};};const proposed=await ctx.app.inject({method:'POST',url:url(state,'/proposals'),headers:owner,payload:{prompt:'Create a custom score tool'}});expect(proposed.statusCode,proposed.body).toBe(200);expect(proposed.json().testReport.ok).toBe(true);expect(await ctx.store.getCodeTools(state.space.id)).toEqual([]);await register(state);toolGenerator=async input=>{expect(input.registeredTools[0]).not.toHaveProperty('source');expect(input.registeredTools[0]).not.toHaveProperty('tests');return {spec:null,reuse:{toolId:'score',toolVersion:1},source:'gemini',summary:'Reuse'};};expect((await ctx.app.inject({method:'POST',url:url(state,'/proposals'),headers:owner,payload:{prompt:'Reuse the score'}})).json().reuse).toEqual({toolId:'score',toolVersion:1});
},10000);
it('tests code candidates outside transactions, persists real outline/tool reports and publishes registry plus definition atomically',async()=>{
 const state=await space(ctx,false);generator=async input=>{input.onProgress?.({stage:'writing',message:'Actual checkpoint',ui:{version:1,title:'Score',layout:'flow',sections:[{id:'main',kind:'form',label:'Calculator'}]}});return generated(input.current!);};const start=await ctx.app.inject({method:'POST',url:`/api/spaces/${state.space.slug}/generations`,headers:owner,payload:{prompt:'A custom score website',baseDefinitionVersion:1,requestId:randomUUID()}});expect(start.statusCode,start.body).toBe(202);let job:GenerationJob=start.json();
 await vi.waitFor(async()=>{job=(await ctx.app.inject({url:`/api/spaces/${state.space.slug}/generations/${job.id}`,headers:owner})).json();expect(job.stage,job.error).toBe('preview');},{timeout:10000});expect(job.toolReports?.[0]?.report.ok).toBe(true);expect(job.events.some(e=>e.ui?.sections[0]?.kind==='form')).toBe(true);expect(job.events.filter(e=>e.tool).map(e=>e.tool!.phase)).toEqual(['testing','ready']);expect(await ctx.store.getCodeTools(state.space.id)).toEqual([]);expect((await invoke(state)).statusCode).toBe(403);
 const prefix=`/api/spaces/${state.space.slug}/generations/${job.id}`;await ctx.app.inject({method:'POST',url:`${prefix}/preview`,headers:owner,payload:{sourceRevision:1,ok:true,errors:[]}});const published=await ctx.app.inject({method:'POST',url:`${prefix}/publish`,headers:owner,payload:{sourceRevision:1,requestId:randomUUID()}});expect(published.statusCode,published.body).toBe(200);expect((await ctx.store.getCodeTools(state.space.id))[0]!.enabled).toBe(true);expect((await invoke(state,{...invocation(),definitionVersion:2})).json().result).toEqual({answer:56});expect((await ctx.store.getSpace(state.space.slug))!.records).toEqual(state.records);
},15000);
it('shares one repair between tool fixture failures and browser diagnostics',async()=>{
 const state=await space(ctx,false);let attempts=0;generator=async input=>{const tool=spec();if(++attempts===1)tool.tests[0]!.expected={answer:0};else expect(input.repair?.errors[0]).toContain('fixture');return generated(input.current!,tool);};const start=await ctx.app.inject({method:'POST',url:`/api/spaces/${state.space.slug}/generations`,headers:owner,payload:{prompt:'A score tool with tests',baseDefinitionVersion:1,requestId:randomUUID()}});let job:GenerationJob=start.json();await vi.waitFor(async()=>{job=(await ctx.app.inject({url:`/api/spaces/${state.space.slug}/generations/${job.id}`,headers:owner})).json();expect(job.stage,job.error).toBe('preview');},{timeout:10000});expect(attempts).toBe(2);expect(job.repairCount).toBe(1);expect(job.sourceRevision).toBe(2);const failed=await ctx.app.inject({method:'POST',url:`/api/spaces/${state.space.slug}/generations/${job.id}/preview`,headers:owner,payload:{sourceRevision:2,ok:false,errors:['The browser check failed.']}});expect(failed.json().stage).toBe('failed');expect(await ctx.store.getCodeTools(state.space.id)).toEqual([]);expect((await ctx.store.getSpace(state.space.slug))!.definition!.definitionVersion).toBe(1);
},15000);
it('does not commit a late result after logout, nor repeat pending or interrupted invocations',async()=>{
 let entered=false,resolve!:(value:{answer:number})=>void;const local=await buildApp({db:await createDatabase(),origin,localDemo:true,generatedToolAdapter:{...runtime,invoke:async()=>{entered=true;return new Promise(r=>{resolve=r;});}}});try{const headers=await login(local),state=await space(local);await register(state,spec(),true,local,headers);const body=invocation(),pending=invoke(state,body,local,headers);await vi.waitFor(()=>expect(entered).toBe(true));expect((await invoke(state,body,local,headers)).statusCode).toBe(409);expect((await local.app.inject({method:'POST',url:'/auth/logout',headers})).statusCode).toBe(200);resolve({answer:56});expect([401,409]).toContain((await pending).statusCode);const fresh=await login(local);expect((await invoke(state,body,local,fresh)).statusCode).toBe(409);expect((await local.store.getCodeTools(state.space.id))[0]!.invocationCount).toBe(0);}finally{await local.app.close();}
},15000);
it('persists registry and replay on disk and marks interrupted reservations honestly after restart',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'lf-code-tools-'));let local:Context|undefined;try{local=await buildApp({db:await createDatabase({dataDir:directory}),origin,localDemo:true});const headers=await login(local),state=await space(local);await register(state,spec(),true,local,headers);const body=invocation(),first=await invoke(state,body,local,headers);expect(first.statusCode,first.body).toBe(200);await local.store.db.query('INSERT INTO lf_code_tool_requests(space_id,user_id,request_id,data) VALUES($1,$2,$3,$4)',[state.space.id,'user-local-owner',randomUUID(),JSON.stringify({digest:'fixture',status:'pending',startedAt:1})]);await local.app.close();local=await buildApp({db:await createDatabase({dataDir:directory}),origin,localDemo:true});expect((await invoke(state,body,local,headers)).json()).toEqual(first.json());expect((await local.store.getCodeTools(state.space.id))[0]!.invocationCount).toBe(1);const rows=await local.store.db.query<{data:{status:string}}>('SELECT data FROM lf_code_tool_requests WHERE data->>\'digest\'=$1',['fixture']);expect(rows.rows[0]!.data.status).toBe('failed');}finally{await local?.app.close();await rm(directory,{recursive:true,force:true});}
},25000);
it('uses only enabled catalog connectors and validates exact legacy bindings before and after asynchronous calls',async()=>{
 let calls=0,delayed=false,resolve!:(value:Record<string,unknown>)=>void;
 const local=await buildApp({db:await createDatabase(),origin,localDemo:true,tools:{validate:input=>toolSpecSchema.parse(input),test:async()=>({ok:true,message:'Offline connector fixture.'}),invoke:async()=>{calls++;return delayed?new Promise(r=>{resolve=r;}):{factor:2};}}});
 try{const headers=await login(local),state=await space(local),catalog=toolSpecSchema.parse({toolId:'fixture_rate',toolVersion:1,name:'Fixture rate',description:'Offline only.',endpointId:'fixture_rate',method:'GET',sideEffects:'none',parameters:[],responseMap:{factor:'factor'},timeoutMs:2000});
  const enabled=await local.app.inject({method:'POST',url:`/api/spaces/${state.space.slug}/tools`,headers,payload:{spec:catalog,enable:true}});expect(enabled.statusCode,enabled.body).toBe(200);
  const tool=spec();tool.source='async function run(input,api){const data=await api.callConnector({toolId:"fixture_rate",toolVersion:1,input:{}});return {answer:input.value*data.factor}}';tool.capabilities.connectors=[{toolId:'fixture_rate',toolVersion:1}];for(const f of tool.tests){f.expected={answer:Number(f.input.value)*2};f.connectorResults=[{toolId:'fixture_rate',toolVersion:1,input:{},result:{factor:2}}];}
  expect((await register(state,tool,true,local,headers)).statusCode).toBe(200);expect(calls).toBe(0);expect((await invoke(state,invocation(),local,headers)).json().result).toEqual({answer:16});expect(calls).toBe(1);
  const registered=(await local.store.getTool(state.space.id,'fixture_rate',1))!;registered.enabled=false;await local.store.putTool(state.space.id,registered);expect((await invoke(state,invocation(),local,headers)).statusCode).toBe(422);expect(calls).toBe(1);registered.enabled=true;await local.store.putTool(state.space.id,registered);
  await local.store.db.transaction(async tx=>{const current=(await local.store.getSpace(state.space.slug,tx,true))!;current.definition!.appSpec.components[0]!.toolBindings=[{actionId:'run_score',toolId:'fixture_rate',toolVersion:1,kind:'catalog'}];await local.store.saveSpace(current,tx);});
  const endpoint=`/api/spaces/${state.space.slug}/tools/fixture_rate/invoke`;expect((await local.app.inject({method:'POST',url:endpoint,headers,payload:{...invocation(),componentId:'wrong'}})).statusCode).toBe(403);delayed=true;const pending=local.app.inject({method:'POST',url:endpoint,headers,payload:invocation()});await vi.waitFor(()=>expect(calls).toBe(2));
  await local.store.db.transaction(async tx=>{const current=(await local.store.getSpace(state.space.slug,tx,true))!;current.definition!.definitionVersion++;await local.store.saveSpace(current,tx);});resolve({factor:2});expect((await pending).statusCode).toBe(409);expect((await local.store.getTool(state.space.id,'fixture_rate',1))!.invocationCount).toBe(0);
 }finally{await local.app.close();}
},15000);
it('aborts a tool when its HTTP client disconnects after sending the request body',async()=>{
 let entered=false,aborted=false;const local=await buildApp({db:await createDatabase(),origin,localDemo:true,generatedToolAdapter:{...runtime,invoke:async(_spec,_input,{signal})=>{entered=true;return new Promise((_resolve,reject)=>{signal!.addEventListener('abort',()=>{aborted=true;reject(new Error('Cancelled fixture.'));},{once:true});});}}});
 try{const headers=await login(local),state=await space(local);expect((await register(state,spec(),true,local,headers)).statusCode).toBe(200);const address=await local.app.listen({host:'127.0.0.1',port:0}),controller=new AbortController(),pending=fetch(address+url(state,'/score/invoke'),{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(invocation()),signal:controller.signal}).catch(()=>null);await vi.waitFor(()=>expect(entered).toBe(true));controller.abort();await pending;await vi.waitFor(()=>expect(aborted).toBe(true));await vi.waitFor(async()=>{const rows=await local.store.db.query<{data:{status:string}}>('SELECT data FROM lf_code_tool_requests WHERE space_id=$1',[state.space.id]);expect(rows.rows[0]!.data.status).toBe('failed');});expect((await local.store.getCodeTools(state.space.id))[0]!.invocationCount).toBe(0);
 }finally{await local.app.close();}
},15000);
it('returns honest busy status, never executes a rejected request ID, and accepts a deliberate fresh request after capacity frees',async()=>{
 const state=await space();expect((await register(state)).statusCode).toBe(200);
 const held=spec();held.capabilities.publicRecordFields=['points'];held.source='async function run(input,api){await api.readRecords({fields:["points"]});return {answer:input.value*7}}';
 let entered=false,release!:(rows:[])=>void;const controller=new AbortController();const running=runtime.invoke(held,{value:1},{signal:controller.signal,broker:{async readRecords(){entered=true;return new Promise<[]>(resolve=>{release=resolve;});},async callConnector(){return {};}}});const settled=Promise.allSettled([running]);
 try{await vi.waitFor(()=>expect(entered).toBe(true));const body=invocation(),busy=await invoke(state,body);expect(busy.statusCode,busy.body).toBe(429);expect(busy.json().error).toMatchObject({code:'TOOL_BUSY',message:'The tool runtime is busy. Start a new request after the current run finishes.'});
  expect((await ctx.store.getCodeTools(state.space.id))[0]!.invocationCount).toBe(0);const rows=await ctx.store.db.query<{data:{status:string}}>('SELECT data FROM lf_code_tool_requests WHERE space_id=$1 AND request_id=$2',[state.space.id,body.requestId]);expect(rows.rows[0]!.data.status).toBe('failed');
  release([]);expect((await settled)[0]).toMatchObject({status:'fulfilled',value:{answer:7}});
  const same=await invoke(state,body);expect(same.statusCode,same.body).toBe(409);expect(same.json().error.code).toBe('TOOL_INTERRUPTED');expect((await ctx.store.getCodeTools(state.space.id))[0]!.invocationCount).toBe(0);
  const fresh=invocation(),success=await invoke(state,fresh);expect(success.statusCode,success.body).toBe(200);expect(success.json()).toMatchObject({result:{answer:56},reused:false});expect((await invoke(state,fresh)).json()).toEqual(success.json());expect((await ctx.store.getCodeTools(state.space.id))[0]!.invocationCount).toBe(1);
  const audit=await ctx.store.db.query<{status:string}>('SELECT status FROM lf_tool_runs WHERE space_id=$1',[state.space.id]);expect(audit.rows.map(row=>row.status).sort()).toEqual(['failed','ok']);
 }finally{controller.abort();await settled;}
},15000);
