#!/usr/bin/env python3
"""Generate only the project-local Codex config; never rewrite unrelated config."""
from pathlib import Path
import argparse
from datetime import datetime, timezone
import json
import os
import sys
import tempfile
import tomllib

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--trust", action="store_true", help="Trust only this repository in the user Codex config (with backup).")
args = parser.parse_args()
ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / ".codex/config.toml"
MARKER = "# Generated by LivingForma scripts/setup-workflow.py"
template = (ROOT / ".codex/config.toml.example").read_text()
# JSON string escaping is valid for the TOML basic-string contents used here.
escaped_root = json.dumps(str(ROOT), ensure_ascii=False)[1:-1]
text = MARKER + "\n" + template.replace("__LIVINGFORMA_ROOT__", escaped_root)
config = tomllib.loads(text)
for name, role in config["agents"].items():
    if isinstance(role, dict) and "config_file" in role:
        role_path = TARGET.parent / role["config_file"]
        tomllib.loads(role_path.read_text())
if TARGET.exists() and not TARGET.read_text().startswith(MARKER):
    sys.exit(f"Preserving existing unmanaged configuration: {TARGET}. Merge the example manually.")
TARGET.parent.mkdir(parents=True, exist_ok=True)
with tempfile.NamedTemporaryFile("w", dir=TARGET.parent, delete=False) as f:
    f.write(text)
    temporary = f.name
os.replace(temporary, TARGET)
print(f"Generated {TARGET}")
if args.trust:
    codex_home = Path(os.environ.get("CODEX_HOME", str(Path.home() / ".codex")))
    user_config = codex_home / "config.toml"
    old_text = user_config.read_text() if user_config.exists() else ""
    user_data = tomllib.loads(old_text)
    existing = user_data.get("projects", {}).get(str(ROOT))
    if existing and existing.get("trust_level") == "trusted":
        print("This exact repository is already trusted.")
    elif existing is not None:
        sys.exit("Preserving an existing project entry. Set this project's trust in the Codex UI.")
    else:
        backup_dir = ROOT / ".local/config-backups"
        backup_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
        backup = backup_dir / f"codex-{stamp}.toml"
        with backup.open("x") as f:
            os.chmod(backup, 0o600)
            f.write(old_text)
        updated = old_text.rstrip() + f'\n\n[projects.{json.dumps(str(ROOT), ensure_ascii=False)}]\ntrust_level = "trusted"\n'
        tomllib.loads(updated)
        codex_home.mkdir(parents=True, exist_ok=True)
        # Do not overwrite concurrent edits from the app or another agent.
        if user_config.exists() and user_config.read_text() != old_text:
            sys.exit("Codex config changed during setup. Retry after the other edit completes.")
        with tempfile.NamedTemporaryFile("w", dir=codex_home, delete=False) as f:
            f.write(updated)
            temporary = f.name
        os.replace(temporary, user_config)
        print("Trusted only this repository; saved a private backup under .local/config-backups/.")
print("Existing model, sandbox and approval settings are unchanged.")
