import {useCallback,useEffect,useRef,useState,useSyncExternalStore,type Dispatch,type SetStateAction} from 'react';
import {validateDefinition,type Session,type Snapshot,type Mutation,type Proposal} from '@livingforma/contracts';
import {assertCurrent,changePage,getIdentity,getPageRevision,invalidateIdentity,localSignIn,protectedRequest,refreshSession,request,RequestError,signedOut,StaleRequestError,subscribeIdentity} from './session-client';
export {request,protectedRequest,RequestError} from './session-client';
export type SpaceLink={id:string;slug:string;title:string;role:string};
export const readSlug=()=>decodeURIComponent(location.pathname.match(/^\/s\/([^/]+)/)?.[1]||'');
export function useWorkspace(){
  const [slug,setSlug]=useState(readSlug),[session,setSession]=useState<Session|null>(null),[spaces,setSpaces]=useState<SpaceLink[]>([]),[snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[connection,setConnection]=useState<'connecting'|'live'|'offline'>('connecting'),[notice,setNotice]=useState(''),[streamTick,setStreamTick]=useState(0),[identityTick,setIdentityTick]=useState(0);
  const snap=useRef<Snapshot|null>(null),currentSlug=useRef(slug),pendingMutations=useRef(new Map<string,string>()),sourceRef=useRef<EventSource|null>(null),loggingOut=useRef(false),mounted=useRef(true);
  const clearView=useCallback(()=>{sourceRef.current?.close();sourceRef.current=null;snap.current=null;setSnapshot(null);setSpaces([]);setError('');setLoading(!!currentSlug.current);setConnection('connecting')},[]);
  const navigate=useCallback((next:string)=>{if(next===currentSlug.current)return;changePage();currentSlug.current=next;history.pushState({},'',`/s/${encodeURIComponent(next)}`);setSlug(next);clearView();},[clearView]);
  useEffect(()=>{const pop=()=>{changePage();currentSlug.current=readSlug();setSlug(currentSlug.current);clearView()};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[clearView]);
  useEffect(()=>{mounted.current=true;const sync=()=>{const current=getIdentity();if(current.change!=='token'){clearView();pendingMutations.current.clear()}setSession(current.session);setIdentityTick(current.revision);if(current.reason)setNotice(current.reason)};const unsubscribe=subscribeIdentity(sync);if(getIdentity().session)sync();return()=>{mounted.current=false;unsubscribe();sourceRef.current?.close()}},[clearView]);
  const refreshIdentity=useCallback(async()=>{const identity=await refreshSession();const revision=getIdentity().revision;const index=await request<{spaces:SpaceLink[]}>('/api/spaces');if(!mounted.current||revision!==getIdentity().revision)throw new StaleRequestError();setSession(identity);setSpaces(index.spaces);return {identity,index};},[]);
  useEffect(()=>{let active=true;refreshIdentity().then(result=>{if(!active)return;if(!currentSlug.current&&result.index.spaces.length){const next=result.index.spaces[0].slug;changePage();currentSlug.current=next;history.replaceState({},'',`/s/${encodeURIComponent(next)}`);setSlug(next)}else if(!currentSlug.current)setLoading(false)}).catch(e=>{if(active&&!(e instanceof StaleRequestError)){setError(e.message);setLoading(false)}});return()=>{active=false}},[refreshIdentity]);
  const apply=useCallback((next:Snapshot)=>{if(next.space.slug!==currentSlug.current||loggingOut.current)throw new StaleRequestError();if(next.definition)validateDefinition(next.definition);const previous=snap.current;if(previous&&previous.space.id===next.space.id&&next.eventCursor<previous.eventCursor)return;if(previous&&next.definition?.definitionVersion!==previous.definition?.definitionVersion)setNotice(`Space updated · ${next.definition?.summary||'A new version is ready'}`);const focused=document.activeElement as HTMLInputElement|null;const focusId=focused?.id;const selection=focused&&'selectionStart' in focused?focused.selectionStart:null;snap.current=next;setSnapshot(next);setError('');setLoading(false);if(focusId)requestAnimationFrame(()=>{if(focused&&!document.contains(focused)){const replacement=document.getElementById(focusId) as HTMLInputElement|null;replacement?.focus();if(selection!==null&&replacement&&'setSelectionRange' in replacement&&['text','search',''].includes(replacement.type))replacement.setSelectionRange(selection,selection)}})},[]);
  const refresh=useCallback(async()=>{const requestedSlug=currentSlug.current;if(!requestedSlug||!getIdentity().session||loggingOut.current)return;const revision=getIdentity().revision,scope=getPageRevision();const next=await request<Snapshot>(`/api/spaces/${encodeURIComponent(requestedSlug)}/snapshot`).catch(error=>{if(error instanceof RequestError&&([401,403,404].includes(error.status))&&revision===getIdentity().revision&&scope===getPageRevision()&&requestedSlug===currentSlug.current){clearView();setError(error.message);setLoading(false);setConnection('offline')}throw error});if(revision!==getIdentity().revision||scope!==getPageRevision()||requestedSlug!==currentSlug.current)throw new StaleRequestError();apply(next);return next},[apply,clearView]);
  useEffect(()=>{if(!session||loggingOut.current)return;let alive=true;void request<{spaces:SpaceLink[]}>('/api/spaces').then(index=>{if(alive)setSpaces(index.spaces)}).catch(()=>{});if(slug)void refresh().catch(e=>{if(alive&&!(e instanceof StaleRequestError)){setError(e.message);setLoading(false);setConnection('offline')}});return()=>{alive=false}},[slug,identityTick,session?.user?.id,refresh]);
  useEffect(()=>{if(!snapshot||snapshot.space.slug!==slug)return;let active=true,timer:ReturnType<typeof setTimeout>|undefined,pending=false,again=false;setConnection('connecting');const source=new EventSource(`/api/spaces/${encodeURIComponent(slug)}/events?after=${snapshot.eventCursor}`);sourceRef.current=source;
    async function reload(){if(pending){again=true;return}pending=true;try{await refresh()}catch{if(active)setConnection('offline')}finally{pending=false;if(again&&active){again=false;void reload()}}}
    source.onopen=()=>{if(active)setConnection('live')};
    const changed=(event:MessageEvent)=>{try{const e=JSON.parse(event.data);if(e.id&&e.id<=(snap.current?.eventCursor??-1))return}catch{/* Reload authoritative data. */}void reload()};
    source.onmessage=changed;for(const name of ['definition.published','records.changed','snapshot.updated'])source.addEventListener(name,changed as EventListener);
    const reconnect=()=>{source.close();if(!active)return;setConnection('offline');timer=setTimeout(async()=>{try{await refreshIdentity();await refresh()}catch{/* Keep the safe current view. */}if(active)setStreamTick(t=>t+1)},2500)};
    source.addEventListener('reset.required',reconnect);source.onerror=reconnect;return()=>{active=false;source.close();if(sourceRef.current===source)sourceRef.current=null;clearTimeout(timer)};
  },[slug,!!snapshot,identityTick,streamTick,refresh,refreshIdentity]);
  useEffect(()=>{const recover=()=>{if(document.hidden||loggingOut.current)return;void refreshIdentity().then(()=>refresh()).then(()=>setStreamTick(t=>t+1)).catch(()=>{})};const offline=()=>setConnection('offline');addEventListener('focus',recover);addEventListener('online',recover);addEventListener('offline',offline);document.addEventListener('visibilitychange',recover);return()=>{removeEventListener('focus',recover);removeEventListener('online',recover);removeEventListener('offline',offline);document.removeEventListener('visibilitychange',recover)}},[refresh,refreshIdentity]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id)},[notice]);
  async function mutate(input:Omit<Mutation,'requestId'|'definitionVersion'>){if(!snapshot?.definition||!session?.user)throw new Error('Please sign in before saving a record.');const userId=session.user.id,scope=getPageRevision();assertCurrent(userId,scope);const mutationKey=JSON.stringify({slug,user:userId,version:snapshot.definition.definitionVersion,...input});const requestId=pendingMutations.current.get(mutationKey)||crypto.randomUUID();pendingMutations.current.set(mutationKey,requestId);try{const result=await protectedRequest<Snapshot>(`/api/spaces/${slug}/actions`,{method:'POST',body:JSON.stringify({...input,requestId,definitionVersion:snapshot.definition.definitionVersion})},userId);assertCurrent(userId,scope);pendingMutations.current.delete(mutationKey);apply(result);return result}catch(e){if(e instanceof RequestError&&e.status<500)pendingMutations.current.delete(mutationKey);if(e instanceof RequestError&&e.status===409&&!(e instanceof StaleRequestError))await refresh().catch(()=>{});throw e}}
  async function propose(prompt:string){if(!snapshot?.permissions.canEdit||!session?.user)throw new Error('Only the owner can reshape this space.');const userId=session.user.id,scope=getPageRevision();assertCurrent(userId,scope);const result=await protectedRequest<{snapshot:Snapshot;proposal:Proposal;requiresToolApproval?:boolean}>(`/api/spaces/${slug}/proposals`,{method:'POST',body:JSON.stringify({prompt,baseDefinitionVersion:snapshot.definition?.definitionVersion??0,requestId:crypto.randomUUID()})},userId);assertCurrent(userId,scope);if(!result.requiresToolApproval){apply(result.snapshot);setNotice(`${result.proposal.summary}${result.proposal.source==='local-rules'?' · local rules mode':''}`)}return result}
  async function localLogin(){await localSignIn();await refreshIdentity();await refresh()}
  async function logout(){const userId=session?.user?.id??null;if(loggingOut.current)return;loggingOut.current=true;invalidateIdentity('Signing out…');clearView();try{await protectedRequest('/auth/logout',{method:'POST'},userId);signedOut()}finally{loggingOut.current=false;void refreshIdentity().then(()=>refresh()).catch(()=>{})}}
  async function createSpace(title:string,prompt:string){const userId=session?.user?.id??null,scope=getPageRevision();assertCurrent(userId,scope);const result=await protectedRequest<Snapshot>('/api/spaces',{method:'POST',body:JSON.stringify({title,...(prompt.trim()?{prompt:prompt.trim()}:{})})},userId);assertCurrent(userId,scope);navigate(result.space.slug);return result}
  return {slug,session,spaces,snapshot,loading,error,connection,notice,navigate,refresh,refreshIdentity,mutate,propose,localLogin,logout,createSpace,setNotice};
}
export function dayInTimezone(timezone:string,date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
export function dayBefore(date:string,days=1){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10)}
function readDraft(storageKey:string,initial:Record<string,unknown>){try{return {...initial,...(JSON.parse(sessionStorage.getItem(storageKey)||'null')??{})}}catch{return initial}}
export function useDraft(key:string,initial:Record<string,unknown>={},legacyOwnerAccount?:string|null){
  const identity=useSyncExternalStore(subscribeIdentity,getIdentity),account=identity.session?.user?.id??'anonymous';
  const storageKey=`lf-draft:v2:${encodeURIComponent(account)}:${key}`;
  try{if(legacyOwnerAccount===account&&account!=='anonymous'&&!sessionStorage.getItem(storageKey)){
    const legacy=`lf-draft:${key}`,saved=sessionStorage.getItem(legacy);
    if(saved){sessionStorage.setItem(storageKey,saved);sessionStorage.removeItem(legacy)}
  }}catch{/* Storage can be blocked; the editor must remain usable. */}
  const [state,setState]=useState(()=>({key:storageKey,value:readDraft(storageKey,initial)}));
  const draft=state.key===storageKey?state.value:readDraft(storageKey,initial);
  const latest=useRef({key:storageKey,value:draft});latest.current={key:storageKey,value:draft};
  const setDraft:Dispatch<SetStateAction<Record<string,unknown>>>=useCallback(update=>{
    // Persist synchronously so a successful request can clear its original draft even if a refresh unmounted the form.
    const before=latest.current.key===storageKey?latest.current.value:readDraft(storageKey,initial);
    const value=typeof update==='function'?update(before):update;
    try{sessionStorage.setItem(storageKey,JSON.stringify(value))}catch{/* Keep the in-memory draft when storage is unavailable. */}
    latest.current={key:storageKey,value};setState({key:storageKey,value});
  },[storageKey]);
  return [draft,setDraft] as const;
}
