import {useCallback,useEffect,useRef,useState} from 'react';
import {stopLocalDevices} from './media-events';
import {validateDefinition,type Session,type Snapshot,type Mutation,type Proposal} from '@livingforma/contracts';

export type SpaceLink={id:string;slug:string;title:string;role:string};
export class RequestError extends Error { constructor(public status:number,public code:string,message:string){super(message)} }
export async function request<T>(path:string,options:RequestInit={},csrf?:string|null):Promise<T>{
  const response=await fetch(path,{...options,credentials:'same-origin',headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...options.headers}});
  const body=await response.json().catch(()=>({}));
  if(!response.ok)throw new RequestError(response.status,body.error?.code||'REQUEST_FAILED',body.error?.message||'We could not connect. Please try again.');
  return body;
}
export const readSlug=()=>decodeURIComponent(location.pathname.match(/^\/s\/([^/]+)/)?.[1]||'');
export function useWorkspace(){
  const [slug,setSlug]=useState(readSlug),[session,setSession]=useState<Session|null>(null),[spaces,setSpaces]=useState<SpaceLink[]>([]),[snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[connection,setConnection]=useState<'connecting'|'live'|'offline'>('connecting'),[notice,setNotice]=useState(''),[streamTick,setStreamTick]=useState(0);
  const snap=useRef<Snapshot|null>(null),epoch=useRef(0),currentSlug=useRef(slug),pendingMutations=useRef(new Map<string,string>());
  currentSlug.current=slug;
  const navigate=useCallback((next:string)=>{if(next===currentSlug.current)return;stopLocalDevices('Space changed.');history.pushState({},'',`/s/${encodeURIComponent(next)}`);setSlug(next);setSnapshot(null);snap.current=null;setLoading(true);setError('');},[]);
  useEffect(()=>{const pop=()=>{stopLocalDevices('Space changed.');setSlug(readSlug());setSnapshot(null);snap.current=null;setLoading(true)};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
  const refreshIdentity=useCallback(async()=>{const myEpoch=++epoch.current;const [identity,index]=await Promise.all([request<Session>('/api/session'),request<{spaces:SpaceLink[]}>('/api/spaces')]);if(myEpoch!==epoch.current)return;setSession(identity);setSpaces(index.spaces);return {identity,index};},[]);
  useEffect(()=>{let active=true;refreshIdentity().then(result=>{if(!active||!result)return;if(!currentSlug.current&&result.index.spaces.length){const next=result.index.spaces[0].slug;history.replaceState({},'',`/s/${encodeURIComponent(next)}`);setSlug(next)}else if(!currentSlug.current)setLoading(false)}).catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false}},[refreshIdentity]);
  const apply=useCallback((next:Snapshot,identityEpoch=epoch.current)=>{if(identityEpoch!==epoch.current||next.space.slug!==currentSlug.current)return;if(next.definition)validateDefinition(next.definition);const previous=snap.current;if(previous&&previous.space.id===next.space.id&&next.eventCursor<previous.eventCursor)return;if(previous&&next.definition?.definitionVersion!==previous.definition?.definitionVersion)setNotice(`Space updated · ${next.definition?.summary||'A new version is ready'}`);const focused=document.activeElement as HTMLInputElement|null;const focusId=focused?.id;const selection=focused&&'selectionStart' in focused?focused.selectionStart:null;snap.current=next;setSnapshot(next);setError('');setLoading(false);if(focusId)requestAnimationFrame(()=>{if(focused&&!document.contains(focused)){const replacement=document.getElementById(focusId) as HTMLInputElement|null;replacement?.focus();if(selection!==null&&replacement&&'setSelectionRange' in replacement&&['text','search',''].includes(replacement.type))replacement.setSelectionRange(selection,selection)}})},[]);
  const refresh=useCallback(async()=>{const requestedSlug=currentSlug.current,identityEpoch=epoch.current;if(!requestedSlug)return;const next=await request<Snapshot>(`/api/spaces/${encodeURIComponent(requestedSlug)}/snapshot`);apply(next,identityEpoch);return next},[apply]);
  useEffect(()=>{if(!slug)return;let alive=true;refresh().catch(e=>{if(alive){setError(e.message);setLoading(false);setConnection('offline')}});return()=>{alive=false}},[slug,session?.user?.id,refresh]);
  useEffect(()=>{if(!snapshot||snapshot.space.slug!==slug)return;let active=true,timer:ReturnType<typeof setTimeout>|undefined,pending=false,again=false;setConnection('connecting');const source=new EventSource(`/api/spaces/${encodeURIComponent(slug)}/events?after=${snapshot.eventCursor}`);
    async function reload(){if(pending){again=true;return}pending=true;try{await refresh()}catch{if(active)setConnection('offline')}finally{pending=false;if(again&&active){again=false;void reload()}}}
    source.onopen=()=>{if(active)setConnection('live')};
    const changed=(event:MessageEvent)=>{try{const e=JSON.parse(event.data);if(e.id&&e.id<=(snap.current?.eventCursor??-1))return}catch{/* A malformed event safely triggers authoritative reload. */}void reload()};
    source.onmessage=changed;for(const name of ['definition.published','records.changed','snapshot.updated'])source.addEventListener(name,changed as EventListener);
    const reconnect=()=>{source.close();if(!active)return;setConnection('offline');timer=setTimeout(async()=>{try{await refresh()}catch{/* Keep last view. */}if(active)setStreamTick(t=>t+1)},2500)};
    source.addEventListener('reset.required',reconnect);source.onerror=reconnect;return()=>{active=false;source.close();clearTimeout(timer)};
  // Cursor updates do not restart a healthy stream; reconnect starts from the newly applied snapshot.
  },[slug,!!snapshot,session?.user?.id,streamTick,refresh]);
  useEffect(()=>{const online=()=>{void refresh().then(()=>setStreamTick(t=>t+1)).catch(()=>{})};const offline=()=>setConnection('offline');addEventListener('online',online);addEventListener('offline',offline);return()=>{removeEventListener('online',online);removeEventListener('offline',offline)}},[refresh]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id)},[notice]);
  async function mutate(input:Omit<Mutation,'requestId'|'definitionVersion'>){if(!snapshot?.definition||!session?.user)throw new Error('Please sign in before saving a record.');const myEpoch=epoch.current;const mutationKey=JSON.stringify({slug,user:session.user.id,version:snapshot.definition.definitionVersion,...input});const requestId=pendingMutations.current.get(mutationKey)||crypto.randomUUID();pendingMutations.current.set(mutationKey,requestId);try{const result=await request<Snapshot>(`/api/spaces/${slug}/actions`,{method:'POST',body:JSON.stringify({...input,requestId,definitionVersion:snapshot.definition.definitionVersion})},session.csrfToken);pendingMutations.current.delete(mutationKey);apply(result,myEpoch);return result}catch(e){if(e instanceof RequestError&&e.status<500)pendingMutations.current.delete(mutationKey);if(e instanceof RequestError&&(e.status===409||e.status===401||e.status===403)){await refreshIdentity();await refresh()}throw e}}
  async function propose(prompt:string){if(!snapshot?.permissions.canEdit)throw new Error('Only the owner can reshape this space.');const myEpoch=epoch.current;const result=await request<{snapshot:Snapshot;proposal:Proposal;requiresToolApproval?:boolean}>(`/api/spaces/${slug}/proposals`,{method:'POST',body:JSON.stringify({prompt,baseDefinitionVersion:snapshot.definition?.definitionVersion??0,requestId:crypto.randomUUID()})},session?.csrfToken);if(!result.requiresToolApproval)apply(result.snapshot,myEpoch);if(!result.requiresToolApproval&&myEpoch===epoch.current)setNotice(`${result.proposal.summary}${result.proposal.source==='local-rules'?' · local rules mode':''}`);return result}
  async function localLogin(){await request('/auth/local',{method:'POST',body:JSON.stringify({persona:'owner'})},session?.csrfToken);snap.current=null;setSnapshot(null);await refreshIdentity();await refresh();}
  async function logout(){stopLocalDevices('Signed out.');await request('/auth/logout',{method:'POST'},session?.csrfToken);epoch.current++;snap.current=null;setSnapshot(null);setSession(null);Object.keys(sessionStorage).filter(k=>k.startsWith('lf-draft:')).forEach(k=>sessionStorage.removeItem(k));await refreshIdentity();await refresh()}
  async function createSpace(title:string,prompt:string){const myEpoch=epoch.current;const result=await request<Snapshot>('/api/spaces',{method:'POST',body:JSON.stringify({title,...(prompt.trim()?{prompt:prompt.trim()}:{})})},session?.csrfToken);if(myEpoch!==epoch.current)return;await refreshIdentity();navigate(result.space.slug)}
  return {slug,session,spaces,snapshot,loading,error,connection,notice,navigate,refresh,refreshIdentity,mutate,propose,localLogin,logout,createSpace,setNotice};
}
export function dayInTimezone(timezone:string,date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
export function dayBefore(date:string,days=1){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10)}
export function useDraft(key:string,initial:Record<string,unknown>={}){const storageKey=`lf-draft:${key}`;const [draft,setDraft]=useState<Record<string,unknown>>(()=>{try{return {...initial,...(JSON.parse(sessionStorage.getItem(storageKey)||'null')??{})}}catch{return initial}});useEffect(()=>{sessionStorage.setItem(storageKey,JSON.stringify(draft))},[draft,storageKey]);return [draft,setDraft] as const}
