import {chromium,expect,type Page} from '@playwright/test';
import {resolve} from 'node:path';
import {writeFile} from 'node:fs/promises';
import {buildApp} from '../../../../apps/api/src/app';
import {applyProposal} from '../../../../apps/api/src/domain';
import {createDatabase} from '../../../../packages/db/src/index';
import {componentSchema,readingDefinition,type Proposal,type SiteGenerator} from '../../../../packages/contracts/src/index';
process.env.ENABLE_LOCAL_DEMO='true';process.env.NODE_ENV='test';
const origin='http://localhost:4349',root='docs/memory/handoffs/frontend';let generationCalls=0;const writes:string[]=[],checks:string[]=[],errors:string[]=[],reports:Array<{id:string;revision:number;ok:boolean}>=[];
function proposal(current=readingDefinition()):Proposal{return {entitySchema:current.entitySchema,appSpec:{...current.appSpec,title:'Bounded choices',components:[componentSchema.parse({id:'website',type:'generated-site',version:1,fields:current.entitySchema.fields.filter(field=>field.public).map(field=>field.id),actionIds:current.appSpec.actions.map(action=>action.id)})],generated:{format:'html-v1',bridgeVersion:1,assetIds:[],html:'<main><h1>Make a choice</h1><button id="pick">Choose image</button><button id="remove">Remove first record</button><p id="result" role="status"></p></main>',css:'body{font:16px system-ui;background:#f2ede5;color:#304032}main{padding:24px}h1{font:36px Georgia}button{font:inherit;margin:10px;padding:12px;border:1px solid #888;background:white;border-radius:8px}',js:`(async()=>{let state=await lf.ready;lf.subscribe(next=>state=next);const out=document.getElementById('result');document.getElementById('pick').onclick=async()=>{out.textContent='Waiting for your image';try{const asset=await lf.pickImage();await lf.update(state.records[0].id,{photo:asset.assetId});out.textContent='Image saved'}catch(error){out.textContent=error.message}};document.getElementById('remove').onclick=async()=>{out.textContent='Waiting for confirmation';try{await lf.remove(state.records[0].id);out.textContent='Record removed'}catch(error){out.textContent=error.message}};lf.reportReady()})();`}},summary:'Offline human-choice and check-retry fixture.',source:'gemini',capabilityGaps:[]}}
const generator:SiteGenerator=async input=>{generationCalls++;return proposal(input.current??undefined)};
const api=await buildApp({db:await createDatabase(),origin,localDemo:true,siteGenerator:generator,staticDir:'/tmp/livingforma-lf234-web'});const state=(await api.store.getSpace('reading'))!;state.definition!.entitySchema.fields.push({id:'photo',label:'Photo reference',type:'text',public:true,required:false});applyProposal(state,proposal(state.definition!));await api.store.db.transaction(tx=>api.store.event(state,'definition.published',tx));await api.app.listen({host:'127.0.0.1',port:4349});
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1280,height:950},reducedMotion:'reduce'});await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});const page=await context.newPage();page.setDefaultTimeout(15000);await page.clock.install();page.on('pageerror',e=>errors.push(e.message));page.on('request',request=>{if(request.method()==='POST'&&/\/(assets|actions)$/.test(new URL(request.url()).pathname))writes.push(new URL(request.url()).pathname);if(request.method()==='POST'&&request.url().endsWith('/preview')){const body=request.postDataJSON();reports.push({id:request.url().split('/').at(-2)!,revision:body.sourceRevision,ok:body.ok})}});
const frame=()=>page.frameLocator('iframe[title="Generated website"]');async function click(name:string){await frame().getByRole('button',{name,exact:true}).focus();await page.keyboard.press('Enter')}
async function lateFile(handle:any){await handle.evaluate((node:HTMLInputElement)=>{const transfer=new DataTransfer();transfer.items.add(new File(['old choice'],'late.png',{type:'image/png'}));node.files=transfer.files;node.dispatchEvent(new Event('change',{bubbles:true}))})}
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.log('PASS',name)}
try{
 await page.goto(`${origin}/s/reading`);await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');
 await check('An image selected after 31 seconds still reaches the real host and saves its reference',async()=>{await click('Choose image');await expect(page.getByRole('heading',{name:'Add an image',exact:true})).toBeVisible();await page.clock.fastForward(31000);await expect(frame().getByRole('status')).toHaveText('Waiting for your image');const image=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=20;canvas.height=20;canvas.getContext('2d')!.fillRect(0,0,20,20);return canvas.toDataURL('image/png').split(',')[1]});await page.locator('input[type=file]').setInputFiles({name:'choice.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await expect(frame().getByRole('status')).toHaveText('Image saved');expect((await api.store.getSpace('reading'))!.records[0].values.photo).toMatch(/^asset_/);expect(writes).toHaveLength(2)});
 await check('Explicit image cancellation and keeping a record send no writes',async()=>{const before=writes.length;await click('Choose image');await page.getByRole('button',{name:'Cancel image selection'}).click();await expect(frame().getByRole('status')).toContainText('cancelled');await expect(page.getByRole('dialog')).toHaveCount(0);await click('Remove first record');await page.getByRole('button',{name:'Keep record',exact:true}).click();await expect(frame().getByRole('status')).toContainText('Your record was kept');expect(writes).toHaveLength(before)});
 await check('120-second image expiry closes the host dialog and ignores a late native selection',async()=>{const before=writes.length;await click('Choose image');await expect(page.getByRole('heading',{name:'Add an image',exact:true})).toBeVisible();const oldInput=await page.locator('input[type=file]').elementHandle();await page.clock.fastForward(120001);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(frame().getByRole('status')).toContainText('Image selection expired');await lateFile(oldInput);expect(writes).toHaveLength(before);await page.screenshot({path:`${root}/LF-234-choice-expired.png`})});
 await check('120-second deletion expiry keeps the record; a fresh confirmation after 31 seconds still works',async()=>{const before=writes.length,count=(await api.store.getSpace('reading'))!.records.length;await click('Remove first record');const oldButton=await page.getByRole('button',{name:'Delete record',exact:true}).elementHandle();await page.clock.fastForward(120001);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(frame().getByRole('status')).toContainText('Delete confirmation expired');await oldButton!.evaluate(button=>button.click());expect(writes).toHaveLength(before);expect((await api.store.getSpace('reading'))!.records).toHaveLength(count);await click('Remove first record');await expect(page.getByRole('heading',{name:'Delete this record?',exact:true})).toBeVisible();await page.clock.fastForward(31000);await page.getByRole('button',{name:'Delete record',exact:true}).click();await expect(frame().getByRole('status')).toHaveText('Record removed');expect((await api.store.getSpace('reading'))!.records).toHaveLength(count-1)});
 await check('Identity changes cancel the outstanding choice and ignore its old selection',async()=>{const before=writes.length;await click('Choose image');await expect(page.getByRole('heading',{name:'Add an image',exact:true})).toBeVisible();const input=await page.locator('input[type=file]').elementHandle();await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'participant'}});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Open the space designer'})).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(0);await lateFile(input);expect(writes).toHaveLength(before);await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});await page.reload();await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready')});
 await check('Leaving the space cancels a choice before any upload can be sent',async()=>{const before=writes.length;await click('Choose image');await expect(page.getByRole('heading',{name:'Add an image',exact:true})).toBeVisible();const input=await page.locator('input[type=file]').elementHandle();await page.evaluate(()=>{history.pushState(null,'','/s/habits');window.dispatchEvent(new PopStateEvent('popstate'))});await expect(page).toHaveURL(`${origin}/s/habits`);await expect(page.getByRole('dialog')).toHaveCount(0);await lateFile(input);expect(writes).toHaveLength(before);await page.locator('.space-nav a[href="/s/reading"]').click();await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready')});
 await check('A failed ready report waits for explicit retry, then checks the same job/revision without a model call',async()=>{let reject=true;await context.route('**/generations/*/preview',async route=>{if(reject&&route.request().postDataJSON().ok){reject=false;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_NETWORK_FAILURE',message:'Offline fixture: the check could not be delivered.'}})})}return route.continue()});await page.getByRole('button',{name:'Open the space designer'}).click();const prompt='Keep this fixture, and check its existing interactions';await page.getByRole('textbox',{name:'Describe your website'}).fill(prompt);await page.getByRole('button',{name:'Create website',exact:true}).click();await expect(page.getByRole('button',{name:'Retry preview check'})).toBeVisible();expect(generationCalls).toBe(1);expect(reports).toHaveLength(1);await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeDisabled();await page.getByRole('tab',{name:'HTML',exact:true}).click();await page.getByRole('tab',{name:'Preview',exact:true}).click();await page.clock.fastForward(4000);await expect(page.locator('.is-preview .generated-frame-status [role=status]')).toHaveText('Website ready');expect(reports).toHaveLength(1);await page.screenshot({path:`${root}/LF-234-preview-retry.png`});await page.getByRole('tab',{name:'HTML',exact:true}).click();await page.getByRole('button',{name:'Retry preview check'}).click();await expect(page.getByRole('tab',{name:'Preview',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled();expect(reports).toHaveLength(2);expect(reports[1]).toEqual(reports[0]);expect(generationCalls).toBe(1);await expect(page.getByRole('textbox',{name:'Describe your website'})).toHaveValue(prompt);await expect(page.getByRole('button',{name:'Report an issue',exact:true})).toBeVisible();await page.getByRole('button',{name:'Report an issue',exact:true}).click();await expect(page.getByLabel('What should work differently?')).toBeVisible();expect((await api.store.getSpace('reading'))!.definition!.definitionVersion).toBe(2)});
 expect(errors).toEqual([]);await writeFile(`${root}/LF-234-browser-results.json`,JSON.stringify({at:new Date().toISOString(),scope:'Real Chrome/MessageChannel/current backend bootstrap/local API/PGlite; virtual clock for human timeouts, offline generator, explicit transport rejection fixture. No providers or shared apps/web/dist rebuild.',checks,writes,generationCalls,reports,errors},null,2));
}catch(error){await page.screenshot({path:`${root}/LF-234-failed.png`,fullPage:true});await writeFile(`${root}/LF-234-failed.json`,JSON.stringify({error:String(error),body:await page.locator('body').innerText(),writes,reports,generationCalls,errors},null,2));throw error}finally{await context.close();await browser.close();await api.app.close()}
