import {chromium,expect} from '@playwright/test';
import {resolve} from 'node:path';
import {writeFile} from 'node:fs/promises';
import {buildApp} from '../../../../apps/api/src/app';
import {createDatabase} from '../../../../packages/db/src/index';
import {componentSchema,readingDefinition,type SiteGenerator,type Proposal} from '../../../../packages/contracts/src/index';
process.env.ENABLE_LOCAL_DEMO='true';process.env.NODE_ENV='test';
const origin='http://localhost:4337',root='docs/memory/handoffs/frontend';let calls=0;
const generator:SiteGenerator=async input=>{
 calls++;input.onProgress?.({stage:'planning',message:'Offline fixture planning'});await new Promise(resolve=>setTimeout(resolve,input.prompt.includes('slow fixture')?1800:80));
 const current=input.current??readingDefinition();
 const proposal:Proposal={entitySchema:current.entitySchema,appSpec:{...current.appSpec,title:'The Interactive Reading Room',description:'An original website fixture running through the real generation pipeline.',layout:'flow',components:[componentSchema.parse({id:'custom-site',type:'generated-site',version:1,fields:current.entitySchema.fields.filter(field=>field.public).map(field=>field.id),actionIds:current.appSpec.actions.filter(action=>action.type!=='tool.invoke').map(action=>action.id)})],generated:{format:'html-v1',bridgeVersion:1,assetIds:[],html:'<main><small>A SPACE TO EXPLORE</small><h1>The Interactive Reading Room</h1><p id="summary"></p><button id="count">Count a moment · 0</button><label>Book title<input id="book"></label><button id="save">Save entry</button><button id="delete">Remove first record</button><button id="pick">Choose a photo</button><img id="photo" alt="Selected photograph"><p id="result" role="status"></p></main>',css:'body{margin:0;background:#ede4d5;color:#3d4035;font:16px system-ui}main{max-width:660px;margin:auto;padding:48px 24px}small{letter-spacing:3px}h1{font:50px Georgia;line-height:1.05}button,input{font:inherit;padding:12px;border-radius:9px;border:1px solid #8b917f;background:#fcfaf4;margin:6px 0}button{cursor:pointer;display:block}label{display:grid;margin-top:24px}img{max-width:100%;max-height:150px}#result{min-height:2em;font-size:13px}',js:`(async()=>{let state=await lf.ready,count=0;window.fixtureState=state;const result=document.getElementById('result');const draw=next=>{state=next;window.fixtureState=next;document.getElementById('summary').textContent=next.records.length+' records, kept safe.';if(next.records[0]?.values.photo)lf.image(next.records[0].values.photo).then(asset=>document.getElementById('photo').src=asset.dataUrl)};lf.subscribe(draw);document.getElementById('count').onclick=()=>{document.getElementById('count').textContent='Count a moment · '+(++count)};document.getElementById('save').onclick=async()=>{try{draw(await lf.create({title:document.getElementById('book').value,author:'Fixture author'}));result.textContent='Saved through the host'}catch(error){result.textContent=error.message}};document.getElementById('delete').onclick=async()=>{try{draw(await lf.remove(state.records[0].id));result.textContent='Deleted'}catch(error){result.textContent=error.message}};document.getElementById('pick').onclick=async()=>{try{const asset=await lf.pickImage();document.getElementById('photo').src=asset.dataUrl;await lf.update(state.records[0].id,{photo:asset.assetId});result.textContent=asset.assetId}catch(error){result.textContent=error.message}};lf.reportReady();})();`}},summary:'Generated an offline fixture website.',source:'gemini',capabilityGaps:[]};
 if(input.prompt.includes('repair')&&!input.repair)proposal.appSpec.generated!.js='throw new Error("Fixture startup failure");';
 input.onProgress?.({stage:'writing',message:'Offline source written',source:proposal.appSpec.generated});await new Promise(resolve=>setTimeout(resolve,80));return proposal;
};
const api=await buildApp({db:await createDatabase(),origin,localDemo:true,siteGenerator:generator,staticDir:resolve('apps/web/dist')});
const state=(await api.store.getSpace('reading'))!;state.definition!.entitySchema.fields.push({id:'photo',label:'Photo reference',public:true,required:false,type:'text'});state.definition!.entitySchema.fields.push({id:'private_note',label:'Private note',public:false,required:false,type:'text'});state.records[0].values.private_note='PRIVATE_FRAME_SENTINEL';await api.store.db.transaction(tx=>api.store.event(state,'definition.published',tx));await api.app.listen({host:'127.0.0.1',port:4337});
const browser=await chromium.launch({headless:true,channel:'chrome'});const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce'});await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});const page=await context.newPage();page.setDefaultTimeout(15000);const checks:string[]=[],errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
const frame=()=>page.frameLocator('iframe[title="Generated website preview"]');const live=()=>page.frameLocator('iframe[title="Generated website"]');
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.log('PASS',name)}
try{
 await page.goto(`${origin}/s/reading`);await page.getByRole('button',{name:'Open the space designer'}).click();
 await check('Default Owner prompt opens general generation with actual source and isolated read-only preview',async()=>{await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});await page.getByRole('textbox',{name:'Describe your website'}).fill('Build an original interactive reading room with custom styling and saved records');await page.getByRole('button',{name:'Create website',exact:true}).click();await expect(frame().getByRole('heading',{name:'The Interactive Reading Room'})).toBeVisible();await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled();await frame().getByRole('button',{name:'Count a moment · 0'}).click();await expect(frame().getByRole('button',{name:'Count a moment · 1'})).toBeVisible();await frame().getByLabel('Book title').fill('Preview cannot save');await frame().getByRole('button',{name:'Save entry'}).click();await expect(frame().getByRole('status')).toContainText('read-only');expect((await api.store.getSpace('reading'))!.definition!.definitionVersion).toBe(1);await page.getByRole('tab',{name:'HTML',exact:true}).click();await expect(page.locator('.studio-source code')).toContainText('<main>');await page.keyboard.press('ArrowRight');await expect(page.getByRole('tab',{name:'CSS',exact:true})).toBeFocused();await expect(page.getByRole('tab',{name:'CSS',exact:true})).toHaveAttribute('aria-selected','true');expect(await page.locator('.studio-source main').count()).toBe(0);await page.getByRole('tab',{name:'Preview',exact:true}).click();await expect(frame().getByRole('heading',{name:'The Interactive Reading Room'})).toBeVisible();expect((await page.getByRole('dialog').boundingBox())!.width).toBeGreaterThan(1100);await page.screenshot({path:`${root}/LF-226-base-regression-studio-desktop.png`});});
 await check('Publish keeps records and URL; public-only bridge can save with existing actions',async()=>{const before=(await api.store.getSpace('reading'))!.records.length;await page.getByRole('button',{name:'Publish website',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(live().getByRole('heading',{name:'The Interactive Reading Room'})).toBeVisible();expect(page.url()).toBe(`${origin}/s/reading`);const content=await page.frames().find(f=>f.url().includes('/api/generated-frame')&&!f.url().includes('generation='))!.evaluate(()=>JSON.stringify((window as any).fixtureState));expect(content).not.toContain('PRIVATE_FRAME_SENTINEL');expect(content).not.toContain('private_note');await live().getByLabel('Book title').fill('A real bridge write');await live().getByRole('button',{name:'Save entry'}).click();await expect(live().getByRole('status')).toHaveText('Saved through the host');expect((await api.store.getSpace('reading'))!.records.length).toBe(before+1);await page.reload();await expect(live().getByText(`${before+1} records, kept safe.`)).toBeVisible();});
 await check('Same-account fresh CSRF sends one bridge write and reconnects the frame to saved state',async()=>{const before=(await api.store.getSpace('reading'))!.records.length;const oldSrc=await page.locator('iframe[title="Generated website"]').getAttribute('src');let posts=0;const count=(request:any)=>{if(request.method()==='POST'&&request.url().endsWith('/actions'))posts++};page.on('request',count);await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});await live().getByLabel('Book title').fill('Refreshed session bridge write');await live().getByRole('button',{name:'Save entry'}).click();await expect.poll(async()=>(await api.store.getSpace('reading'))!.records.length).toBe(before+1);await expect(page.locator('iframe[title="Generated website"]')).not.toHaveAttribute('src',oldSrc!);await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');await expect(live().getByText(`${before+1} records, kept safe.`)).toBeVisible();page.off('request',count);expect(posts).toBe(1);});
 await check('Explicit host image selection saves a reference and restores the image after reload',async()=>{await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');await live().getByRole('button',{name:'Choose a photo'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Add an image',exact:true})).toBeVisible();await page.locator('input[type=file]').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:Buffer.from(await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=40;canvas.height=40;const context=canvas.getContext('2d')!;context.fillStyle='#778b6a';context.fillRect(0,0,40,40);return canvas.toDataURL('image/png').split(',')[1]}),'base64')});await expect(live().getByRole('status')).toContainText('asset_');expect((await api.store.getSpace('reading'))!.records[0].values.photo).toMatch(/^asset_/);await page.reload();await expect(live().locator('#photo')).toHaveAttribute('src',/^data:image/);});
 await check('Destructive frame requests need host confirmation; visitor writes request sign-in',async()=>{const before=(await api.store.getSpace('reading'))!.records.length;await live().getByRole('button',{name:'Remove first record'}).click();await expect(page.getByRole('heading',{name:'Delete this record?'})).toBeVisible();await page.getByRole('button',{name:'Keep record',exact:true}).click();expect((await api.store.getSpace('reading'))!.records.length).toBe(before);const visitor=await browser.newContext({reducedMotion:'reduce'});const tab=await visitor.newPage();await tab.goto(`${origin}/s/reading`);const vf=tab.frameLocator('iframe[title="Generated website"]');await expect(tab.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');await vf.getByLabel('Book title').fill('Visitor attempt');await vf.getByRole('button',{name:'Save entry'}).focus();await tab.keyboard.press('Enter');await expect(tab.getByRole('heading',{name:'Make this moment yours.'})).toBeVisible().catch(async error=>{await writeFile(`${root}/LF-226-base-regression-visitor-failure.json`,JSON.stringify({body:await tab.locator('body').innerText(),frames:await Promise.all(tab.frames().filter(f=>f.parentFrame()).map(async f=>({text:await f.locator('body').innerText(),state:await f.evaluate(()=>JSON.stringify((window as any).fixtureState))})))},null,2));throw error});expect((await api.store.getSpace('reading'))!.records.length).toBe(before);await visitor.close();});
 await check('Runtime failure repairs once; explicit publication preserves records, image and URL',async()=>{const version=(await api.store.getSpace('reading'))!.definition!.definitionVersion;await page.getByRole('button',{name:'Open the space designer'}).click();await page.getByRole('textbox',{name:'Describe your website'}).fill('Please test the repair fixture');await page.getByRole('button',{name:'Create website',exact:true}).click();await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled({timeout:25000});expect((await api.store.getSpace('reading'))!.definition!.definitionVersion).toBe(version);await expect(frame().getByRole('button',{name:'Count a moment · 0'})).toBeVisible();await page.getByRole('button',{name:'Phone',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.locator('.studio-workbench').scrollIntoViewIfNeeded();await page.screenshot({path:`${root}/LF-226-base-regression-studio-mobile.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Publish website',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(live().getByRole('heading',{name:'The Interactive Reading Room'})).toBeVisible();expect((await api.store.getSpace('reading'))!.definition!.definitionVersion).toBe(version+1);expect((await api.store.getSpace('reading'))!.records[0].values.photo).toMatch(/^asset_/);await expect(live().locator('#photo')).toHaveAttribute('src',/^data:image/);expect(page.url()).toBe(`${origin}/s/reading`);});
 await check('Explicit cancellation suppresses late preview and preserves the live version',async()=>{const version=(await api.store.getSpace('reading'))!.definition!.definitionVersion;await page.getByRole('button',{name:'Open the space designer'}).click();await page.getByRole('textbox',{name:'Describe your website'}).fill('A slow fixture website');await page.getByRole('button',{name:'Create another revision',exact:true}).click();await page.getByRole('button',{name:'Stop generation',exact:true}).click();await expect(page.getByText('Generation stopped',{exact:true})).toBeVisible();await page.waitForTimeout(2100);await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeDisabled();expect(await page.locator('iframe[title="Generated website preview"]').count()).toBe(0);expect((await api.store.getSpace('reading'))!.definition!.definitionVersion).toBe(version);await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Open the space designer'})).toBeFocused();});
 await check('New space description creates a blank space then enters the same generation flow',async()=>{await page.setViewportSize({width:1440,height:1080});await page.getByRole('button',{name:'Create a new space'}).click();await page.getByLabel('Give it a name').fill('New generated space');await page.getByLabel('What would you like to keep here? (optional)').fill('Create a custom interactive website');await page.getByRole('button',{name:'Create my space'}).click();await expect(page.getByRole('heading',{name:'An idea. A website. Yours.'})).toBeVisible();await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled();expect((await api.store.getSpace(new URL(page.url()).pathname.split('/').at(-1)!))!.definition).toBeNull();await page.getByRole('button',{name:'Close',exact:true}).click();const beforeCalls=calls;await page.locator('.space-nav a[href="/s/habits"]').click();await expect(page).toHaveURL(`${origin}/s/habits`);await expect(page.getByRole('button',{name:'Open the space designer'})).toBeVisible();await page.waitForTimeout(700);expect(await page.getByRole('dialog').count()).toBe(0);expect(calls).toBe(beforeCalls);});
 await check('Optional module gallery still exposes 60 reusable modules separately',async()=>{const gallery=await context.newPage();await gallery.goto(`${origin}/modules`);await expect(gallery.getByText('60 matching modules · mobile and desktop ready')).toBeVisible();await gallery.getByRole('searchbox').fill('generated-site');await expect(gallery.getByText('0 matching modules · mobile and desktop ready')).toBeVisible();await gallery.close();});
 expect(errors).toEqual(['Fixture startup failure']);
 await writeFile(`${root}/LF-226-base-regression-browser-results.json`,JSON.stringify({at:new Date().toISOString(),scope:'Real local API/PGlite/Chrome and strict sandbox with offline fixture generator. No provider calls.',checks,calls,expectedFixtureErrors:errors},null,2));
} catch(error){await page.screenshot({path:`${root}/LF-226-base-regression-failed.png`,fullPage:true});await writeFile(`${root}/LF-226-base-regression-failed.json`,JSON.stringify({error:String(error),body:await page.locator('body').innerText(),frames:await Promise.all(page.frames().filter(frame=>frame.parentFrame()).map(async frame=>({url:frame.url(),text:await frame.locator('body').innerText().catch(()=>'(detached)')}))),errors},null,2));throw error}finally{await context.close();await browser.close();await api.app.close()}
