import {chromium,expect,type BrowserContext,type Page} from '@playwright/test';
import {resolve} from 'node:path';
import {writeFile} from 'node:fs/promises';
import {buildApp} from '../../../../apps/api/src/app';
import {createDatabase} from '../../../../packages/db/src/index';
import {componentSchema,readingDefinition,type SiteGenerator,type Proposal} from '../../../../packages/contracts/src/index';
process.env.ENABLE_LOCAL_DEMO='true';process.env.NODE_ENV='test';
const origin='http://localhost:4348',root='docs/memory/handoffs/frontend';
const calls:Array<{prompt:string;repair:boolean;errors:string[]}>=[],posts:Array<{path:string;body:any}>=[],checks:string[]=[],errors:string[]=[];
let releaseRepair:(()=>void)|null=null;
const generator:SiteGenerator=async input=>{calls.push({prompt:input.prompt,repair:!!input.repair,errors:input.repair?.errors??[]});input.onProgress?.({stage:'writing',message:'Offline fixture source ready.'});if(input.repair)await new Promise<void>(resolve=>{releaseRepair=resolve;setTimeout(resolve,2500)});const current=input.current??readingDefinition();return {entitySchema:current.entitySchema,appSpec:{...current.appSpec,title:'A feedback fixture',components:[componentSchema.parse({id:'fixture',type:'generated-site',version:1,fields:current.entitySchema.fields.filter(field=>field.public).map(field=>field.id),actionIds:current.appSpec.actions.filter(action=>action.type!=='tool.invoke').map(action=>action.id)})],generated:{format:'html-v1',bridgeVersion:1,assetIds:[],html:'<main><h1>Try the interaction</h1><button id="choose">Choose an image</button><p id="message" role="status"></p></main>',css:'body{font:16px system-ui;background:#f3eee5;color:#35412c}main{padding:36px}h1{font:36px Georgia}button{font:inherit;padding:14px;border-radius:8px;background:white;border:1px solid #888}',js:`(async()=>{await lf.ready;document.getElementById('choose').onclick=()=>document.getElementById('message').textContent=${input.repair?'"The repaired interaction works"':'"The chooser did not open"'};lf.reportReady()})();`}},summary:'Offline interaction-feedback fixture.',source:'gemini',capabilityGaps:[]} satisfies Proposal};
const api=await buildApp({db:await createDatabase(),origin,localDemo:true,siteGenerator:generator,staticDir:resolve('apps/web/dist')});await api.app.listen({host:'127.0.0.1',port:4348});const browser=await chromium.launch({headless:true,channel:'chrome'});
const contexts:BrowserContext[]=[];
async function owner(){const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'});contexts.push(context);await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()==='POST'&&new URL(request.url()).pathname.endsWith('/preview'))posts.push({path:new URL(request.url()).pathname,body:request.postDataJSON()})});await page.goto(`${origin}/s/reading`);return {context,page};}
async function draft(page:Page,prompt:string){await page.getByRole('button',{name:'Open the space designer'}).click();await page.getByRole('textbox',{name:'Describe your website'}).fill(prompt);await page.getByRole('button',{name:'Create website',exact:true}).click();await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Report an issue',exact:true}).click();await expect(page.getByRole('button',{name:'Request repair',exact:true})).toBeDisabled();await expect(page.getByLabel('What should work differently?')).toHaveAttribute('maxlength','500');}
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.log('PASS',name)}
const first=await owner();const page=first.page;
try{
 await check('Checked draft accepts explicit bounded feedback and actual host repairs one source revision; live data and original prompt stay intact',async()=>{
  const original='Build an original image interaction for this offline fixture';await draft(page,original);const input=page.getByLabel('What should work differently?');const feedback='The image button reports a message instead of opening the chooser. Make that interaction work.';await input.fill(feedback);await page.getByRole('button',{name:'Hide feedback'}).click();await page.getByRole('button',{name:'Report an issue'}).click();await expect(input).toHaveValue(feedback);await page.locator('.studio-feedback-actions').scrollIntoViewIfNeeded();await page.screenshot({path:`${root}/LF-232-feedback-desktop.png`});
  const response=page.waitForResponse(response=>response.request().method()==='POST'&&response.url().endsWith('/preview')&&response.request().postDataJSON().ok===false);await page.getByRole('button',{name:'Request repair',exact:true}).click();const repaired=await(await response).json();expect(repaired).toMatchObject({stage:'repairing',sourceRevision:2,repairCount:1});await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeDisabled();expect((await api.store.getSpace('reading'))!.definition!.definitionVersion).toBe(1);expect(calls.filter(call=>call.repair)).toHaveLength(1);expect(calls.at(-1)?.errors).toEqual([feedback]);releaseRepair?.();await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled();await expect(page.locator('.studio-feedback-limit')).toContainText('used its one repair attempt');expect(await page.getByRole('button',{name:'Request repair',exact:true}).count()).toBe(0);await expect(page.getByRole('textbox',{name:'Describe your website'})).toHaveValue(original);await page.frameLocator('iframe[title="Generated website preview"]').getByRole('button',{name:'Choose an image'}).click();await expect(page.frameLocator('iframe[title="Generated website preview"]').getByRole('status')).toHaveText('The repaired interaction works');await page.setViewportSize({width:390,height:844});await page.locator('.studio-feedback-limit').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${root}/LF-232-feedback-mobile.png`});const records=(await api.store.getSpace('reading'))!.records;await page.getByRole('button',{name:'Publish website',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await api.store.getSpace('reading'))!.records).toEqual(records);expect(page.url()).toBe(`${origin}/s/reading`);expect((await api.store.getSpace('reading'))!.definition!.definitionVersion).toBe(2);
 });
 await check('A rejected report preserves feedback and blocks publication without retrying automatically',async()=>{const {context,page}=await owner();await draft(page,'Rejected feedback fixture');const text='The image interaction should open its chooser.';await page.getByLabel('What should work differently?').fill(text);let rejected=0;await context.route('**/generations/*/preview',async route=>{if(route.request().postDataJSON().ok===false){rejected++;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_UNAVAILABLE',message:'Offline fixture: repair is temporarily unavailable.'}})})}else await route.continue()});await page.getByRole('button',{name:'Request repair',exact:true}).click();await expect(page.getByRole('alert')).toContainText('repair is temporarily unavailable');await expect(page.getByLabel('What should work differently?')).toHaveValue(text);await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Request repair',exact:true})).toBeEnabled();await page.waitForTimeout(750);expect(rejected).toBe(1);await context.close()});
 await check('A new revision can finish its startup check before the older repair response arrives',async()=>{const {context,page}=await owner();await draft(page,'Reordered repair acknowledgment fixture');await page.getByLabel('What should work differently?').fill('Fix this normal image interaction.');let release:()=>void=()=>{},held=false;await context.route('**/generations/*/preview',async route=>{if(route.request().postDataJSON().ok!==false)return route.continue();const response=await route.fetch();held=true;await new Promise<void>(resolve=>{release=resolve});await route.fulfill({response}).catch(()=>{})});await page.getByRole('button',{name:'Request repair',exact:true}).click();await expect.poll(()=>held).toBe(true);releaseRepair?.();await expect(page.locator('.generation-progress>.eyebrow')).toHaveText('Preview checked — ready to publish');await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeDisabled();release();await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled();await expect(page.locator('.studio-feedback-limit')).toContainText('one repair attempt');await context.close()});
 await check('Changed identity before feedback preflight sends zero reports and keeps Owner-only UI away',async()=>{const {context,page}=await owner();await draft(page,'Identity preflight fixture');await page.getByLabel('What should work differently?').fill('Please fix the image interaction.');const before=posts.filter(post=>post.body.ok===false).length;await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'participant'}});await page.getByRole('button',{name:'Request repair',exact:true}).click();await expect(page.getByRole('button',{name:'Open the space designer'})).toHaveCount(0);expect(posts.filter(post=>post.body.ok===false)).toHaveLength(before);await expect(page.getByRole('dialog')).toHaveCount(0);await context.close()});
 await check('An actual repair response delayed past navigation cannot reopen or alter the next space',async()=>{const {context,page}=await owner();await draft(page,'Late feedback response fixture');await page.getByLabel('What should work differently?').fill('Fix the image interaction before publication.');let release:()=>void=()=>{};let held=false;await context.route('**/generations/*/preview',async route=>{if(route.request().postDataJSON().ok!==false)return route.continue();const response=await route.fetch();held=true;await new Promise<void>(resolve=>{release=resolve});await route.fulfill({response}).catch(()=>{})});await page.getByRole('button',{name:'Request repair',exact:true}).click();await expect.poll(()=>held).toBe(true);await page.keyboard.press('Escape');await page.locator('.space-nav a[href="/s/habits"]').click();await expect(page).toHaveURL(`${origin}/s/habits`);release();releaseRepair?.();await expect(page.getByRole('heading',{name:'Little by little.',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Open the space designer'}).click();await expect(page.getByRole('textbox',{name:'Describe your website'})).toHaveValue('');expect(await page.locator('.studio-feedback').count()).toBe(0);await context.close()});
 expect(errors).toEqual([]);await writeFile(`${root}/LF-232-browser-results.json`,JSON.stringify({at:new Date().toISOString(),scope:'Real Chrome, local API/PGlite, actual host repair state/revision with an offline generator. Rejection and delayed-delivery transport fixtures are explicit. No external services.',checks,calls,feedbackReports:posts.filter(post=>post.body.ok===false),errors},null,2));
}catch(error){await page.screenshot({path:`${root}/LF-232-failed.png`,fullPage:true});await writeFile(`${root}/LF-232-failed.json`,JSON.stringify({error:String(error),body:await page.locator('body').innerText(),calls,posts,errors},null,2));throw error}finally{releaseRepair?.();for(const context of contexts)await context.close();await browser.close();await api.app.close()}
