import {chromium,expect,type BrowserContext,type Route} from '@playwright/test';
import {resolve} from 'node:path';
import {writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {buildApp} from '../../../../apps/api/src/app';
import {applyProposal} from '../../../../apps/api/src/domain';
import {createDatabase} from '../../../../packages/db/src/index';
import {componentSchema,readingDefinition,type Proposal,type GenerationJob,type GenerationOutline,type GeneratedToolSpec} from '../../../../packages/contracts/src/index';
process.env.ENABLE_LOCAL_DEMO='true';process.env.NODE_ENV='test';
const origin='http://localhost:4336',root='docs/memory/handoffs/frontend';
const api=await buildApp({db:await createDatabase(),origin,localDemo:true,staticDir:resolve('apps/web/dist')});
const current=(await api.store.getSpace('reading'))!;current.definition!.entitySchema.fields.push({id:'private_note',label:'Private note',type:'text',required:false,public:false});current.records[0].values.private_note='PRIVATE_FRAME_SENTINEL';await api.store.db.transaction(tx=>api.store.event(current,'definition.published',tx));
await api.app.listen({host:'127.0.0.1',port:4336});
const tool:GeneratedToolSpec={kind:'code-js-v1',toolId:'readingInsights',toolVersion:2,name:'Reading insights',description:'A read-only summary of the public reading list.',source:'async function run(input, api) { const rows = await api.readRecords({fields:["title"]}); return {summary: input.prefix + rows.length + " books"}; }',inputSchema:{type:'object',properties:{prefix:{type:'string',maxLength:100}},required:['prefix'],additionalProperties:false},outputSchema:{type:'object',properties:{summary:{type:'string'}},required:['summary'],additionalProperties:false},sideEffects:'none',capabilities:{publicRecordFields:['title'],connectors:[]},tests:[{name:'Empty reading list',input:{prefix:'You have '},expected:{summary:'You have 0 books'},records:[]},{name:'One book',input:{prefix:'You have '},expected:{summary:'You have 1 books'},records:[{id:'one',version:1,values:{title:'A book'}}]}]};
const makeProposal=():Proposal=>{const definition=readingDefinition();return {entitySchema:current.definition!.entitySchema,appSpec:{...definition.appSpec,title:'Reading with perspective',description:'An offline browser fixture for tool and progress interactions.',layout:'flow',actions:[...definition.appSpec.actions,{id:'insights',type:'tool.invoke',label:'Reading insights'}],components:[componentSchema.parse({id:'custom-site',type:'generated-site',version:1,fields:definition.entitySchema.fields.filter(field=>field.public).map(field=>field.id),actionIds:[...definition.appSpec.actions.map(action=>action.id),'insights'],toolBindings:[{actionId:'insights',toolId:tool.toolId,toolVersion:2,kind:'generated'}]})],generated:{format:'html-v1',bridgeVersion:1,assetIds:[],html:'<main><small>READING WITH PERSPECTIVE</small><h1>A little insight.</h1><p id="count"></p><label>Summary introduction<input id="prefix" value="You have "></label><button id="run">Run reading insights</button><button id="wrong">Try another version</button><p id="result" role="status"></p></main>',css:'body{margin:0;background:#eaf0e3;color:#35412c;font:16px system-ui}main{padding:40px 26px;max-width:620px;margin:auto}small{letter-spacing:2px;font-size:10px}h1{font:52px Georgia;line-height:1.1}label{display:grid;gap:8px;margin:24px 0}input,button{font:inherit;padding:13px;border:1px solid #89927f;border-radius:8px;background:#fafbf6}button{display:block;margin:10px 0;cursor:pointer}input{min-width:0}#result{font-size:13px;min-height:3em}',js:'(async()=>{const state=await lf.ready;window.fixtureState=state;document.getElementById("count").textContent=state.records.length+" saved books";const output=document.getElementById("result");async function run(version){output.textContent="Working…";try{const response=await lf.runTool("readingInsights",version,{prefix:document.getElementById("prefix").value});output.textContent=response.result.summary}catch(error){output.textContent=error.message}}document.getElementById("run").onclick=()=>run(2);document.getElementById("wrong").onclick=()=>run(1);lf.reportReady();})();'}},summary:'Offline UI fixture with a bound tool.',source:'gemini',capabilityGaps:[],codeToolProposals:[tool]};};
let job:GenerationJob|null=null,posts:any[]=[],gate:(()=>void)|null=null,waitForRelease=false,failTool=false;
const outline:GenerationOutline={version:1,title:'Reading with perspective',layout:'flow',skin:'sage',sections:[{id:'introduction',kind:'hero',label:'A welcoming introduction',columns:12}]};
const report={ok:true,results:[{name:'Empty reading list',ok:true,message:'Offline host test report: expected result matched.'},{name:'One book',ok:true,message:'Offline host test report: expected result matched.'}]};
function event(stage:GenerationJob['stage'],ui?:GenerationOutline){if(!job)throw new Error('No job');job.stage=stage;job.events.push({sequence:(job.events.at(-1)?.sequence??0)+1,sourceRevision:job.sourceRevision,stage,at:new Date().toISOString(),message:`Fixture host checkpoint: ${stage}`,...(ui?{ui}:{})});}
async function json(route:Route,value:unknown,status=200){await route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)}).catch(()=>{});}
async function fixtures(context:BrowserContext){
 await context.route('**/api/spaces/reading/generations**',async route=>{const url=new URL(route.request().url()),method=route.request().method();
  if(method==='POST'&&url.pathname.endsWith('/generations')){const body=route.request().postDataJSON();job={id:randomUUID(),spaceId:current.space.id,slug:'reading',requestId:body.requestId,baseDefinitionVersion:body.baseDefinitionVersion,sourceRevision:1,stage:'planning',prompt:body.prompt,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),repairCount:0,events:[]};event('planning');return json(route,job,202);}
  if(url.pathname.endsWith('/events')){const after=Number(url.searchParams.get('after')??0);return route.fulfill({status:200,contentType:'text/event-stream',body:(job?.events??[]).filter(event=>event.sequence>after).map(event=>`id: ${event.sequence}\nevent: generation\ndata: ${JSON.stringify(event)}\n\n`).join('')||': no new fixture checkpoints\n\n'});}
  if(method==='POST'&&url.pathname.endsWith('/preview')){event('checked');return json(route,job);}
  if(method==='POST'&&url.pathname.endsWith('/cancel')){event('cancelled');return json(route,job);}
  if(method==='POST'&&url.pathname.endsWith('/publish')){const state=(await api.store.getSpace('reading'))!;await api.store.db.transaction(async tx=>{applyProposal(state,job!.proposal!);await api.store.event(state,'definition.published',tx)});event('published');return json(route,{job,snapshot:{}});}
  return json(route,job);
 });
 // Generation job storage and tool execution are explicitly fixture responses;
 // the host app, session guard, published space, frame loader and bridge are real.
 await context.route('**/api/generated-frame?*generation=*',async route=>{const {renderGeneratedFrame,GENERATED_FRAME_CSP,GENERATED_FRAME_PERMISSIONS}=await import('../../../../apps/api/src/generated-frame');const url=new URL(route.request().url());return route.fulfill({status:200,headers:{'Content-Type':'text/html','Content-Security-Policy':GENERATED_FRAME_CSP,'Permissions-Policy':GENERATED_FRAME_PERMISSIONS,'Referrer-Policy':'no-referrer'},body:renderGeneratedFrame(job!.proposal!.appSpec.generated!,url.searchParams.get('channel')!)});});
 await context.route('**/api/spaces/reading/code-tools/readingInsights/invoke',async route=>{posts.push({body:route.request().postDataJSON(),hasCsrf:!!route.request().headers()['x-csrf-token']});if(waitForRelease)await new Promise<void>(resolve=>{gate=resolve});if(failTool)return json(route,{error:{code:'TOOL_FAILED',message:'The fixture tool could not complete this request.'}},503);return json(route,{toolId:tool.toolId,toolVersion:2,result:{summary:`${route.request().postDataJSON().input.prefix}${current.records.length} books`},reused:posts.length>1});});
 await context.route('**/api/spaces/reading/code-tools',route=>json(route,{tools:[{spec:tool,enabled:true,verifiedAt:new Date().toISOString(),sourceDigest:'fixture-digest',testReport:report,invocationCount:1}]}));
}
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'no-preference'});await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'owner'}});await fixtures(context);const page=await context.newPage();page.setDefaultTimeout(15000);const checks:string[]=[],errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));const preview=()=>page.frameLocator('iframe[title="Generated website preview"]'),live=()=>page.frameLocator('iframe[title="Generated website"]');
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.log('PASS',name)}
try{
 await page.goto(`${origin}/s/reading`);await page.getByRole('button',{name:'Open the space designer'}).click();await page.getByRole('textbox',{name:'Describe your website'}).fill('Offline fixture: build a reading insights website');await page.getByRole('button',{name:'Create website',exact:true}).click();
 await check('No fabricated outline before a real checkpoint; actual stable sections reshape and add content',async()=>{await expect(page.getByText('Waiting for the next layout checkpoint.',{exact:false})).toBeVisible();expect(await page.locator('[data-outline-id]').count()).toBe(0);await expect.poll(()=>job!==null).toBe(true);event('planning',outline);await page.getByRole('button',{name:'Refresh generation'}).click();await expect(page.locator('[data-outline-id=introduction]')).toBeVisible();await page.locator('[data-outline-id=introduction]').evaluate(element=>{(element as any).fixtureIdentity='kept'});event('writing',{...outline,layout:'split',sections:[{id:'introduction',kind:'hero',label:'An intimate reading room',columns:8},{id:'insights',kind:'metrics',label:'Perspective at a glance',columns:4,items:2},{id:'shelves',kind:'collection',label:'A shelf for your books',columns:12,items:4}]});await page.getByRole('button',{name:'Refresh generation'}).click();await expect(page.locator('[data-outline-id]')).toHaveCount(3);expect(await page.locator('[data-outline-id=introduction]').evaluate(element=>(element as any).fixtureIdentity)).toBe('kept');await expect(page.locator('[data-outline-id=introduction]')).toHaveCSS('--outline-columns','8');await expect(page.locator('[data-outline-id=shelves]')).toHaveCSS('opacity','1');await expect(page.locator('[data-outline-id=introduction]')).toHaveCSS('transform','none');await page.screenshot({path:`${root}/LF-226-formation-desktop.png`});});
 await check('Reduced-motion phone formation keeps all sections readable without overflow',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Phone',exact:true}).click();await page.locator('.formation').scrollIntoViewIfNeeded();await page.screenshot({path:`${root}/LF-226-formation-mobile.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.locator('.formation-section').evaluateAll(elements=>elements.every(element=>element.scrollWidth<=element.clientWidth+1))).toBe(true);await page.setViewportSize({width:1440,height:1080});await page.getByRole('button',{name:'Desktop',exact:true}).click();});
 await check('Owner sees escaped tool source and actual host report; candidate tool calls stay read-only',async()=>{job!.proposal=makeProposal();job!.toolReports=[{toolId:tool.toolId,toolVersion:2,name:tool.name,report}];event('preview');await page.getByRole('button',{name:'Refresh generation'}).click();await expect(page.getByRole('button',{name:'Publish website',exact:true})).toBeEnabled();await page.getByRole('tab',{name:'Tools',exact:true}).click();await expect(page.locator('.tool-evidence-card code').first()).toContainText('async function run');await expect(page.getByText('Host tests passed',{exact:true})).toBeVisible();await expect(page.getByText('Pass · Empty reading list',{exact:true})).toBeVisible();await page.screenshot({path:`${root}/LF-226-tool-evidence.png`});await page.getByRole('tab',{name:'Preview',exact:true}).click();await expect(page.locator('.is-preview .generated-frame-status [role=status]')).toHaveText('Website ready');await preview().getByRole('button',{name:'Run reading insights'}).click();await expect(preview().getByRole('status')).toContainText('Tools are disabled in preview');expect(posts.length).toBe(0);await page.getByRole('button',{name:'Publish website',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');});
 await check('Exact bound tool request uses fresh auth; pending, result, error and unbound version are explicit',async()=>{waitForRelease=true;await live().getByRole('button',{name:'Run reading insights'}).click();await expect(page.getByText('Running the connected tool…',{exact:true})).toBeVisible();await expect.poll(()=>gate!==null).toBe(true);gate!();gate=null;waitForRelease=false;await expect(live().getByRole('status')).toHaveText(`You have ${current.records.length} books`);await expect(page.getByText('Tool completed.',{exact:false})).toBeVisible();expect(posts[0]).toMatchObject({hasCsrf:true,body:{definitionVersion:2,componentId:'custom-site',actionId:'insights',toolVersion:2,input:{prefix:'You have '}}});const frame=page.frames().find(frame=>frame.url().includes('/api/generated-frame'))!;const publicState=await frame.evaluate(()=>JSON.stringify((window as any).fixtureState));expect(publicState).toContain('toolBindings');for(const privateValue of ['PRIVATE_FRAME_SENTINEL','async function run','csrfToken','sourceDigest'])expect(publicState).not.toContain(privateValue);await live().getByRole('button',{name:'Try another version'}).focus();await page.keyboard.press('Enter');await expect(live().getByRole('status')).toContainText('exact tool version');expect(posts.length).toBe(1);failTool=true;await live().getByRole('button',{name:'Run reading insights'}).click();await expect(page.locator('.generated-tool-status[role=alert]')).toContainText('fixture tool could not complete');await expect(live().getByRole('status')).toContainText('fixture tool could not complete');expect(posts.length).toBe(2);failTool=false;});
 await check('Anonymous tool use opens host login without executing or replaying',async()=>{const visitor=await browser.newContext({reducedMotion:'reduce'});await fixtures(visitor);const tab=await visitor.newPage();await tab.goto(`${origin}/s/reading`);await expect(tab.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');await tab.frameLocator('iframe').getByRole('button',{name:'Run reading insights'}).focus();await tab.keyboard.press('Enter');await expect(tab.getByRole('heading',{name:'Make this moment yours.'})).toBeVisible().catch(async error=>{await writeFile(`${root}/LF-226-browser-visitor-failure.json`,JSON.stringify({body:await tab.locator('body').innerText(),frames:await Promise.all(tab.frames().filter(f=>f.parentFrame()).map(async f=>({text:await f.locator('body').innerText(),state:await f.evaluate(()=>JSON.stringify((window as any).fixtureState))})))},null,2));throw error});expect(posts.length).toBe(2);expect(await tab.getByRole('button',{name:'Open the space designer'}).count()).toBe(0);await visitor.close();});
 await check('Reused exact-version tool source and saved test evidence load only in Owner studio',async()=>{await context.route('**/api/spaces/reading/code-tools',route=>json(route,{tools:[{spec:tool,enabled:true,verifiedAt:new Date().toISOString(),sourceDigest:'fixture-digest',testReport:report,invocationCount:2}]}));await page.getByRole('button',{name:'Open the space designer'}).click();await page.getByRole('textbox',{name:'Describe your website'}).fill('Reuse the reading insights tool in the next design');await page.getByRole('button',{name:'Create another revision',exact:true}).click();await expect.poll(()=>job?.stage).toBe('planning');job!.proposal=makeProposal();job!.proposal!.codeToolProposals=[];event('preview');await page.getByRole('button',{name:'Refresh generation'}).click();await page.getByRole('tab',{name:'Tools',exact:true}).click();await expect(page.locator('.tool-evidence-card code').first()).toContainText('async function run');await expect(page.getByText('Host tests passed',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
 await check('Identity change discards an in-flight tool response and the next account cannot use Owner tools',async()=>{waitForRelease=true;await live().getByRole('button',{name:'Run reading insights'}).click();await expect.poll(()=>gate!==null).toBe(true);await context.request.post(`${origin}/auth/local`,{headers:{origin},data:{persona:'participant'}});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Open the space designer'})).toHaveCount(0);gate!();gate=null;waitForRelease=false;await expect(page.locator('.generated-frame-status [role=status]')).toHaveText('Website ready');await live().getByRole('button',{name:'Run reading insights'}).click();await expect(live().getByRole('status')).toContainText('cannot use this tool');expect(posts.length).toBe(3);expect(await page.getByText('Tool completed.',{exact:false}).count()).toBe(0);});
 expect(errors).toEqual([]);await writeFile(`${root}/LF-226-browser-results.json`,JSON.stringify({at:new Date().toISOString(),scope:'Real Chrome/local PGlite/session/TT frame; explicitly fixture generation progress/jobs/tool reports/invocations. No provider calls or QuickJS execution claim.',checks,toolPosts:posts.length,errors},null,2));
}catch(error){await page.screenshot({path:`${root}/LF-226-failed.png`,fullPage:true});await writeFile(`${root}/LF-226-failed.json`,JSON.stringify({error:String(error),body:await page.locator('body').innerText(),posts,frames:await Promise.all(page.frames().filter(frame=>frame.parentFrame()).map(async frame=>({url:frame.url(),text:await frame.locator('body').innerText().catch(()=>'(detached)')}))),errors},null,2));throw error}finally{gate?.();await context.close();await browser.close();await api.app.close()}
